### ISSUE TITLE
Make half and third custom definable

### ISSUE THREAD

**Issue by Flor-IT** [eczarny/spectacle#100]
Hi,
first, let me thank You for this great app. :)

I´m using Spectacle with a FullHD-Display for Web-Coding and have browser and code windows arranged. A half-half divider is not the optimal arrangement for this, 2/3 and 1/3 make the code windows to small.

Would it be possible to make the divider proportions custom definable? Like 60/40 or like golden ratio (62/38). 
I´ve done some iOS programming before. I could try to implement it for myself if You say that it should be possible with tiny effort. But if much of the logic has to be changed for this I´m not able to do it (in reasonable time ;) .

Let me know what You think about that,
Bye

**Comment by ssbarnea** [comment]
Any reason why this was closed? On a 5K display there is a huge need to split display into somethink like 40/60.
