### ISSUE TITLE
Combo of two Arrow keys?

### ISSUE THREAD

**Issue by LEMONed** [eczarny/spectacle#105]
The only reason I'm still using Hyperdock is that it allows me to use not just one but two arrow keys in a hotkey combination.

For instance, I can press **^⎇←↑** together to get a window snapped to the top left corner.
I personally think that this combo makes much better sense than two modifier keys + one arrow key.

I'd appreciate it if this feature is added to Spectacle.

**Comment by kirstu** [comment]
Yes. Less key combos to remember is always good

**Comment by diwu1989** [comment]
I would really appreciate this too, to be able to combo the corners

**Comment by rayshan** [comment]
+1

**Comment by eczarny** [comment]
Closing in favor of #442.
