### ISSUE TITLE
Control percent of Make Larger/Make Smaller

### ISSUE THREAD

**Issue by natew** [eczarny/spectacle#114]
Excellent app, my one request would be to allow adjusting these options to a percent of the current screen size.

Right now I have to press them 3-4 times on average.  Would be better if they could nudge a larger percent.

**Comment by kaspermalfroid** [comment]
I would also love to see this feature implemented!

**Comment by spartanatreyu** [comment]
If you're happy to build the app yourself, I found where you can customise it.

Open Spectacle/Sources/SpectacleConstants.m

Change line 62 from:
```const CGFloat kWindowSizeOffset = 30.0f;```
to:
```const CGFloat kWindowSizeOffset = 150.0f;```

You can make the number higher or lower depending on how much you want it to change, 150 is 5 times 30 so setting it to 150 is the same as pressing the shortcut 5 times.

I'm not really familiar with objective-c or mac programs themselves, so I can't make this a preference or whatever. This would have to be something @eczarny would have to look at, and he might already have something like this planned anyway.

**Comment by shrx** [comment]
+1, came here to ask this.
