### ISSUE TITLE
Terminal resize to half not holding when opening new tabs

### ISSUE THREAD

**Issue by natew** [eczarny/spectacle#125]
On a Macbook Air 13" with 10.8 when I resize the terminal to the right half of the screen and then open a new tab, it about the entire tabs width *past* the right side of the screen, so I have to run the resize to right half shortcut again.

I have the source here (I used it to bump up the resize percent a little), if anyone can point me in the right direction I can take a stab at it.

I know that ShiftIt handles this properly, and it is also open source as well.

**Comment by un5t0ppab13** [comment]
**Resize your Terminal in Mac Preferences to fit your needs:**

Open Terminal with Spotlight
	
	Cmd space 
	Type Terminal	
	Click Enter

Open Preferences
	
	Cmd ,

Select Window Tab

Look at Window Size, Columns & Rows, often shows:

	80 24		

> Optionally: Resize your window to fix your desired new size

> Pause and think, 24 lines, how wide is a line? 

> OK, how many do I need?

Increase column size if when you both create a new tab or new window it is not the same size as your desired size.

Trial and error, just attempt to keep your estimates close and it will be brief.

Similarly decrease if it is too large, for example, on this 1920 x 1200 scaled display the following is great for me.

	130 40
	
Test your new setting by opening a new tab 

	Cmd t
	
Place your window over the previous one, is it the same size or close enough for you? If not keep resizing, until it is.
	
Open a new terminal window also and do similarly.

	Cmd n
	
Now consider using a window management program, I recommend Spectacle bc it is free as in free beer and freedom: https://github.com/eczarny/spectacle
	
You can then use the following to move windows quickly while a window is selected

	Cmd Ctrl right-arrow

This places the window in the top right corner 1/4 of the screen, left works similarly. If you also hold down shift it will place the window below in the 1/4 half of the screen

	Cmd Ctrl Shift right-arrow
	
Plenty more options are available, **enjoy!**

**Comment by qakart** [comment]
thats great its worked for me thanks
