### ISSUE TITLE
More than just halves and thirds

### ISSUE THREAD

**Issue by popshuvitdude** [eczarny/spectacle#127]
Feature request. Instead of working with halves and thirds, can we have two thirds, quarters and so on or whatever screen division the user specifies. Thanks.

**Comment by sharq88** [comment]
Hi. I love this little app, and helped me soo much, but now I bought a 21:9 screen, and would be great to divide the screen into 6 parts. There is a way to use 1/2, 1/3 and 2/3 but I can't use the middle part of the screen, it only jumps to the left or the right of the screen. I can not do 1/3 left, 1/3 center and 1/3 right. Is there any way to achieve this? Thanks again!

**Comment by genox** [comment]
I agree, divisions should be configurable. 1/3 subdivisions is not enough on a 21:9 screen. :-)
