### ISSUE TITLE
Dock issue with left/right positioning (on Mavericks?)

### ISSUE THREAD

**Issue by jamiehannaford** [eczarny/spectacle#142]
There's already been an issue raised about a centering problem with Mavericks (#141), but I'm encountering another one: if your dock is positioned to the left, when you shift a window either left or right there's a large overhanging. I'm using Matrox's TripleHead2Go external adapter, so I'm effectively used 1 widened display over 2 monitors (hence why it's so noticeable).

I think this is because it's adding 50% width on top of the dock width - so the left window is hanging over the central divide by however wide the dock is. The right window is also offset a bit too much.

If I reposition my dock to the bottom, or if I move it to another monitor, the problem goes away.

Is there a way for the "Left half" and "Right half" motions to incorporate the space taken up by a left/right dock?

**Comment by eczarny** [comment]
Sounds like this issue may have been addressed in a OS X update. Closing but please reopen if the problem persists.

**Comment by kvcrawford** [comment]
This is happening for me on OSX 10.10.5
