### ISSUE TITLE
Move windows between Spaces

### ISSUE THREAD

**Issue by eczarny** [eczarny/spectacle#15]
Spectacle should be able to move windows between Spaces.

**Comment by treeder** [comment]
+1, also using SizeUp for this.

**Comment by cristeahub** [comment]
Any news on this lately? I too am currently using SizeUp for this reason. Maybe private APIs or hacks to make this possible isn't such a bad idea after all? Seems like a lot of people want this feature after all.

**Comment by dnlek** [comment]
+1

**Comment by nadim7** [comment]
+1

**Comment by lukeadams** [comment]
There's a keyboard shortcut to move a window b/w spaces by default in OSX:
-Grab and hold the top
-[ctrl] + [left or right arrow key]
I don't have enough knowledge of Spectacle to dive in and implement it, but it seems relatively simple to do with the accessibility API.

**Comment by raldred** [comment]
:+1:

**Comment by lukeadams** [comment]
~/Library/Preferences/com.apple.spaces.plist has perfectly formatted information for spaces by monitor!

**Comment by lukeadams** [comment]
If anybody is interested in implementing it, [here](http://ianyh.com/blog/2013/06/05/accessibility/) is a good writeup using the KB+mouse method I mentioned above.

**Comment by amaltson** [comment]
This was closed but is it closed as won't implement?

**Comment by eczarny** [comment]
Correct. This isn't something I intend to build into Spectacle.

**Comment by nonameolsson** [comment]
I really would like to see this. I switched from Sizeup to Spectacle. But now I think that I will have to switch back. Great app though, like it more than SizeUp.

**Comment by Tritlo** [comment]
Why do you not want to implement this? IMO this would be a killer feature, especially on machines with small screens. Being able to group them by workspaces is great, as evidenced by XMonad, i3 and Unity on Linux.

**Comment by kas** [comment]
@eczarny This is my only gripe with OS X (besides not being able to open Trash with spotlight :P). Voicing my support for this feature

**Comment by markallasread** [comment]
+1 — one of the few deal breakers with osx is no hotkey support for moving things between spaces.

**Comment by mattatgiinsure** [comment]
Would you accept a pull request that implements this?

**Comment by matthewlmcclure** [comment]
Would you accept a pull request that implements this?

**Comment by chliul** [comment]
+1

**Comment by NullGuru** [comment]
+1

**Comment by lhlmgr** [comment]
@matthewlmcclure it seems so: 
> I don't think so. It isn't something that is easy to implement and I just don't have the time to focus on it. Perhaps somebody else who really wants this feature could take a crack at it?

https://github.com/eczarny/spectacle/issues/15#issuecomment-524395

**Comment by simgust** [comment]
+1

**Comment by Tukan3** [comment]
+1

**Comment by Ciebiada** [comment]
+1

I will use Hammerspoon for the time being, as it can do what Spectacle does + can manage spaces. Example config if anyone is interested: https://github.com/Ciebiada/dot-files/blob/master/hammerspoon/init.lua

**Comment by StianIsmar** [comment]
+1

**Comment by andreapesare** [comment]
+1
