### ISSUE TITLE
1/6 window

### ISSUE THREAD

**Issue by jdbaum** [eczarny/spectacle#151]
I just noticed the function that rotates left half/left third/left two thirds and love it (was that just added?). Could the same thing be applied to corner quarters? Switch between top-left quarter and top-left 1/6 (1/3 width and half height)? Then you could make one window 2/3 and two more 1/6 each. Nice on a wide screen.

**Comment by nii236** [comment]
This will be handy on LG's ultra wide monitor.

http://www.lg.com/au/it-monitors/lg-34UM95

**Comment by mvd7793** [comment]
As someone who just bought this monitor^ and has been enjoying Spectacle, +1 for this feature. :) I might poke around later and try to add it myself.

**Comment by guillaumesalagnac** [comment]
i'd love to see this feature added to Spectacle !

**Comment by eczarny** [comment]
Closing in favor of #427.
