### ISSUE TITLE
Hot key to activate/deactivate Spectacle

### ISSUE THREAD

**Issue by benhsu** [eczarny/spectacle#156]
Is it possible to have a hot key to activate Spectacle, and then deactivate it with another hot key when I'm done moving windows around?

Motivation: its hard to find key bindings that don't clash with my application specific key bindings, and I resize my windows very infrequently. When I'm not moving windows around I don't want to worry about resizing them by accident.

So I'm proposing a hotkey to enter Spectacle mode, lets say we make it F12. Then I'll hit F12 to enter spectacle mode, move and resize my windows using spectacle hot keys (and they can be keys that conflict with application hot keys, for example, I can use Cmd-Z to undo!), and when I'm done, I can hit F12 again, and all my keys would do what they're supposed to in the app I'm running

**Comment by srid** [comment]
My major annoyance with this other great piece of open source software -- having to remember/ recall the specific key bindings for moving/ resizing window in a particular -- will automatically go away of this feature is implemented.

[Moom](http://manytricks.com/moom/) works in this manner, so you can [look there](http://manytricks.com/blog/?p=3206) for some ideas.

**Comment by eczarny** [comment]
Closing in favor of #254. I plan to include a new menu item to help temporarily disable Spectacle globally or permanently for a particular application.
