### ISSUE TITLE
Detect and communicate potential conflicts with "unsupported" apps

### ISSUE THREAD

**Issue by eczarny** [eczarny/spectacle#178]
Many folks run into issues using Spectacle an apps that are "unsupported". Ideally Spectacle would work with every app, but it just isn't always possible. Sometimes apps employ tricks or hacks that break Spectacle's ability to manipulate them using Apple's Accessibility API. This isn't confirmed, just a very strong theory. I'll need to continue a deeper investigation.

I'm hoping that this change would somehow help communicate this issue. If Spectacle could somehow detect a conflict with an unsupported app it would be easy to display an error message explaining the situation.

**Comment by markhdavid** [comment]
Yes! Please! Can I contribute to make this happen?  I spend a lot of time in Adobe products, and they all have this problem.  Spectacle is great, and it's a huge drag that I cannot use it with Adobe (reader, audition, et al).

**Comment by eczarny** [comment]
Closing in favor of #254.
