### ISSUE TITLE
Safari in fullscreen mode

### ISSUE THREAD

**Issue by flohaase** [eczarny/spectacle#206]
Hi,

if I'm running Safari in fullscreen mode and then put the windows to left, right, up or down, it is not very useful. I've to leave the fullscreen mode and reenter it to solve the problem.

![bildschirmfoto 2014-05-14 um 16 38 38](https://cloud.githubusercontent.com/assets/5834841/2972629/fc4a1392-db75-11e3-9667-97e4fa5f208b.png)

Best regards,
Flo

**Comment by eczarny** [comment]
I had to revert the fix for this issue to address a larger problem described in #455.

**Comment by eczarny** [comment]
Closing in favor of #468.
