### ISSUE TITLE
Vertical 1/3, 2/3

### ISSUE THREAD

**Issue by dy-dx** [eczarny/spectacle#208]
I love that when you repeat the "Left Half / Right Half" actions, windows resize to 1/3 or 2/3 of the screen width. However, the "Top Half / Bottom Half" actions don't seem to have this functionality, which I really need.

**Comment by caseyyee** [comment]
Another vote for 1/3rds.   Especially useful for moving stuff between finder windows!

**Comment by dy-dx** [comment]
Fixed by https://github.com/eczarny/spectacle/pull/309.
Thank you @dwayneyuen & @eczarny! Hope this gets released soon.

**Comment by eczarny** [comment]
I'm hoping to cut a release this weekend!

**Comment by eczarny** [comment]
Reopening because of a regression @janniklorenz pointed out in issue #321.

**Comment by eczarny** [comment]
Okay, I believe I have a fix in place (see 3f8ac6941ec5116a6bf47eafdd1ba0e7f7fd1da5). Closing this issue out again.

**Comment by passsy** [comment]
Oh just discovered this works. Thanks!
