### ISSUE TITLE
Shortcuts set using numpad don't work when using number row and vice versa

### ISSUE THREAD

**Issue by dpmccabe** [eczarny/spectacle#241]
![screen shot 2014-07-27 at 2 13 36 pm](https://cloud.githubusercontent.com/assets/527578/3714901/f0043c98-15c2-11e4-9e7a-5597a6813cf5.png)

I set shortcuts for the various actions using ^⌘4, ^⌘6, etc., using the numpad on on external Apple keyboard connected to a MacBook Pro. These shortcuts don't work when I use the number keys on the number row, though, which is the only option available if I don't have the external keyboard connected.

So, I reassigned all the shortcuts using the keys on the number row, which work fine, but then I can't use the numpad keys to trigger them. It's confusing because the UI shows "^⌘4" regardless of which "4" I pressed, even though only one of them will work.

Is it possible to get the shortcuts to trigger in either case? If not, maybe there's a way to signal in the UI that those keys are actually different.

**Comment by eczarny** [comment]
This behavior also exists in Apple's shortcuts tab under the keyboard preference pane in System Preferences. I'm inclined to close this issue and not alter the behavior.

**Comment by muesic** [comment]
So it looks like someone else has had virtually exactly the same idea! That numeric pad on the extended keyboard is a *very* intuitive way to move windows around. Would you please consider allowing the user to manually select from a choice of hotkey sets. The Spectacle defaults would be one set, and (in my case) I would have two others - one for when the external keyboard is attached and another for just the native MacBook Pro keyboard itself. I think that could solve the problem nicely :-).
