### ISSUE TITLE
Keyboard Shortcuts and custom keylayouts

### ISSUE THREAD

**Issue by gizmomogwai** [eczarny/spectacle#249]
after installing spectacle, i installed an alternative layout (neo).
i did not change the default keyboard shortcuts, but after logging in again with the new layout activated, the keyboard short e.g. for fullscreen (...-f) was still shown in the menu as -f, but the key i had to use was the original key of my keyboard for f (which in this layout now produces an e).

**Comment by eczarny** [comment]
Closing as a duplicate of #395.
