### ISSUE TITLE
Make "left half" and "right half" move window to next screen if window is already in that "half"

### ISSUE THREAD

**Issue by mfn** [eczarny/spectacle#251]
This is a suggestion to mimic the Windows behavior.

Example:
- setup: two monitors, active window on right monitor, custom position/width/height
- user presses key for "left half" and window resizes
- user presses key for "left half" again and window moves to the left screen on the **right half**
- user presses key for "left half" again and window moves to the left half (on the left screen already)
- user presses key for "left half" again, nothing happens

The same for "right half".

**Comment by kirstu** [comment]
+1

**Comment by WoLpH** [comment]
Indeed, would be useful :)
