### ISSUE TITLE
Disable Spectacle for a particular application through a new menu item

### ISSUE THREAD

**Issue by soulston** [eczarny/spectacle#254]
Is there any way that you can make applications ignore specific keyboard shortcuts or even be blacklisted?

Skype for example uses alt + CMD + left_arrow/right_arrow to move between conversations and it would be good to still be able to use this without having to remap this shortcut in Spectacle settings.

Many thanks

**Comment by eces** [comment]
+1

**Comment by jvnvr** [comment]
+1

**Comment by robrt** [comment]
+1

**Comment by andifant** [comment]
+1

**Comment by blimpage** [comment]
+1

**Comment by esco** [comment]
#160 mentioned a shortcut for the temporary disabling feature. Was this provided?

**Comment by Auo** [comment]
I guess most figure this out, but open the application where you want to disable Spectacle and press the Spectacle icon in your tray menu.

![Screenshot 2019-07-03 at 08 32 25](https://user-images.githubusercontent.com/1984096/60568502-4ec46280-9d6d-11e9-895f-c278a76955a9.png)
