### ISSUE TITLE
Mouse Screen Edge Snapping

### ISSUE THREAD

**Issue by alexkarasyov** [eczarny/spectacle#256]
Ability to snap windows by dragging them to screes edges with a mouse.
![image](https://cloud.githubusercontent.com/assets/1993707/4063285/64bedccc-2e06-11e4-998f-68bcec4d3ef7.jpg)

**Comment by jenslauterbach** [comment]
I would love to see this feature as well! 

:thumbsup:

**Comment by Alplob** [comment]
:thumbsup: :)

**Comment by saada** [comment]
:+1: please!!!

**Comment by saada** [comment]
I am willing to implement it if someone can give me pointer on the codebase? Where to start?

**Comment by foxx** [comment]
@eczarny I'd be willing to put up a bounty for this feature, and also provide beta testing assistance, if that would help speed things up? I've had a look at the source code, but I'm not sure how to achieve this feature without introducing UI lag, similar to the problems experienced by BetterSnapTool. Have you got any thoughts on this? Is there anything else I can do that would help get this issue closed?

**Comment by muellmaa** [comment]
was this implemented? or why is it a closed issue?

**Comment by eczarny** [comment]
It isn't a feature I plan to add to Spectacle so I closed out the issue. Trying to clean up the backlog.

**Comment by saada** [comment]
:sob:

**Comment by foxx** [comment]
@eczarny Any particular reason why you are rejecting this feature? Given that many users are asking for it, and that you've had bounty/PR offers, at the very least you should provide an explanation, rather than just closing with no follow up.

**Comment by eczarny** [comment]
Spectacle is intended to be simple and keyboard driven. I feel like a feature like this doesn't fit into this philosophy and it wouldn't be something I would want to implement or maintain.

**Comment by muellmaa** [comment]
First adding labels so anyone thinks you're going to implement it and then closing the topic WITHOUT ANY COMMENT is cheap... 
Uninstalled spectacle right now due to plain ignorance and behaviour of the developer.

Using BetterSnapTool now.

**Comment by Alplob** [comment]
Yes sure, such a pity, that would have been a killer feature..

**Comment by eczarny** [comment]
Sorry you feel that way but this is a project I work on in my spare time. The labels I use on issues are for my own organization, not at all a promise to build out anything.

I carefully consider every issue and greatly appreciate the time folks into creating them. I apologize I didn't put the time to explain why I closed this issue out.

**Comment by kokarn** [comment]
I really appreciate your time on this project Eric.
I also think you are 100% correct in not adding a bunch of fetures that
isn't really in the scope of Spectacle. It's a great tool and it should
stay that way.

**Comment by foxx** [comment]
Thank you for the clarification @eczarny.
