### ISSUE TITLE
Feature Request: Make window larger/smaller

### ISSUE THREAD

**Issue by fuzendesign** [eczarny/spectacle#260]
I’d like to see both the vertical and horizontal dimensions increased or decreased at the same time.

**Comment by williampower** [comment]
I like the idea of being able to resize in both dimensions. What do you think of having that functionality match the approach taken for moving a screen to left/right/top/bottom half? That approach would look something like this:  
⌃⌥⇧→    larger width
⌃⌥⇧←    smaller width

⌃⌥⇧↑      larger height
⌃⌥⇧↓      smaller height

What do you think, @eczarny ?

**Comment by eczarny** [comment]
Closing in favor of #590; this issue is a bit old and I'm not too sure what the original enhancement is for.
