### ISSUE TITLE
Hold down arrow key + ability to resize/move

### ISSUE THREAD

**Issue by philfreo** [eczarny/spectacle#269]
I used to use [Window Wrangler](http://mindflow.dk/software/windowwrangler/) (which doesn't seem to work with Yosemite) and am now looking for alternatives. Open source is a big plus.

Spectacle seems nice but there's a key feature missing... the ability to hold down a shortcut + arrow key to resize a window in any direction. You *almost* have this with "Make Larger" and "Make Smaller" but it requires pressing the arrow key over and over instead of being able to hold it down. Also you only have left/right but it should also do up/down to make a window taller or shorter vertically.

I got used to a workflow like:
- Hold control+option+arrow for moving a window
- Hold control+option+shift+arrow for resizing window

Thoughts on adding this?

**Comment by bcardiff** [comment]
+1
