### ISSUE TITLE
Spectacle not maximizing windows with hidden menu bar in OS X

### ISSUE THREAD

**Issue by altosaar** [eczarny/spectacle#277]
I have the menu bar hidden for Chrome (on Yosemite). I think I did this by editing the .plist in the package contents.

However, Spectacle doesn't realize this and so leaves a menu-bar sized space between the window and the top of the screen:

![image](https://cloud.githubusercontent.com/assets/5317244/4738050/3edb7694-59fa-11e4-81d6-c6253576a76a.png)

With menu bar:
![image](https://cloud.githubusercontent.com/assets/5317244/4738093/82436fea-59fa-11e4-8354-46b43ae39789.png)

I can still click and drag the top of the Chrome window to make it full screen (I moused over the menu bar to have it overlayed):
![image](https://cloud.githubusercontent.com/assets/5317244/4738099/8ee45fca-59fa-11e4-9626-ec3c05bbc7a9.png)

This seems to be a bug, or I might be missing something. Is this expected behavior? Thanks!

**Comment by altosaar** [comment]
In case anyone else runs into this, the workaround I've settled on is to use [Menu Eclipse 2](https://itunes.apple.com/gb/app/menu-eclipse-2/id420041409?mt=12) -- this does not cause Spectacle to partially-maximize windows :)

**Comment by arkrozycki** [comment]
I use MenuAndDockless to hide the menu. Spectacle was leaving space for the menu bar, I managed to update some source code so that it would take advantage of the full screen space.

SpectacleWindowPositionManager.m Line 74
Change
```
visibleFrameOfScreen = NSRectToCGRect([screenOfDisplay visibleFrame]);
```
to
```
visibleFrameOfScreen = NSRectToCGRect([screenOfDisplay frame]);
```

and Line 384
```
visibleFrameOfScreen = NSRectToCGRect(screenOfDisplay.visibleFrame);
```
to
```
visibleFrameOfScreen = NSRectToCGRect(screenOfDisplay.frame);
```

Recompiled and deployed from xcode and its working nicely.
