### ISSUE TITLE
not making windows full screen, but slightly small, shortcut errors

### ISSUE THREAD

**Issue by stevenmwade** [eczarny/spectacle#283]
The cmd+opt+enter fullscreen is not actually making windows "fullscreen" anymore but a bit under full screen. Also, many of the shortcuts in the status menu come up as, for example, cmd+shift+?

**Comment by eczarny** [comment]
This behavior is actually expected for "quantized" windows. Basically any window that can only be resized by set amounts (MacVim, Terminal, etc.). In apps like these windows cannot be made to exactly fit the screen.
