### ISSUE TITLE
AutomaticUpdateCheckEnabled not effective

### ISSUE THREAD

**Issue by mikep345678** [eczarny/spectacle#285]
We deploy Spectacle to our fleet of school Macs with OS X 10.9 via munki. Most devices were at Spectacle 0.8.6. We manage all updates via munki; we never want any software to prompts to update.

Our post-install-script includes the following:
`# disable Spectacle autoupdate
defaults write /Library/Preferences/com.divisiblebyzero.Spectacle AutomaticUpdateCheckEnabled -bool false`

However, this morning with the release of 0.8.8, end-users are being prompted to upgrade.

`defaults read /Library/Preferences/com.divisiblebyzero.Spectacle` on a non-upgraded machine (still running 0.8.6) yields, both before and after 0.8.8 is installed via munki:
`{`
`    AutomaticUpdateCheckEnabled = 0;`
`}`

Has the "disabling Automatic Update" mechanism changed?

Thanks,
Mike

**Comment by eczarny** [comment]
I know I'm rather late on this (sorry!) but while working through something else I think I found a way to fix this. @mikep345678 if this is still a problem for you try:

`defaults write /Library/Preferences/com.divisiblebyzero.Spectacle SUEnableAutomaticChecks -bool false`
