### ISSUE TITLE
Feature Request: Add un-minimize shortcut

### ISSUE THREAD

**Issue by ffledgling** [eczarny/spectacle#292]
OSX has `Cmd + M` to allow minimizing windows from the keyboard, but unfortunately there's no equivalent way to Un-Minimize a window.

The closest possible option is to go to mission control via `Ctrl + down-arrow` then fiddle around with arrows to select the window you want then hit enter to bring it back.
This is a fairly tedious process because it's multiple key strokes, and long enough to break concentration. It also forces one to move hands away from the home row as well.

I'd like to put in a request for a spectacle feature/shortcut that un-minimizes the last minimized window for an application. Ideally maintaining a stack of of minimized windows and un-minimizing them in that order.

P.S: If necessary I'd be willing to help out with code, but I have no idea where to start or what a feature like this would require.

**Comment by ffledgling** [comment]
Thanks for the tip @reneklacan I'll take a look.

**Comment by chriswait91** [comment]
FYI @ffledgling, if you minimize the only window for an application, you can un-minimize by:
1. Cmd-Tab to summon application switcher
2. Tab to application with single, minimized window
3. While releasing Cmd key to select application, *hold the Alt key*

**Comment by ffledgling** [comment]
@chriswait91 Thanks for the tip, although that's something I already do, and not the usecase I was targetting with this request :)

**Comment by ffledgling** [comment]
I'm going to assume, this being closed means that this isn't going to be added in at any point?

**Comment by eczarny** [comment]
Correct.
