### ISSUE TITLE
Left/Right half and partial height windows

### ISSUE THREAD

**Issue by hlidotbe** [eczarny/spectacle#293]
Hi,

Currently when a windows is already half-width but not full height (after a display resolution change for instance), the next half/prev half makes the window full height (expected) and 1/3 width (usually not expected, at least for me).

Would it be possible that this feature only applies to full or near full height windows? Or have a way to disable it entirely?

**Comment by eczarny** [comment]
I'm unable to reproduce this issue in 1.0.6.
