### ISSUE TITLE
Fullscreen apps are resizable

### ISSUE THREAD

**Issue by beschoenen** [eczarny/spectacle#296]
As the title says, fullscreen programs are resizable in yosemite

Running: 10.10.1
Spectacle: 0.8.8

**Comment by eczarny** [comment]
They definitely are, and this is definitely a defect.

**Comment by andyearnshaw** [comment]
Was this issue closed accidentally?  I still notice this issue and #333 in the latest release.

**Comment by eczarny** [comment]
I may have closed this accidentally. #333 appears to describe an enhancement.

**Comment by eczarny** [comment]
Actually. @andyearnshaw does #468 describe this issue?

**Comment by eczarny** [comment]
Closing in favor of #468.
