### ISSUE TITLE
Outlook 2011 won't go to 3/4 screen

### ISSUE THREAD

**Issue by hellhund** [eczarny/spectacle#297]
With most apps, when you hold down cmd & option and press the left arrow key, the window toggles among 1/4, 1/2 and 3/4 of the monitor (pretty sure those are the proportions).  However, in the last couple of months, Outlook 2011 will only toggle between 1/4 and 1/2. 

Spectacle 0.8.8
OS X 10.9.5

**Comment by eczarny** [comment]
Interesting! Could you see if you can reproduce and copy/paste any logging output from Spectacle in Console.app?

**Comment by hellhund** [comment]
Okay, here you go. I closed MS Outlook, opened it again, and resized it to
the different sizes. It still does not go to 3/4 of the screen.

Hope the below is helpful. Let me know if you need anything else.

John


4/12/15 6:29:15.200 AM Spectacle[314]: Sparkle: ===== Spectacle.app =====
4/13/15 6:29:12.443 AM Spectacle[314]: Sparkle: ===== Spectacle.app =====
4/13/15 7:39:36.845 AM Spectacle[314]: Discovered 2 screen(s).
4/13/15 7:39:36.845 AM Spectacle[314]: Current screen: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 7:39:36.845 AM Spectacle[314]:     Screen 0: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 7:39:36.845 AM Spectacle[314]:     Screen 1: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:39:36.846 AM Spectacle[314]: Selecting the screen of the PREVIOUS
display.
4/13/15 7:39:36.846 AM Spectacle[314]: Index of the current screen: 0
4/13/15 7:39:36.846 AM Spectacle[314]: Selected screen: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:39:40.953 AM Spectacle[314]: Discovered 2 screen(s).
4/13/15 7:39:40.953 AM Spectacle[314]: Current screen: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 7:39:40.953 AM Spectacle[314]:     Screen 0: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 7:39:40.953 AM Spectacle[314]:     Screen 1: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:39:40.953 AM Spectacle[314]: Selecting the screen of the PREVIOUS
display.
4/13/15 7:39:40.954 AM Spectacle[314]: Index of the current screen: 0
4/13/15 7:39:40.954 AM Spectacle[314]: Selected screen: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:42:56.862 AM Spectacle[314]: Discovered 2 screen(s).
4/13/15 7:42:56.862 AM Spectacle[314]: Current screen: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:42:56.863 AM Spectacle[314]:     Screen 0: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 7:42:56.863 AM Spectacle[314]:     Screen 1: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 7:42:56.863 AM Spectacle[314]: Selecting the screen of the NEXT
display.
4/13/15 7:42:56.863 AM Spectacle[314]: Index of the current screen: 1
4/13/15 7:42:56.863 AM Spectacle[314]: Selected screen: (0.000000,
0.000000) 1920.000000x1200.000000
4/13/15 8:53:54.506 AM Spectacle[314]: Discovered 2 screen(s).
4/13/15 8:53:54.506 AM Spectacle[314]: Current screen: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 8:53:54.506 AM Spectacle[314]:     Screen 0: (0.000000, 0.000000)
1920.000000x1200.000000
4/13/15 8:53:54.506 AM Spectacle[314]:     Screen 1: (-1440.000000,
300.000000) 1440.000000x900.000000
4/13/15 8:53:54.506 AM Spectacle[314]: Selecting the screen of the NEXT
display.
4/13/15 8:53:54.507 AM Spectacle[314]: Index of the current screen: 1
4/13/15 8:53:54.507 AM Spectacle[314]: Selected screen: (0.000000,
0.000000) 1920.000000x1200.000000

**Comment by eczarny** [comment]
@hellhund thanks for the additional information! It sounds like Outlook might be restricting the size of the window. In this situation Spectacle will not allow you to resize the window to 3/4 of the screen. If you have a larger secondary display you can confirm this behavior by trying to resize the window to 3/4 of the larger display. If 3/4 of the larger display is within the allowed size of the Outlook window it should work.

**Comment by hellhund** [comment]
This is all happening with the larger display, actually. Is there a
workaround that you can think of? thanks!

John

**Comment by eczarny** [comment]
Is it working with the larger display?

**Comment by hellhund** [comment]
No, not working with the larger display.

**Comment by eczarny** [comment]
Is it working with the larger display on 0.8.10?

**Comment by hellhund** [comment]
Hi, Eric --

Just installed 0.8.10, shut down Outlook and restarted it, and tried it
again. Outlook still won't move among 1/3, half, and 2/3. Other windows
work fine.

John

**Comment by icecreammatt** [comment]
I have what I think is the same issue with Outlook 2014. While I can understand why going to 1/3 would be too small for outlook. I think if it is unable to go from 1/2 to 1/3 it should jump to 2/3 as the next jump option.

**Comment by dimonnwc3** [comment]
Macbook pro Retina 13(Late 2013). Resolution - (look like 1280x800 - Retina)
I have a similar problem with Finder, safari, messages, notes, reminders, etc… 
1/2 work good
1/3 and 2/3 not working

Other externals displays working fine and resolutions  look like(1440x900, 1680x1050) have no issue

**Comment by icecreammatt** [comment]
Is this fixed now? I'm still having this issue in Version 0.8.10 (445)

**Comment by eczarny** [comment]
It isn't, and isn't likely to be fully fixed. I did forget to mention that I am tracking some of the issues I have seen with Outlook 2011 in #371.
