### ISSUE TITLE
Make Spectacle AppleScriptable

### ISSUE THREAD

**Issue by bbk1524** [eczarny/spectacle#301]
Spectacle has really worked well for me, and I appreciate your hard work. As a newbie to AppleScripting, I would love the ability to open some apps in default positions using spectacle. I tried to find the scripting dictionary for it, but I couldn't. It wasn't in /Applications, so I assume it doesn't exist. If I'm simply looking in the wrong place, then please accept my apologies for wasting your time.

**Comment by pozix604** [comment]
Seconded.

**Comment by srid** [comment]
:raised_hands: 

This would be awesome, as you can then script complex window management (eg: move to center monitor and maximize, and when done put it back on previous monitor in its original quadrant) in [JavaScript](https://github.com/dtinth/JXA-Cookbook/wiki) composing on top of Spectacle's primitives.

**Comment by eczarny** [comment]
I'm less interested in AppleScript. How would folks feel about making Spectacle scriptable with Python?

**Comment by eczarny** [comment]
Closing in favor of #427.

**Comment by srid** [comment]
> I'm less interested in AppleScript. How would folks feel about making Spectacle scriptable with Python?

:+1:
