### ISSUE TITLE
Next/Prev Screens not in order with 3 external monitors - Macbook pro

### ISSUE THREAD

**Issue by df-andrews** [eczarny/spectacle#306]
Thanks for the great app, Spectacle has been amazing helpful! 

On my late 2013 Macbook Pro, I have 3 external monitors. One to the left of my Macbook and 2 to the right. When using the Prev/Next monitor functions, it doesnt go in order.

A window on the far left, will go from its screen (monitor 1) and goes direct to monitor 3, than monitor 4 and lastly monitor 2.

**Comment by trevordunn** [comment]
This is a duplicate of https://github.com/eczarny/spectacle/issues/298

**Comment by eczarny** [comment]
Closing as a duplicate of #298.
