### ISSUE TITLE
Moving full screen (OS X style) window to other monitor failed.

### ISSUE THREAD

**Issue by wolf0403** [eczarny/spectacle#314]
Moving full screen Chrome to other desktop leaves a grey, full screen on original monitor with a shadow of the window at the corner next to destination monitor, but the window is not visible on any of the screens.

**Comment by eczarny** [comment]
Sounds like a defect. Spectacle should not allow this behavior.

**Comment by eczarny** [comment]
7313998182432dcd826cb23388de190dbda0bc8f should fix this issue.
