### ISSUE TITLE
Allow Unmodified hot keys

### ISSUE THREAD

**Issue by paulstatezny** [eczarny/spectacle#315]
Thanks for creating Spectacle! Love this app.

It would be great to allow hot keys without modifiers. I would like to reserve the F13+ keys on my extended keyboard for Spectacle so that I can just tap F13 to make a window fullscreen. But modifier keys are required. 

I understand the conflict here; perhaps a prompt would appear: "This hot key has no modifiers. Are you sure you want to do this?"

Thanks for considering!

**Comment by vladdancer** [comment]
+1. I would like to use karabiner to map my Eject key as F12 to resize windows.

**Comment by eczarny** [comment]
I could treat these keys as a special case. My only concern is that typically folks would need to use the "fn" key as a modifier. I don't know if it is possible to override the default behavior of using, say, the F1 key sans the fn "modifier" (which is to reduce brightness on my MacBook Pro).

**Comment by paulstatezny** [comment]
@eczarny, thanks for your reply! I can see your concern about still requiring the fn key. Fortunately, if users so desire there's a setting to "reverse" the fn key behavior, so it is F1 by default, and "reduce brightness" when modified with the fn key.

**Comment by paulstatezny** [comment]
Whoops! Accidentally hit "Close and comment". Here's a link to achive that change: http://heresthethingblog.com/2012/11/12/mac-tip-function-keys-pressing/

**Comment by eczarny** [comment]
Excellent point @paulstatezny! I would love to get a chance to look into this change over the next week.

**Comment by eczarny** [comment]
I have a fix on master if folks are willing to try it out. The only remaining issue is that the function keys are not being displayed in the Spectacle menu. Working on a separate fix.

**Comment by paulstatezny** [comment]
I never saw your reply -- works great! Thanks. :)
