### ISSUE TITLE
Spectacle not working in Yosemite

### ISSUE THREAD

**Issue by Crimmy** [eczarny/spectacle#317]
Hi,

I am a newbie to this, have downloaded and enabled and opened spectacle, and whenever I try and carry through the commands it will give me a negative beep noise to dissuade me. I have read through some of the issues on here and I still cannot get it to work; I have deleted and reinstalled it and still no luck.

Any help will be much appreciated!

**Comment by narlei** [comment]
Hello Crimmy,

I'm using the spectacle in Yosemite and works very fine. You allow this app in System Preferences > Security > Accessibility?

![captura de tela 2015-02-06 as 13 26 06](https://cloud.githubusercontent.com/assets/8092922/6081850/bf64b99e-ae03-11e4-9584-ee436e9c05d2.png)

**Comment by Crimmy** [comment]
Yep, I have it enabled there.

**Comment by Crimmy** [comment]
It has randomly started working now, I have done nothing to the actual app but have been having a cleanup of the rest of my mac, so perhaps I removed something that was interfering with it?

Anyway, thank you for your help!
