### ISSUE TITLE
spectacle icon freezes on mouse-over on top bar

### ISSUE THREAD

**Issue by atmalagon** [eczarny/spectacle#318]
Hi,

I have a Mac running 10.9.5, and when I first downloaded Spectacle (three weeks ago) I could access it just fine by clicking the glasses icon on the top right of the screen. Now whenever I go to click it, I get the spinning wheel and can't open the dropdown menu of keyboard shortcuts.

**Comment by eczarny** [comment]
Is this still an issue? If so can you locate any diagnostic reports for Spectacle in the Console.app?
