### ISSUE TITLE
Bottom/middle/top thirds support

### ISSUE THREAD

**Issue by WoLpH** [eczarny/spectacle#324]
This is probably not a feature most people need/use, but for me it would be quite helpful. I'm currently working on 2 rotated 27" monitors which gives me a vertical resolution of 2560, at which point tiling in thirds would be a very useful feature :)

**Comment by eczarny** [comment]
If you continue to use the "Next Third" shortcut Spectacle should also attempt to tile your window in vertical thirds. Unfortunately, if for some reason Spectacle cannot make your window fit into a third it might not be able to get to the vertical thirds. This is something I can look into.

**Comment by WoLpH** [comment]
You are right, that does appear to work. A direct shortcut could still be useful however :)
