### ISSUE TITLE
Fullscreen/maximize to both monitors (using dual monitor)

### ISSUE THREAD

**Issue by WoLpH** [eczarny/spectacle#325]
It would be great if pressing ctrl+cmd+f twice would make the window maximize on both(/all?) monitors

So instead of maximizing only on screen 1, it would stretch/maximize on both/all screens.

**Comment by eczarny** [comment]
I'm not sure I follow the request?

**Comment by WoLpH** [comment]
For example, if you're working on a large spreadsheet it can be useful to extend the window to both monitors. 

So instead of taking 1600x1200 it would take 3200x1200 pixels.

**Comment by eczarny** [comment]
Oh! I see. Thanks for clarifying.

**Comment by WoLpH** [comment]
Does this mean that the feature have been cancelled?

**Comment by eczarny** [comment]
Yeah. I have been trying to organize the backlog a bit. Some features just don't fit well into the core functionality the app provides. I do hope to make Spectacle more extensible in the future so folks can add features like this easily on their own.

**Comment by WoLpH** [comment]
Adding some api to script your own functions could help a lot for cases
like these. If I can help writing or testing, please let me know.

**Comment by eczarny** [comment]
I created #427 to track that enhancement.
