### ISSUE TITLE
Alphabets displayed incorrectly

### ISSUE THREAD

**Issue by okuramasafumi** [eczarny/spectacle#329]
Alphabets are displayed incorrectly, though it works perfectly. They are all displayed as `?`. I attached the screenshot below.

Environments:
Spectacle 0.8.8, OSX 10.10.2, Japanese as main language, installed with Homebrew cask

![2015-02-20 13 01 23](https://cloud.githubusercontent.com/assets/1012014/6284111/3ff7d83e-b930-11e4-98f1-c231156139b6.png)

**Comment by okuramasafumi** [comment]
Sorry, this is duplication of #84 
I dug into the source code and found that `layoutData` variable in `ZKHotKeyTranslator.m` is `NULL`, which causes `?` appears. `inputSource` variable is however, not `NULL`.
I guess that's because I use U.S. keyboard with Google Japanese IME. In the [official document of TISGetInputSourceProperty](https://developer.apple.com/library/mac/documentation/TextFonts/Reference/TextInputSourcesReference/#//apple_ref/c/func/TISGetInputSourceProperty), it says

> The function might return NULL if the specified property is missing or invalid for the specified input source.

So is this a spec of OS X? Or can we have some alternative way to display alphabets correctly?

**Comment by eczarny** [comment]
I'm going to close this in favor of #84, but I'm going to link to your comment @okuramasafumi. Thanks for digging into the issue!
