### ISSUE TITLE
Problem with left-right placement with Slack Application

### ISSUE THREAD

**Issue by Erowlin** [eczarny/spectacle#335]
Hi, 

there is a little problem with the Slack Application, it seems that it's not properly resized, there is the let part of the application that goes over the screen limit. 

Here is a screenshot, better to understand  : 

![screenshot 2015-02-26 17 55 05](https://cloud.githubusercontent.com/assets/1775878/6396833/28bc316e-bde1-11e4-988d-25e3671d21cf.png)

(Sorry for the greyed parts, confidentiality ;) ). 

As you can see on the screenshot, the left paft of the Slack application is "eaten"

**Comment by cheshirecatalyst** [comment]
I am seeing the exact same thing.

**Comment by eczarny** [comment]
Looks like Spectacle is having trouble resizing the window. If you try to manually resize the width of the window does Slack prevent you from making smaller than the width displayed in the screenshot?

**Comment by eczarny** [comment]
Ideally in this situation Spectacle should try its best to make the window fit 1/2 the width of the screen. In the event this is not possible Spectacle should make the window as wide as it can to fit into 1/2 and have the resized window touch either the left edge or right edge of the screen (assuming the window is being moved to the left or right half, respectively).

**Comment by TedDriggs** [comment]
I looked at the code, but I'm not familiar enough with Cocoa to interrogate a window for its minimum size. I assume there's a way other than "attempt the resize and see if it worked"

**Comment by eczarny** [comment]
If Slack is putting constraints on the minimum size of its window there is nothing Spectacle can do to make it any smaller. The README now includes more information around . I was able to make a fix for a similar issue (see #371) that ensures windows will always be resized within the visible frame of the screen. Closing this issue as a duplicate.

**Comment by Erowlin** [comment]
Sorry for the non-followup, too much GitHub notifications kills it. 
Thank you for your informations.

**Comment by rohanliston** [comment]
This also happens for me on Ubuntu - I've got a vertical screen at 1050x1680 and the text runs off the edge of the screen ![(screenshot)].(https://cloud.githubusercontent.com/assets/1980929/16323740/8e1d3e18-39f0-11e6-9246-dba15f834f6a.png)

**Comment by watsokel** [comment]
Any update on this? I'm experiencing the same issue

**Comment by Erowlin** [comment]
@watsokel this : https://github.com/eczarny/spectacle/issues/335#issuecomment-130511618
