### ISSUE TITLE
Weird behavior when repeating left/right half shortcut

### ISSUE THREAD

**Issue by byalextran** [eczarny/spectacle#336]
The easiest way to explain the behavior is to watch this animated gif. 

http://cl.ly/image/1x0l3b2t1l1s

In this example, I'm repeating the left half and right half keyboard shortcut. 

For the Outlook email, you'll see activating the shortcut the first time produces the correct behavior. But pressing it again then causes the window to be "eaten" as described in Issue #335. 

For the Wunderlist app, it has a different behavior. It cycles between half screen, third screen and two-thirds screen when you activate the shortcut three times in a row. 

Is this intended behavior? 

I would expect no matter how many times you press the shortcut, the window would always just fill half the screen instead of cycling between different window positions. All the other shortcuts I've tried behave in this way.

**Comment by metropt** [comment]
It also happens to me

**Comment by paulozoom** [comment]
+1

**Comment by nixta** [comment]
Cycling through 1/3, 1/2, 2/3 after first jumping to 1/2 is designed behavior.

What happens with Outlook isn't (afaik) correct behavior.

**Comment by reidcooper** [comment]
Happens to me with Messenger and Reeder. Slightly annoying

**Comment by eczarny** [comment]
The issue with Outlook is not correct behavior. I'm going to close this issue in favor of #335, which includes a bit more information about the "eaten window" issue. The 1/3, 1/2, 2/3 behavior is intentional.
