### ISSUE TITLE
How make the window maximized in OSX 10.10.2? 

### ISSUE THREAD

**Issue by shamun** [eczarny/spectacle#339]
I am using OSX 10.10.2, how can i do normal window maximise (not full screen kiosk mode but general maximise)?

**Comment by mattfoster** [comment]
Spectacle's default shortcut for this is: ⌥⌘F

**Comment by shamun** [comment]
This key works. 
- I have two screen connected horizontally and vertically sometimes.

Is it possible i can do ⌥⌘F and then tell please display on screen 1 or screen 2?

**Comment by shamun** [comment]
This is not working: ⌥⌘F

- when application i used SketchBox and Stickies, is it normal?

**Comment by eczarny** [comment]
If you have multiple displays you can use "Next Display" or "Previous Display" to move the focused window to another display. Once on the desired display use "Fullscreen" to make the window use the entire screen of the display.

Spectacle may not be able to resize all windows, especially if the developer of the application has put a restriction on their dimensions. This might be what @shamun is seeing with SketchBox and Stickies.
