### ISSUE TITLE
Remove hard-coded white shadow from menubar icon image

### ISSUE THREAD

**Issue by sindresorhus** [eczarny/spectacle#341]
Now that Spectacle uses a the icon image as a template it makes the hard-coded white shadow in the icon become gray and makes the icon fuzzy and ugly, even on retina.

See the difference:

![screen shot 2015-03-15 at 18 51 54](https://cloud.githubusercontent.com/assets/170270/6655868/6fe931c0-cb44-11e4-8e10-c0659b68d1c6.png)

-

*Also, the [alternative image](https://github.com/eczarny/spectacle/blob/master/Spectacle/Resources/Images/Spectacle%20Alternate%20Status%20Item%402x.png) should not be needed anymore.*

**Comment by eczarny** [comment]
I would love to fix this, unfortunately my skill set doesn't include graphical design. Contributions here are very welcome. Keeping the same style would be fantastic, just without the shadow. I tried but I couldn't make it look good (too jaggy).

**Comment by sindresorhus** [comment]
Would be nice if you referenced the ticket in the commit or the commit here when you closed it.

This was fixed in https://github.com/eczarny/spectacle/commit/de2f747bdc0112c6ee97631a660d1e4b75c2aaf5 for posterity.
