### ISSUE TITLE
split a long vertical (portrait) window to fit a landscape display

### ISSUE THREAD

**Issue by meduz** [eczarny/spectacle#343]
I spend quite some time writing and reading papers. For instance writing LaTeX in TexShop involves having a long text, usually in a 80 chars wide window:

````
+--------------+
|              |
|              |
|              |
|              |
|              |
|              |
|              |
|              |
|              |
|              |
|              |
+--------------+
````

but my display is more like this (16:10 ratio)

````
+--------------------------------------------------+
|                                                  |
|                                                  |
|                                                  |
|                                                  |
|                                                  |
|                                                  |
|                                                  |
+--------------------------------------------------+
````

could it be feasible to virtually break a text window to fit on the display? 
for instance, a window that contains a long column (like this github page rendered in a browser) could be split into 2 columns rendered side by side such that the whole could be seen at a glance without having to vertically scroll.

(I happen to achieve that in vim using ``:vsplit``, opening the same file twice, and synchronizing text scrolling, but this is a solution specific to vim)

cheers

**Comment by eczarny** [comment]
Not sure I follow the request?

**Comment by evoactivity** [comment]
Are you suggesting a number of virtual 80 char wide windows splitting the text across them? Doesn't sound like something a window manager should support.

I'd suggest finding some way to orientate your monitor to portrait for a better experience.

**Comment by meduz** [comment]
I updated my comment to make it more easier to understand, but I understand that this is something that the window manager certainly does not support - as it involves "cutting" a window into splits (certainly hard), then placing them side by side (easier).

**Comment by eczarny** [comment]
I second @evoactivity suggestion. I don't believe splitting up a window is something Apple's Accessibility API supports, and it is certainly outside the scope of Spectacle's set of features. I don't want to say this feature would be impossible to implement but it would be very difficult and take an extremely large amount of time.

**Comment by meduz** [comment]
OK,  I agree. And spectacle should stay simple as it is . Thanks a lot for this piece of software - I find it extremely useful.

**Comment by eczarny** [comment]
Glad you're enjoying Spectacle @meduz! Sorry I couldn't be more helpful. It would be a cool feature though.
