### ISSUE TITLE
4px gap between edge of the screen and frame where the Dock is located. 

### ISSUE THREAD

**Issue by mvaneijgen** [eczarny/spectacle#344]
Is there a way to remove this 4px gap 
![alt text](http://i.imgur.com/eIb07a4.jpg) 
It is only where the dock is located.

**Comment by ygbr** [comment]
+1

**Comment by eczarny** [comment]
Closing as a duplicate of #282.

**Comment by mvaneijgen** [comment]
@eczarny could you link to to duplicate?
