### ISSUE TITLE
[Feature Request] Resize window to a specific size

### ISSUE THREAD

**Issue by Borales** [eczarny/spectacle#347]
I think it could be useful.
Make a set of window sizes in preferences and resize active window to a selected window size from the Spectacle menu (for example, I want to set my window size while making a screen capture to keep it 720p resolution).

Thanks for the app!

**Comment by guillaumesalagnac** [comment]
+1 

I'd love to see this feature, which i'd use a lot to move my (numerous) Terminal.app windows around the screen without having them resized. As of now I'm using spectacle for most of my WM needs, but I still have to resort to the mouse for Terminal.app: ironic, isn't it ?

**Comment by jordanweaver** [comment]
+1

Allowing user-defined layouts would be great, even if the allowable definitions were restrained to a coarse grid. I might try to work on this later in the month. Also, great work on the app so far!

**Comment by rajington** [comment]
was this closed because of the "out of scope" reasons listed in #157 or the potential implementation by @jordanweaver? would you include layout features in the app as a pull request?

**Comment by eczarny** [comment]
Correct. A feature like this is definitely out of scope.
