### ISSUE TITLE
Where have "Top Display" and "Bottom Display" gone? 

### ISSUE THREAD

**Issue by tomasjay** [eczarny/spectacle#349]
# My problem

Hi Eric,

**I love Spectacle**. I am currently using version 0.6.9 with Yosemite, and it works like a charm. Only the menu bar icon doesn't adjust to the dark mode. So I thought I'd update to the current version 0.8.8.

But I cannot find the **"Top Display"** and **"Bottom Display"** actions anymore – the features I'm using most often, e.g. during presentations. 

Where have these features gone? Will they return?

All the best from Munich,
Thomas

# My workflow

As an inspiraton to other users, here's how I am using Spectacle to present:

Before presentations, I create as many desktops on my Mac as I need to have a good overview of the presentation material (e.g. websites, Keynote, Preview, tables etc.). On the presenter screen I only use one desktop. During the presentation, I flip through my desktops, "shoot" the window I need up to the presenter screen, and enlarge it to full size – everything with a few short cuts.

As said above: **I love Spectacle**.

**Comment by eczarny** [comment]
In a previous release of Spectacle I consolidated these actions with the "Next Display" and "Previous Display" actions. Using "Next Display" and "Previous Display" will cause the currently focused window to cycle between connected displays.

During your presentations I imagine only one other display is connected? If so you can probably use the "Next Display" and "Previous Display" actions to accomplish the same thing.

**Comment by eczarny** [comment]
Closing as these shortcuts have been removed in favor of the "Next Display" and "Previous Display" shortcuts.
