### ISSUE TITLE
French localizations.

### ISSUE THREAD

**Issue by Risengan** [eczarny/spectacle#351]
Hello,

I've fully made the French localizations, can you add it? :)

https://www.dropbox.com/s/b4qagnn7m61zrgb/fr.lproj.zip?dl=0

**Comment by eczarny** [comment]
This is great, thank you!

**Comment by Risengan** [comment]
I also translated the website ;-)

![capture d ecran 2015-04-14 a 19 53 55](https://cloud.githubusercontent.com/assets/11879201/7143617/e8352c2a-e2e0-11e4-8c5e-b91897057a7c.png)

**Comment by eczarny** [comment]
Closing this issue out since I added the app translations. Would you mind creating a new issue for the website? Not quite sure how to localize that yet.
