### ISSUE TITLE
Terminal resizing/full screen have gaps

### ISSUE THREAD

**Issue by ronaldsuwandi** [eczarny/spectacle#356]
Same problem with iTerm2 (Spectacle 0.8.9)

Full screen:
![screenshot 2015-04-17 11 12 09](https://cloud.githubusercontent.com/assets/4120788/7194465/ed5d6c26-e4f2-11e4-9fea-961d2a5e9d9d.png)

Half screen:
![screenshot 2015-04-17 11 15 02](https://cloud.githubusercontent.com/assets/4120788/7194486/36486242-e4f3-11e4-9b9e-24c109d231ba.png)

**Comment by elsonwu** [comment]
+1 the same issue just want to report

**Comment by eczarny** [comment]
I believe this should be fixed in 0.8.10.

**Comment by ronaldsuwandi** [comment]
Sweet! Thanks @eczarny it's fixed in 0.8.10

Btw a minor quirk: there is a tiny gap at the top when doing full size for terminal (iTerm2 and Terminal) is there a way to fix this? Google Chrome, iTunes, Sublime Text can occupy all space without any issue

![image](https://cloud.githubusercontent.com/assets/4120788/7243577/00d5d848-e812-11e4-8804-d5276b117e8c.png)
