### ISSUE TITLE
Not working properly on multiple screens.

### ISSUE THREAD

**Issue by craigpetchell** [eczarny/spectacle#357]
Scenario: 

Screen 1 (left): Landscape
Screen 2 (right): Portrait

Terminal on on screen 2, attempt to position top half of screen, it resizes correctly, then gets moved to the first screen.

Happened since the 0.8.9 upgrade.

Workaround: downgrade to 0.8.8

**Comment by dimhof** [comment]
I have the same problem. Both screens in portrait. When i try to make a window on the second screen fullsize, the window resizes and then it gets moved to the first screen

**Comment by kvonspiczak** [comment]
I have this problem aswell. When I want to bring a window to my 2nd monitor in the upper right corner it moves there, blinks short and appears on my primary monitor again.
Spectacle 0.8.9
OSX 10.10.2

**Comment by DonGiulio** [comment]
I have a similar problem, on iterm2 (http://iterm2.com/) on the second display the iterm window gets moved to a position that is partially invisible, (I think it starts somewhere in the center between the two screens). If I change to bottom half, then the window gets moved to the first display. 

I'm not sure if it does it with other apps as well.

**Comment by dhowden** [comment]
I have the same problem since the update to 0.8.9.

**Comment by s-erickson** [comment]
It seems like this is pretty well reported, but I am experiencing the same issue. 

I did notice, however, that this only occurs when trying to move or resize a single window application. I am able to move Firefox windows around fine on my two secondary monitors as long as I have other Firefox windows opened on another monitor. 

Scenario:
Spectacle 0.8.9
Mac OS X 10.9.5
Macbook Pro Laptop monitor (Primary)
Dell Landscape Display (Secondary 1)
Dell Portrait Display (Secondary 2)

If an application has multiple windows open, moving one of the windows to another monitor and resizing works as expected.

If using a single window application, though, moving the window to another monitor works well, but when attempting to fullsize or snap to a fractional proportion of the screen the window is resized and then moved immediately to the primary monitor.
If a

**Comment by eczarny** [comment]
I'm experiencing similar trouble.

**Comment by pablito56** [comment]
I'm experiencing the same or a pretty similar issue here.

Scenario:
- 13" MacBook Pro Retina Mid 2014
- OS X 10.10.3 (14D136)
- Spectacle 0.8.9 (433)
-- No issues until I updated Spectacle this morning
- Displays arrangement: MacBook screen + 2nd landscape display with extended desktop
-- Also happened with a 3rd landscape screen
- Only happens when moving applications in 2nd or 3rd screen, in MacBook display seems to be working fine

Experienced behaviour:
- While on 2nd or 3rd display, resizing applications to left or right half makes the app to be moved to the main laptop screen.
-- Different behaviour with different applications depending on displays setup, but always fails with Chrome, iTerm2 and MacVim
-- Not happening while on MacBook display.

**Comment by eczarny** [comment]
Can somebody try and reproduce the issue using the latest changes on master?

**Comment by pablito56** [comment]
@eczarny I'm running master (cc89376) right now with MacBook's display + an external screen. Spectacle seems to be working fine again and resizing weird behaviour seems to be fixed. Tomorrow I will try at the office with 2 external screens.

Thanks a lot for the fast response and congratulations for the great job, Spectacle is awesome!

**Comment by kvonspiczak** [comment]
@eczarny I'm running master (847b2f7a03f78a12fb473a7b8eb22373ae76d991) at my office desk (27" iMac + external screen). Spectacle is working fine again for me. 
Could not live without your app btw :+1:

**Comment by eczarny** [comment]
I'm going to release a new version today.

**Comment by eczarny** [comment]
0.8.10 has been released.

**Comment by craigpetchell** [comment]
Thanks for the quick response! Great work! :)

**Comment by maspwr** [comment]
:+1: Fix works great!

**Comment by DonGiulio** [comment]
The fix solved my issue, thanks :)

**Comment by kbariotis** [comment]
Running 0.8.10(445) on Yosemite, I have the exact same problem.
