### ISSUE TITLE
Fullscreen does not work well anymore when Dock is on the left

### ISSUE THREAD

**Issue by siebmanb** [eczarny/spectacle#358]
When I apply a fullscreen, the window size is correct, the gap needed for the Dock is well computed, but the window is glued to the left side of the screen, even though my Dock is on the left hand side.

**Comment by eczarny** [comment]
Can you provided a screenshot? That would help immensely.

**Comment by siebmanb** [comment]
Hi,

Here is the screenshot.

PS: your software is truly awesome!

**Comment by eczarny** [comment]
Sorry, I'm not seeing a screenshot. Could you try again?

**Comment by siebmanb** [comment]
![capture 2015-04-17 a 16 47 12](https://cloud.githubusercontent.com/assets/4938788/7204339/9bf12e84-e521-11e4-95d9-ab0c1567eb9e.png)

**Comment by eczarny** [comment]
Ah! Thank you.

**Comment by eczarny** [comment]
Could someone try and reproduce the issue with the latest changes on master? I may have a fix.

**Comment by siebmanb** [comment]
I could if you tell me how to get a working app form the master...

**Comment by clementduncan** [comment]
Updated to 0.8.9, this problem only occurs when aligning a window to the right of the screen (when dock is on the left).

**Comment by sgomezg** [comment]
@siebmanb I tried master version and works fine :)

**Comment by sgomezg** [comment]
Sorry, I mean: @eczarny  I tried master version and works fine :)

**Comment by eczarny** [comment]
Should be fixed in 0.8.10.

**Comment by siebmanb** [comment]
Yes it is, good job !
