### ISSUE TITLE
console windows are stubborn

### ISSUE THREAD

**Issue by davidbobeck** [eczarny/spectacle#359]
1/3 of view doesn't stick with console windows... always jumps back to 2/3 or 1/2, depending on the size of the monitor. It used to work. Other windowed apps behave as expected. 

![image](https://cloud.githubusercontent.com/assets/1579892/7202645/55c76f7a-e4e2-11e4-97c2-491dd4025c3a.png)

**Comment by eczarny** [comment]
Ah, I think I know what's going on here. Out of curiosity, do other actions work on console windows? Is it only thirds that causes trouble?

**Comment by davidbobeck** [comment]
Yes, only thirds. Other actions work.

**Comment by eczarny** [comment]
Perfect, okay. I think I have a fix in mind. I'll try and reproduce the issue myself and try a few things out!

**Comment by eczarny** [comment]
I pushed a change. @davidbobeck are you able to build and run Spectacle to verify?

**Comment by davidbobeck** [comment]
No, sorry... I'm just an application consumer... not an xcode developer

**Comment by eczarny** [comment]
Not a problem. I'll work on getting a release out with the potential fix after I can do some additional testing.

**Comment by joshtronic** [comment]
Just built and verified. iTerm2 and Terminal.app are both resizing correctly to 1/3 and 2/3 using the hotkeys

**Comment by eczarny** [comment]
Awesome, thanks @joshtronic! I'm closing this issue out so I can focus on a couple others that came in after the 0.8.9. release.

**Comment by joshtronic** [comment]
Good deal, feel free to @mention me on anything that you need tested!

**Comment by eczarny** [comment]
:+1:
