### ISSUE TITLE
screen flashing

### ISSUE THREAD

**Issue by calebmennen** [eczarny/spectacle#362]
When resizing a window doesn't work, screen flashes white, and spectacle sizes the window to an undesired configuration. ex, window is some size, and I want it to move it to the left half, mashing left half command results in the left 2/3 configuration, and only way to get it to left half, is to go to another configuration, and come back

**Comment by eczarny** [comment]
Is this still an issue in 0.8.10?

**Comment by calebmennen** [comment]
Appears to be fixed
