### ISSUE TITLE
Terminal window always moves back to primary screen.

### ISSUE THREAD

**Issue by dwayneyuen** [eczarny/spectacle#363]
It seems possibly related to: https://github.com/eczarny/spectacle/issues/357.

It only happens for me with terminal (tested with Chrome, Sublime, HipChat, Adium). If I try to move my terminal window to the secondary screen, it immediately gets switched back to my primary screen. If I manually drag my terminal window to my secondary screen and I do any kind of Spectacle action on it (left, right, top, bottom, full, etc.) it will jump back to my primary screen. I think this has only started happening with 0.8.9.

Terminal is the only program of the ones I've tested that has the frame that won't take up the full screen (this issue here: https://github.com/eczarny/spectacle/issues/356).

**Comment by johnywith1n** [comment]
experiencing this as well

**Comment by chipolux** [comment]
+1

**Comment by cyphercommunications** [comment]
+1

I experience the same issue on my third monitor, pressing ⌥⌘F moves the window to the center display

**Comment by eczarny** [comment]
Can somebody try reproducing the issue with the latest changes on master?

**Comment by rsanchezsaez** [comment]
This seem related to another issue I'm experiencing after updating. 

With the dock on the left side, when I try to make Terminal fullscreen via Spectacles, Terminal ends up being shifted to the left side of the screen under the dock, and there is an empty band of space (with the size of the dock) to the right of the Terminal window. It like it's calculating the window size properly, but the position is offset to the left.

**Comment by kratsg** [comment]
I have the same problem.

**Comment by choongng** [comment]
@eczarny With the latest master Terminal now moves correctly for me.

**Comment by darylknight** [comment]
This is happening with all windows for me - any window I try to move to the secondary monitor with Spectacle immediately flicks back to the main screen.

**Comment by noisychannel** [comment]
Same here. Had to switch the secondary monitor to being the primary for the time being. This issue appears only when trying to non-full screen mode (1/2 screen for example), on the secondary display.

**Comment by kokarn** [comment]
I can +1 this, seeing the same issue on 0.8.9

**Comment by eczarny** [comment]
I think this should be fixed in 0.8.10.

**Comment by bartuer** [comment]
Good job! When I want to fire a bug to track this annoy issue, update resolve it.

**Comment by srvaroa** [comment]
@eczarny I'm seeing this with 1.2, are you aware of a regression?

**Comment by smvv** [comment]
I'm seeing this bug as well on Version 1.2 (672).
