### ISSUE TITLE
Update Not Working Well

### ISSUE THREAD

**Issue by FrankDraws** [eczarny/spectacle#365]
I have a 15" MacBook Pro pushing a Thunderbolt and Cinema Display. 

For some reason it no longer works with the Terminal window. When I hit the shortcut to move it to the middle monitor (i.e. Cinema Display), it jumps back to the main monitor on the left (Thunderbolt).

**Comment by cyphercommunications** [comment]
+1

**Comment by eczarny** [comment]
Closing as a duplicate of #363.
