### ISSUE TITLE
Cycling between 1/2, 1.5/2, 1/3 is now in the wrong order?

### ISSUE THREAD

**Issue by medv** [eczarny/spectacle#366]
If I start off with a window stretched to full screen, then hit the "Left Half" shortcut, it will be 1/2. If I hit the shortcut again, It will go to 1.5/2 (larger), hit again and it goes 1/2, hit again it goes 1/3 (smallest). Before it was Half -> Smaller -> Larger -> Half. Which made more sense? If I keep hitting "Left", it should never result in a bigger window unless it cannot be any smaller and needs to begin its cycle again.

**Comment by eczarny** [comment]
Fixed in 847b2f7.

**Comment by medv** [comment]
Would never have expected to hear back. Amazing, thank you.

**Comment by medv** [comment]
This problem is back as of 1.0.1
