### ISSUE TITLE
Any operation on dual monitor is buggy

### ISSUE THREAD

**Issue by gouaille** [eczarny/spectacle#367]
Hi,

I've been experiencing issues since 10.9 with the windows on my external monitors.

When i try to resize them (fullscreen, 1/3, 1/2, ..) they leave a gap on top of the window. This gap makes the window shift to the bottom of the page and i'm missing like 1/10 of the window.

See the fullscreen

![capture d ecran 2015-04-20 09 07 50](https://cloud.githubusercontent.com/assets/210580/7225272/ec1ddcaa-e73c-11e4-8838-7eb96b6eef69.png)

**Comment by eczarny** [comment]
Does 0.8.10 fix this issue?

**Comment by rgo** [comment]
@eczarny It's working again with 0.8.10 :+1: 
Tested: fullscreen, 1/2 left-right-up-down, move to one monitor to another and back.

**Comment by eczarny** [comment]
Awesome!
