### ISSUE TITLE
French localization quirks

### ISSUE THREAD

**Issue by guillaumesalagnac** [eczarny/spectacle#368]
Hi,

Great app. Love it. Just to let you know that some of the french translations are a bit weird, and misleading. 

- "Affichage suivant" and "Affichage précédent" should be changed to "Écran suivant" and "Écran précédent" (both in the menu and in the preference window)
- "Troisième suivant" and "Troisième précent": should be changed to "Tiers suivant" and "Tiers précédent" (in both contexts too)

Thanks again, and keep up the great work !
-G

**Comment by eczarny** [comment]
Addressed in 89d78e336a7c0d88786872d51e1377f6224c8aad.
