### ISSUE TITLE
Issues with 0.8.9 (433)

### ISSUE THREAD

**Issue by DrRob** [eczarny/spectacle#369]
Hello,

Since the update to 0.8.9 (433) a few days ago:

If I press the button combination to move a window to the right-hand half of the screen, the window ends up shifted in from the right-hand edge by about 100 pixels.  (There's a brief flash - it appears to move to the right-hand edge correctly, then immediately jump to the left by 100 pixels.)  It works fine on the left-hand edge.

If I press the button combination a second time, which would normally make the window 1/3 the width of the screen, it beeps angrily, momentarily makes the window larger than 1/2 width, then reverts to 1/2 width.

I'm using Yosemite 10.10.2 on a retina MBP.

**Comment by joaopimentel** [comment]
This happens to me as well, at least on iTerm.app windows.
Doesn't happen on any other application that I've seen, for now.

**Comment by DrRob** [comment]
I hadn't realised it varies with application.  Here are a few:

Affected:
* Terminal
* MacVim
* Skype

Not affected:
* Google Chrome
* Microsoft Word (from Office 2016 beta)
* Preview

Move to right-half of screen works, but to 1/3 of screen does not:
* Microsoft Powerpoint (from Office 2016 beta)
* MacPass (works ok on password entry screen, but not once passwords are open)

It looks like some apps don't like being resized to 1/3 screen width.  I'm not sure what happened in the previous version of Spectacle?  Did it force the app to a smaller size than it likes, or try 1/3 and settle or the minimum the app would allow?  (The latter would be the best option.)

Thanks,
Rob.

ps. Is the install package for the previous version available somewhere, so I don't have to build it from source?

**Comment by masenf** [comment]
Here is the previous version: https://s3.amazonaws.com/spectacle/downloads/Spectacle+0.8.8.zip

It also appears that several other similar issues have been opened in the past few days, like #361 and #364

**Comment by wpwood** [comment]
Another similar issue with 0.8.9 and iTerm2. I have a multiple monitor setup, and if I maximize my iTerm2 window (Fullscreen, Option-Command-F) on a different monitor, iTerm2 jumps over to monitor 1 and goes fullscreen relative to that monitor. If I run 0.8.8 from that .zip file, it works fine.

**Comment by coffeemonk** [comment]
Similar issue with Mac OS X 10.10.3 and Terminal 2.5.3 (343.7), it moves to my second monitor just fine, but when I try to push it to the right half of the second screen, it expands, then jumps over to the first monitor. Was definitely not doing this with the previous version.

**Comment by rbgarga** [comment]
I have the problem with iTerm2 too. I also noted it only happen when Dock is configured to be on left side. If I move dock to bottom it works as expected. I back to 0.8.8 and everything is OK

**Comment by kevinsimper** [comment]
@rbgarga I also have it when dock is at the bottom. But I am on multiple monitors, don't know if that has something to say.

**Comment by DrRob** [comment]
Ah, my Dock is on the left-hand side too.

**Comment by jdecastro** [comment]
I'm getting the same behavior as @wpwood is seeing with version 0.8.9 and iTerm2.  Moving back to 0.8.8.

**Comment by eczarny** [comment]
I released 0.8.10. Does it address any of the issues folks are seeing here?

**Comment by DrRob** [comment]
Appears to fix all the problems I was having, thanks!

**Comment by wpwood** [comment]
Yep, it appears to fix the iTerm2 Fullscreen issue I reported. Thanks!

**Comment by jdecastro** [comment]
Yes @eczarny .  Thanks very much!

**Comment by rbgarga** [comment]
Everything fine here with 0.8.10. Thank you!

**Comment by kaos** [comment]
:+1:

**Comment by evam70** [comment]
I have just updated Spectacle app to version 1.0 and now Microsoft Word is not working with Spectacle anymore. I have a Macbook Air with Yosemite Version 10.10.5
Can you help me? Thanks

**Comment by DrRob** [comment]
For what it's worth, I'm using Spectacle 1.0 on a Macbook Pro with Yosemite version 10.10.5 and Microsoft Word version 15.13.1 (150807) and Spectacle seems to work with it ok.  (The first time I tried it after reading evam70's message, it beeped angrily instead of moving the window.  I manually moved the window a little, then tried again, and since then it works as expected.)

**Comment by evam70** [comment]
Hi, 
Sorry but I have tried everything (even what DrRob is proposing) and MW is not working. (I have MW 2011 for Mac Version 14.0.0)

**Comment by DrRob** [comment]
I also have Word for Mac 2011, version 14.5.4 (150722), and tried it with
that, and all works fine.  Sorry that doesn't help you evam70, but it at
least confirms that some version combinations can work on some Macs.

**Comment by evam70** [comment]
It is the same in my Macbook Pro. Spectacle is not working with Word either.

**Comment by eczarny** [comment]
Please add all Word-related comments to #447.
