### ISSUE TITLE
Terminal with tabs doesn't size correctly in upper left corner

### ISSUE THREAD

**Issue by cristeahub** [eczarny/spectacle#370]
When having a terminal with tabs on a quarter of the screen its height is not correct. Notice the expected result is a terminal that's `118x33` while the actual result is a terminal that's `118x32`.

Expected result:
![image](https://cloud.githubusercontent.com/assets/1488921/7239698/248e39e4-e7ac-11e4-88d3-01164cb42477.png)

Actual result:
![image](https://cloud.githubusercontent.com/assets/1488921/7239667/f7979b42-e7ab-11e4-9a1e-70f12c8fd30a.png)

Information:
Macbook Pro Retina 15" (late 2013).
Spectacle version 0.8.10 (also present on 0.8.9)
Terminal.app for mac (standard terminal app)

**Comment by eczarny** [comment]
Unfortunately this is expected. The tabs change the restrictions on the window's dimensions. To accommodate Spectacle shrinks the window to fit within the upper left corner.

**Comment by eczarny** [comment]
See #250 for details on the workaround.

**Comment by cristeahub** [comment]
Sorry for the late response, I have tested this with other similar tools like SizeUp and the size is bigger than using Spectacle. I'm not sure if this is due to using non-official techniques or not, but I feel it could be investigated some more.
