### ISSUE TITLE
Improper window placement with Activity Monitor, iTunes, & possibly others?

### ISSUE THREAD

**Issue by docbiz** [eczarny/spectacle#371]
For programs with windows that have a minimum width that exceeds half the width of the display, Spectacle, when sending these windows to the left-half of the display, appears to force the window outside of the bounds of the display. An example screenshot can be seen [here](https://i.imgur.com/E3nMzJ2.png).

(I'm running Spectacle 0.8.10 on OS X 10.10.3 on a mid-2014 Retina Macbook Pro.)

**Comment by ckcollab** [comment]
Thanks so much for being on top of this!

**Comment by TedDriggs** [comment]
Which version will this fix be in?

**Comment by eczarny** [comment]
The next release, most likely 0.8.11. I hope to have something ready next week.
