### ISSUE TITLE
window resizing doesn't work with excel

### ISSUE THREAD

**Issue by will-NYGC** [eczarny/spectacle#373]
after latest update, unable to resize MS Office apps

**Comment by eczarny** [comment]
Anything more specific? What version of Spectacle (0.8.10 or 0.8.9)? Which shortcuts don't work? What appears broken?

**Comment by erhutton** [comment]
I have the same issue.  I am using Spectacle 0.8.10 and MS office 14.4.8 (2011) on a MacBook Pro.   Windows in word, excel, Preview, Terminal, and others do not recognize or respond to any Spectacle commands.  Spectacle only seems to work with Chrome since I've updated.

**Comment by will-NYGC** [comment]
hi sorry,

more details
spectacle version 0.8.10
outlook version 14.4.9

none of the shortcuts work for me.


On Apr 21, 2015, at 10:32 AM, Eric Czarny <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything more specific? What version of Spectacle (0.8.10 or 0.8.9)? Which shortcuts don't work? What appears broken?

—
Reply to this email directly or view it on GitHub<https://github.com/eczarny/spectacle/issues/373#issuecomment-94815921>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by eczarny** [comment]
Next round of questions. What version of OS X are folks seeing this issue with? If you restart your computer is the problem still present?

**Comment by erhutton** [comment]
I uninstalled the original, updated version of spectacle and re-installed the new release, and this problem is no longer present.

**Comment by will-NYGC** [comment]
10.9.5

i unplugged from my thunderbolt and seems to be working ok now.

will


On Apr 25, 2015, at 3:28 PM, erhutton <notifications@github.com<mailto:notifications@github.com>> wrote:


I uninstalled the original, updated version of spectacle and re-installed the new release, and this problem is no longer present.

—
Reply to this email directly or view it on GitHub<https://github.com/eczarny/spectacle/issues/373#issuecomment-96267343>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by will-NYGC** [comment]
seems to be working now after restarting computer and disconnecting and reconnecting thunderbolt display. thx for help.


On Apr 25, 2015, at 12:47 PM, Eric Czarny <notifications@github.com<mailto:notifications@github.com>> wrote:


Next round of questions. What version of OS X are folks seeing this issue with? If you restart your computer is the problem still present?

—
Reply to this email directly or view it on GitHub<https://github.com/eczarny/spectacle/issues/373#issuecomment-96235227>.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.
