### ISSUE TITLE
Left/Right half shortcut broken with iTerm2 and external monitor

### ISSUE THREAD

**Issue by sberthol** [eczarny/spectacle#376]
After upgrading spectacle to latest version (Version 0.8.9 (433))
Left/Right half shortcut don't work anymore with iTerm2 on an external monitor (plugged to a macbook pro): windows are resized as expected but moved to a random place.

**Comment by kokarn** [comment]
0.8.10 is the latest version

**Comment by sberthol** [comment]
Oops. Did not notice it :$. 
Just installed the actual latest version and this indeed fixes my issue.
Thanks

**Comment by kokarn** [comment]
No worries dude! :)

**Comment by WoLpH** [comment]
I think it's actually a duplicate as well: https://github.com/eczarny/spectacle/issues/303
