### ISSUE TITLE
Window resizing/positioning doesn't work with Steam

### ISSUE THREAD

**Issue by rsanchezsaez** [eczarny/spectacle#378]
Window resizing and positioning doesn't work with Steam.

**Comment by eczarny** [comment]
Hey @rsanchezsaez, could you provide a few screenshots as examples of the issues you are seeing?

**Comment by gomako** [comment]
Hi, I have the same issue with the Steam client. It tries to move it but the window pops back. I have recorded a terrible quality video but you can see what is happening. I am trying to position the window to the left, then the right. The Steam window doesn't seem to abide by many system rules.

![output](https://cloud.githubusercontent.com/assets/1306421/7512532/8d80a4c2-f4a5-11e4-8519-f8fdf9194b61.gif)

**Comment by rsanchezsaez** [comment]
Part of the problem seems to be that Steam has a minimum enforced size, which seems to cause Spectacle to fail when it tries to resize it to fixed sizes, and also cancels repositioning. But this also makes it fall when you try to make it take the maximum screen size.

Note that Steam is a free download, in case anyone wants to see the issue live.

**Comment by eczarny** [comment]
Steam may be better supported in the next Spectacle release. If anybody is willing to try out the latest changes on master perhaps we can get confirmation.

**Comment by gomako** [comment]
@eczarny I have cloned master and built the latest version (Version 0.8.10 (465), is this correct?) and it seems that the behaviour is the same as before.

**Comment by eczarny** [comment]
I'm wondering if it would just be better to blacklist Steam. Does this only happen when you try to make the window smaller than the minimally allowed dimensions? If you use a larger display does the problem persist?

**Comment by gomako** [comment]
I would be totally happy if Steam was blacklisted. I don't think anyone that has used it expects it to behave in the same way as the rest of the os.

The problem still happens on a larger display i.e. I open the window and it's smaller than the natural screen size, then when I try to pin to left or right it freaks out.

There is often a popup that opens when you first launch steam that cannot be resized although it can be closed, like an offers thing. I wonder if this has anything to do with it?

**Comment by eczarny** [comment]
Agreed. I'll add it to the blacklist.
