### ISSUE TITLE
Certain Apple applications not resizing as expected in Yosemite.

### ISSUE THREAD

**Issue by prestia** [eczarny/spectacle#380]
Spectacle runs in Yosemite and seems to work well with many applications, but it appears to have problems with the 1/3 and 2/3 sizes in certain Apple applications. Specifically, the 1/3 and 2/3 window sizing doesn't seem to work in Safari 8, Preview 8, and Mail 8. Other applications (like TextEdit) are unaffected.

As previously recommended by @eczarny, I tested to see if the window dimensions are restricted by manually re-sizing and that works just fine.

**Comment by eczarny** [comment]
Kind of a dumb question but have you tried restarting your computer? Sometimes that helps.

**Comment by prestia** [comment]
Yes. I've had this issue since Yosemite was released, so I've restarted countless times. I've also tried uninstalling and reinstalling Spectacle. I can't think of anything truly unusual about my setup, so I'm not sure what would be causing this. Let me know if I can provide any other info to help.

**Comment by eczarny** [comment]
What version of Spectacle are you using?

**Comment by prestia** [comment]
0.8.10 (445)
