### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by sandinak** [eczarny/spectacle#384]
Have the tool recognize, and be able to use, the difference between 
 - left control and right control
 - left option and right option
 - left cmd and right cmd
 - left shift and right shift.
I have to say .. I am LOVING this tool .. makes me wish for another modifier key on my keyboard to be able to assign just for things like this ;)

**Comment by janniklorenz** [comment]
As I mentioned in #302, I would like to have a master shortcut, to get rid of some rarely used actions. It should then be possible to decide in the config menu, if the action should react only after the master shortcut, or a dedicated global shortcut.
