### ISSUE TITLE
Strange default fallback language decision

### ISSUE THREAD

**Issue by fgreinus** [eczarny/spectacle#385]
Hey there,

i just installed this app and got french language as default. My mac uses german OSX - so if no german translation is available, wouldn't it be best to use english instead of french?

Furthermore i wasn't able to find a option to set the preffered language by myself. Would be pretty neat to have this.

Anyway, thanks for your awesome app :).

**Comment by marteb** [comment]
Just ran into exactly the same problem. Mac OS X is set to german, Spectacle was to set french!?

**Comment by patrickbaber** [comment]
Same problem here. OS X is set to German, but Spectacle shows me French.

**Comment by eczarny** [comment]
Can anybody easily confirm that this is still a problem on `master`?

**Comment by eczarny** [comment]
I am unable to reproduce the issue with Spectacle 0.8.10 on OS X 10.10.4. What versions of Spectacle and OS X are folks seeing the issue with?

**Comment by scherii** [comment]
I can confirm that the problem still exists as of version 1.0 (503):
![version 1.0 (503)](http://i.imgur.com/Mz3cPHE.png).

**Comment by eczarny** [comment]
This problem is really frustrating. Can folks seeing this problem attach some screenshots of their language preferences? I would love to track this issue down and fix it.

**Comment by scherii** [comment]
Haha :smile: I should've checked the region & language settings.
After the last update some other languages snuck in.
German is still the first in the list, but I suppose due the lack of a German Spectacle localization the fallback was the French one:
![Region & Language](http://i.imgur.com/V9yQkKN.png)

I think that means Spectacle was acting normal.

**Comment by marteb** [comment]
Exactle the same for me. After i removed alle the weird entries of the preferred languages (there were a lot entries like chinese, thai, korean, …, and french at the second position) spectacle is in english again.

Seems to be an OS X Bug/Problem after the latest OS X Update.

**Comment by fgreinus** [comment]
Same for me @marteb.

So this seems to be "solved" then :+1:.

**Comment by eczarny** [comment]
Happy to hear there is a workaround! Hopefully this is something Apple has fixed in 10.11.
