### ISSUE TITLE
If window can't shrink to 1/3, it can't get to the 2/3 size

### ISSUE THREAD

**Issue by abroekhof** [eczarny/spectacle#388]
Cycling through the Left/Right Half sizes should size the window 1/2, 1/3, 2/3, but if the Applications doesn't allow the window to size to 1/3 of the screen, you also won't be able to get to the 2/3 size, which I'm going for. I'm experiencing this behavior in Navicat.

**Comment by secrettriangle** [comment]
:+1:

**Comment by eczarny** [comment]
#391 should address this in the next release.

**Comment by abroekhof** [comment]
Great, thanks!
