### ISSUE TITLE
Accept bitcoin donations

### ISSUE THREAD

**Issue by abrkn** [eczarny/spectacle#389]
I love Spectacle and would love to donate using [bitcoin](http://bitcoin.org). Here's a start:

[![Bountysource](https://www.bountysource.com/badge/team?team_id=28831&style=bounties_received)](https://www.bountysource.com/teams/spectacle/issues)

(I have no affiliation with bountysource)

**Comment by eczarny** [comment]
I appreciate you wanting to donate but I don't want to support accept bitcoin.

**Comment by jorijnsmit** [comment]
Why not? I wanted to donate as well but don't want to in fiat 😝
