### ISSUE TITLE
Window not aligning to top of display

### ISSUE THREAD

**Issue by kentonh** [eczarny/spectacle#390]
Changing window size, position, or display aligns the top of the window at about 50% down the on the display. Window height is appropriate for the display, but defeats the purpose of the app to use a mouse to drag a window to the top.

**Comment by eczarny** [comment]
A screenshot would be helpful.

**Comment by eczarny** [comment]
Also, what version of Spectacle are you using?

**Comment by kentonh** [comment]
Version 0.6.7 (4)

In this screenshot, I've given the command to Spectacle to align this window to the top, left quarter. https://www.dropbox.com/s/vazjiz9z5e9y3dy/Screenshot%202015-06-11%2016.39.48.png?dl=0

**Comment by kentonh** [comment]
Sorry, Never mind.

I thought I updated, but when you asked me to check, I realized that the old version was still installed and being opened on startup.
