### ISSUE TITLE
Spectacle shortcuts using dvorak layout still in qwerty mode

### ISSUE THREAD

**Issue by featheredtoast** [eczarny/spectacle#395]
When running spectacle 0.8.8 using a dvorak keyboard layout, I noticed that the shortcuts are still in qwerty mode.

EG: alt-command-f for fullscreen becomes alt-command-u (qwerty f)

Searching issues it seems that #76 was the opposite issue. I am using full dvorak layouts so this functionality of command switching to a qwerty layout was not expected.

**Comment by eczarny** [comment]
What happens if you simply change the shortcuts to better match what you want?

**Comment by featheredtoast** [comment]
It works as expected if you remap it.
Feel free to close this out if it's working as expected for you guys, I was just not expecting the keys to auto-remap to the physical qwerty keys upon switching keyboard layouts, and wanted to raise the issue up here.
It makes the most sense to me for the mnemonic of "f" to remain 'fullscreen' by default, regardless of layout.

**Comment by eczarny** [comment]
I agree that the behavior is confusing. I'll leave this issue open but it isn't likely I'll get the chance to work on it. Maybe somebody else running into this problem would be willing to sort it out and send me a pull request.

**Comment by eczarny** [comment]
I'm now using this issue to track all problems with alternate keyboard layouts.

**Comment by eczarny** [comment]
This looks like it may be fixed on `master` (though there are lingering issues when changing input sources with Spectacle running). Closing this out.

**Comment by eczarny** [comment]
Reopening since this fix hasn't been released yet.

**Comment by cnrmck** [comment]
Has this fix been released? It seems like Dvorak Querty still has the issue

**Comment by scnewma** [comment]
I'm having this issue as well with Dvorak keys being mapped with the Qwerty buttons.

Changing the keyboard shortcuts don't work well for me because I constantly switch between Qwerty and Dvorak layout depending on when I'm using an external keyboard (which maps Dvorak on the physical keyboard).
