### ISSUE TITLE
Feature request: Center and resize a window

### ISSUE THREAD

**Issue by sway** [eczarny/spectacle#400]
It would be great to have a shortcut for centering and resizing a window to fill a certain area, e.g. resize to cover 70% of the screen and center, so that it ends up having a 15% margin all around. I often switch between using different panes and working with one window, and this would be a great time saver.

**Comment by eczarny** [comment]
Have you tried centering the window and using shortcuts to increase or decrease the window size?

**Comment by TheLocehiliosan** [comment]
I second this request. Centering and then decreasing is cumbersome. The "center" shortcut of the "SizeUp" app works precisely as this suggested feature—allowing you to "resize on center". This is the one thing that is keeping me from switching to Spectacle. I very much like the additional ability of Spectacle with 1/3 and 2/3 screens; but I can't do without the resize on center.

I _might_ consider implementing this feature. Does the "investigating" tag mean someone is already working on this?

**Comment by eczarny** [comment]
I use the "investigating" tag to track issues where I am waiting to follow up with the creator of the ticket.

In this particular case I was waiting on @sway to tell me if my suggestion to use existing shortcuts would work. I don't have any plans to implement a feature that explicitly centers and resizes a window.
