### ISSUE TITLE
Apple's Mail.app and OmniFocus not resizing as expected on 15" retina display

### ISSUE THREAD

**Issue by Aqueum** [eczarny/spectacle#401]
Love Spectacle.

I have just upgraded to Spectacle 0.8.10 (from 0.6.x) on OSX 10.10.3.  Both Mail and OmniFocus work perfectly on a 27" Thunderbolt, but I consistently have issues (even after reboot) as follows:

Mail.app when asked to fill a quarter screen, first fills the quarter screen then reduces its width by around 1cm on each side, in doing so it also turns off the mailbox view.  It used to fill the quarter, sometimes taking centre more space if required, but with perfect edge alignment.

Omnifocus when asked to fill a quarter or half screen is instead spilling over the edge - hence not all the window is showing.  It used to perfectly edge align, but take more centre space if required.

**Comment by eczarny** [comment]
I believe these apps put size restrictions on their windows, which can explain the behavior. They work on the larger display because the locations you are moving these windows to are bigger than they are on the smaller display.

On the other hand Spectacle should not be forcing the OmniFocus window over the edge of the display. That seems like a defect.

**Comment by Aqueum** [comment]
Thanks Eric

I believe how it used to work in earlier versions was that if an app had a minimum size, that exceeded a quarter, the app window would be shown at it's minimum size, with the outermost corner touching the requested corner of the screen.

That's not what I see on the retina display.  Skype is fine in the top quarters, but in the bottom quarter the bottom of the window is below the bottom of the screen.  Omnifocus has one side always over the edge of the screen.

Mail.app seems even worse - it takes up less than a quarter of the screen, by correctly positioning, but then reducing its width.  This seems to be because there are two minimum width options, one including the search box, and one excluding it.  It would appear that Spectacle positions for the option including the search box, but the window then goes down to the smaller size.

Unfortunately these are the three apps that I keep on my retina display and none of them work as well as they used to under 0.6.x, excel and other apps seem fine.

**Comment by eczarny** [comment]
@Aqueum that's correct. Fortunately I think I have a fix in place on master. Should have a release ready sometime next week.
