### ISSUE TITLE
Windows resize to fraction of expected size on 1920x1080 monitor

### ISSUE THREAD

**Issue by michaeljscott** [eczarny/spectacle#402]
My 11-inch MacBook Air is connected to an external monitor (Samsung S27D590 with resolution of 1920x1080. The laptop display is the primary display, the Samsung is the secondary display. Spectacle works fine on the MacBook Air display but does not resize windows properly on the larger display.

-the "top" of the windows that are resized is approx. 2/3rds of the way up the screen, not at the very top as would be expected.

-when resizing windows in Spectacle to show only on the bottom of the Samsung, the windows actually show up on the top of the laptop display instead.

-when resizing windows to left or right half, the top of the windows are approx. 2/3rds of the way up the screen (like above) and the bottom of the windows appear to extend down below the display on the monitor.

**Comment by eczarny** [comment]
What version of Spectacle?
