### ISSUE TITLE
Ability to use extra space when the menu bar is hidden in OS X 10.11 El Capitan 

### ISSUE THREAD

**Issue by danmanstx** [eczarny/spectacle#404]
A new feature in El Capitan allows the menu bar to be automatically hidden. 
![screen shot 2015-06-10 at 11 05 52 am](https://cloud.githubusercontent.com/assets/663340/8085905/afd7228c-0f60-11e5-8f82-52580b5a4369.png)

When resizing windows with this feature on, I believe you would expect the windows to take the up the extra space now provided. Currently they do not. 
![screen shot 2015-06-10 at 11 04 41 am](https://cloud.githubusercontent.com/assets/663340/8085923/cb8a515c-0f60-11e5-970b-e49eb1c7e399.png)

**Comment by gursualtunkaya** [comment]
I experienced the same problem. I would appreciate a patch. Otherwise, still loving you, guys. :)

**Comment by gursualtunkaya** [comment]
I experienced the same shortcoming. I would appreciate a patch.

**Comment by gursualtunkaya** [comment]
Here's a workaround: I connected my Mac to an AirPlay display, played around with the display settings, then disconnected the display. Now the maximize mode in Spectacles leaves no gap where the menu used to be in El Capitan's Auto Hide Menu mode. Problem solved.

**Comment by miketucker** [comment]
An easier workaround: 
* enable auto-hide in System Preferences -> Appearances
* Log out or Restart
* Done!

**Comment by gursualtunkaya** [comment]
No need to log out or restart, just quit Spectacles and then relaunch, and your problem will be solved. I was wrong before when I wrote that connecting to an AirPlay display fixes the problem. It does not. Only quitting and relaunching Spectacles does.

**Comment by danmanstx** [comment]
also can note, that if you relaunch like @gursualtunkaya recommends while your menu bar is in auto-hide mode it will correctly resize in both shown and hidden if you switch between the modes after this. Looks like spectacle could always use the hidden sizing and correct itself for when the menu bar is shown.
