### ISSUE TITLE
Feature Request: Save window state

### ISSUE THREAD

**Issue by filipebarcos** [eczarny/spectacle#405]
Hey, can we please add the ability to save window state? For example, I'd like to save Safari on 1/2 of screen on my first monitor.
When I unplug the monitor, and plug it back again, I'd like safari to go back to previously-saved location, 1/2 of by first monitor.

Thank you :smile_cat:

**Comment by eczarny** [comment]
https://cordlessdog.com/stay/ is the app for you.

**Comment by filipebarcos** [comment]
thank you so much, I was not aware about that app. Really helped. :+1:

**Comment by eczarny** [comment]
Happy to hear!
