### ISSUE TITLE
Program window rearrangement rules, based on screen setup changes

### ISSUE THREAD

**Issue by magnusart** [eczarny/spectacle#406]
I would like to have all program windows that occupy half a screen on my external monitors (with higher resolution) to move into their own full screen desktops when I unplug external monitors. I end up having to rearrange my desktops since all the windows get stacked when I unplug to go to a meeting or move to a different location.

Reversely I'd like to have the windows merge back into a single desktop with half the screen when I plug the monitor(s) back in.

I want a feature that either remembering the window positions across different screen setups or the possibility to have certain rules (like what I described above) apply when screens change would help.

**Comment by kokarn** [comment]
There are already other apps for that, as mentioned in #405

Here are some you can try
https://github.com/jigish/slate
https://cordlessdog.com/stay/
