### ISSUE TITLE
sometimes doesn't work with Sunrise app

### ISSUE THREAD

**Issue by toomasr** [eczarny/spectacle#409]
I'm using Sunrise ( https://calendar.sunrise.am/ ) 1.02 on Mac 10.10.3 and sometimes Spectacle works with Sunrise app and sometimes it doesn't.

When it doesn't it just makes a sound. I've tried to make sure the app has focus and what not. So far restarting Sunrise has helped.

**Comment by bettin** [comment]
I can't replicate the sounds.  Maybe your using a key like Left or Right arrows and getting the default sound, not Spectacle combo?

The app doesn't actually resize small enough to fit 1/2 screen, so that might be related.
Sunrise 1.02 and Spectacle 0.8.10 on OS X 10.10.3

**Comment by toomasr** [comment]
I don't have steps to reproduce the issue but to double check I wasn't using keyboard shortcuts I tried the shortcuts from the Spectacle menu even. I know that it doesn't resize to certain sizes so I made sure to try to go to full screen and switch to the sides on my big screen (which does work most of the time).

As I was typing this I had the same problem again. The window was centred and not in full screen and it wouldn't go to fullscreen. After some cmd-tab'ing around it started working again. I'll keep an eye on this and try to figure out how to reproduce.

**Comment by eczarny** [comment]
I sometimes see Spectacle run into trouble when trying to interact with windows. The next time you run into the issue could you copy/paste any relevant output from the Console? Spectacle will often log an error message there in this situation.

**Comment by toomasr** [comment]
Ok, sure thing!
