### ISSUE TITLE
Check Auto-Hide menu bar setting when resizing windows on OSX 10.11+ (El Capitan)

### ISSUE THREAD

**Issue by lgomez** [eczarny/spectacle#414]
Hi,

Just a heads up, OSX El Capitan (I'm on v10.11) added a System Setting that allows the menu bar to be automatically hidden (like the Dock). Spectacle resizes to a height that asumes the menu is visible even when it's not so windows don't use all the available space.

Thanks for the great work.

**Comment by lgomez** [comment]
I was hoping I could contribute a change but I don't know enough about OSX dev. I _suspect_ the `SpectacleWindowSizeOffset` constant ([here](https://github.com/eczarny/spectacle/blob/e49a3be0ddc5125669f3405e733d163e577b009d/Spectacle/SpectacleConstants.m#L63)) should be changed to a variable set to `30.0f` or `0` based on  the menu autohide setting.

**Comment by saada** [comment]
:+1:

**Comment by eczarny** [comment]
`SpectacleWindowSizeOffset` is used to determine how much larger or smaller to make a window when using the "Make Larger" and "Make Smaller" shortcuts. If my memory serves me correctly this is usually something handled by Apple's frameworks when requesting the visible frame of the current screen. I don't believe I do anything special.

Thanks for creating the issue! I don't usually get a chance to use Spectacle on pre-release versions of OS X.

**Comment by lgomez** [comment]
No problem. I'm not entirely sure what changed but I noticed about two weeks ago that the behavior changed to what it should be. Perhaps the OS was reporting the current screen's visible frame incorrectly.

Thank you!
