### ISSUE TITLE
Provide older versions of spectacle (cannot upgrade work laptop to Mavericks)

### ISSUE THREAD

**Issue by Khorkhe** [eczarny/spectacle#416]
Hello,

My work laptop is currently on Mountain Lion, and we are not able to upgrade to Mavericks.  My other laptop has the older Spectacle, but this computer cannot support the latest Spectacle from the website.

Would you be able to provide older versions for compatibility issues?  Macs are not usable without Spectacle...

Thanks!

**Comment by eczarny** [comment]
The [README](https://github.com/eczarny/spectacle#system-requirements) provides a link to older versions of Spectacle.
