### ISSUE TITLE
Window snaps back to screen edge on manual resize

### ISSUE THREAD

**Issue by alextegelid** [eczarny/spectacle#417]
*Steps to reproduce:*
1. Position a window to top left, for example
2. Move the window off the edge
3. Resize the window by dragging the window corner on the opposite side the edge to which Spectacle snapped the window.

See video for better explanation: http://cl.ly/3g2R1j3m0y21

This also has another side effect on Google Chrome, where the address bar and sometimes the statusbar shows up where the main window would be if it were at the edge of the screen: http://cl.ly/2V1q0J3X0i3o

**Comment by alextegelid** [comment]
Also, when this occurs, the command "make smaller/larger" will snap the window back to the edges (top-left in the example above) and make it smaller from there

**Comment by eczarny** [comment]
Is this only happening with Chrome? What version of OS X?

Also, thanks for the videos! Very helpful.

**Comment by alextegelid** [comment]
I'm on OSX 10.10.4, and so far Chrome is the only app I've noticed this in

**Comment by eczarny** [comment]
Looking at the videos you provided it really looks like this is an issue specific to Chrome. I can't reproduce in version 44.0.2403.125. Given that this happens when you resize the window with the mouse I can't see how Spectacle could cause the behavior you are seeing.

**Comment by alextegelid** [comment]
Sorry, I've completely  forgotten to dig further into this. I haven't noticed it  much more either. I'll keep my eyes open for  anything else that could help you to reproduce the problem.



—
Alexander Tegelid
070-508 49 90
alex@tegelid.se
—

**Comment by alextegelid** [comment]
I can confirm that this happens to other apps as well. So far I've tested with Sublime Text, Slack, Google Chrome and (OSX built-in) Messages. They all behave the same. I can't confirm that Spectacle is causing this though, but I thought it was worth mentioning.

Logging out and in again resets the problem
