### ISSUE TITLE
Make larger/smaller on El Captain

### ISSUE THREAD

**Issue by vyscond** [eczarny/spectacle#419]
Make larger/smaller on El Captain 10.11 Beta is not working only in the main screen. Other windows can work fine on this macro if i put them on a extended screen.

**Comment by eczarny** [comment]
Is this still an issue? Or has it been resolved in subsequent betas?

**Comment by vyscond** [comment]
Can't tell. I've reinstalled yosemite. Sorry.

**Comment by eczarny** [comment]
I'm closing in the meantime. I've had a few reports of strange behavior on these beta releases that have been resolved in subsequent releases. We can always reopen if this remains an issue after 10.11 is formally released.
