### ISSUE TITLE
Impossible to active Spectacle

### ISSUE THREAD

**Issue by remibenault** [eczarny/spectacle#420]
Hello everybody,

Spectacle stopped to work on my mac (maverick) and I deleted it and downloaded the last version but when I open it, I get the message to allow it into Security & Privacy, the problem is that spectacle isn't in the list.
![spectacle](https://cloud.githubusercontent.com/assets/4526552/9063426/9a41a450-3ac7-11e5-8618-509f57299fe5.jpg)

Any help will be appreciated :+1:

**Comment by eczarny** [comment]
Have you tried restarting your computer?

**Comment by remibenault** [comment]
Yes I did several times, I even tried old version from my backup but nothing works. Spectacle still doesn't appear in the list. I don't understand because it worked for years and suddenly stopped.

**Comment by eczarny** [comment]
Are you using Spectacle 0.8.10? Are there any errors in the Console?

**Comment by remibenault** [comment]
Yes, I'm using 0.8.10(445). 

Well, I never used the console but here is what I get when I search about Spectacle.


12/08/2015 17:44:06,015 universalAccessAuthWarn[2468]: AccessibilityAPI: pid 24576, is not allowed to access the accessibility API. Path: (unknown) (Leaf request from pid 20822 Path: /Applications/Spectacle.app/Contents/MacOS/Spectacle)
12/08/2015 17:45:27,895 Spectacle[20822]: Unable to obtain the accessibility element with the specified attribute: AXFocusedApplication (error code -25204)
12/08/2015 17:45:27,895 Spectacle[20822]: Unable to obtain the accessibility element with the specified attribute: AXFocusedApplication (error code -25204)
12/08/2015 17:45:27,896 Spectacle[20822]: Failed to find the application that currently has focus.
12/08/2015 17:45:27,896 universalAccessAuthWarn[2468]: AccessibilityAPI: pid -1, is not allowed to access the accessibility API. Path: (unknown) (Leaf request from pid 20822 Path: /Applications/Spectacle.app/Contents/MacOS/Spectacle)
12/08/2015 17:45:27,896 Spectacle[20822]: Unable to obtain the accessibility element with the specified attribute: AXFocusedApplication (error code -25204)


Maybe that can help you.

**Comment by eczarny** [comment]
I would recommend upgrading to Yosemite. From what I can see this may be a Mavericks issue.

I did find this though:

http://www.itechlounge.net/2013/12/mac-issue-with-divvy-and-universal-access-on-osx-mavericks/

I haven't tried the fix described there so please take the time to understand what that command is doing. No guarantees it will help.
