### ISSUE TITLE
All commands cause window to lose focus?

### ISSUE THREAD

**Issue by kevincastillo** [eczarny/spectacle#421]
Is this an intentional feature?

If I'm in an active window and use any spectacle command, the resizing is performed, but the window/application loses focus, which becomes a particular problem when dealing with multiple windows/apps, and prevents consecutive moves (say, moving a window to left half, then right).

I'm running the application in the status menu, with no changes to any of the default shortcuts.

**Comment by eczarny** [comment]
That isn't intentional. The window with focus should remain in focus when you use Spectacle to move and resize the window. What window gains focus when this happens?

**Comment by kevincastillo** [comment]
Apologies....false alarm. After trying some more through testing to nail down what window gains focus so I could reply accurately, found that a Keyboard Maestro macro I thought I had deleted long ago was reactivated, and seems to be the source of the conflict. Missed it when double-checking my shortcuts for conflicts in keyboard system preferences. Sorry about that, and thanks for the quick reply!
