### ISSUE TITLE
The same shortcut is permitted for different actions (with default configuration)

### ISSUE THREAD

**Issue by herau** [eczarny/spectacle#423]
I can define for an action the same keyboard shortcut than an existing one. 
For example, i can change the shortcut for the action "left half" with the same shortcut than "Next display"

**Comment by ezig** [comment]
I tried looking into this and found that it wasn't a problem with all of the hot keys and only happened when the hotkeys were on a default setting. For example, as @herau pointed out, you can set "left half" to be the same as "Next display" BUT if you manually set next display to ⌃⌥⌘-> (which should be the same as the default), you can't set "left half" to be the same as "next display". I stepped through in the debugger in Xcode and found that the modifier codes for the default hotkey settings were not always the same as the modifier codes resulting from manually entering the same hotkey in the preferences window.   

My suspicion is that there's something about the way the defaults are loaded from the plist, or maybe something about the data saved in the plist for the defaults. I would be happy to try a fix, but I don't know exactly how the default keys were originally archived into the plist.
