### ISSUE TITLE
1/3 & middle of the screen

### ISSUE THREAD

**Issue by christianv** [eczarny/spectacle#425]
What is the easiest way to resize a window to be in the 1/3 the width of the screen  middle of the screen?

**Comment by eczarny** [comment]
Move a window to the left or right half until it's at 1/3 then center the window. If a window had already been moved to a half using the same shortcut once more should cycle the window between 1/3, 2/3, and back to 1/2 again.

**Comment by christianv** [comment]
@eczarny thanks!
