### ISSUE TITLE
Not working properly on multiple screens

### ISSUE THREAD

**Issue by kbariotis** [eczarny/spectacle#430]
I noticed that an [issue](https://github.com/eczarny/spectacle/issues/357) has already been reported and fixed, but I am encountering the same problem running Yosemite and Spectacle 0.8.10(445).

Thanks

**Comment by eczarny** [comment]
Are you able to confirm that this remains an issue on master?

**Comment by kbariotis** [comment]
yes @eczarny you are right. master indeed works fine. When will it be out? :)

thank you

**Comment by eczarny** [comment]
Hoping to have a release ready next week!

**Comment by kbariotis** [comment]
@eczarny even though I had tested this that time and I got the update after a while ( I am currently at 1.0.1(59)) this still is an issue. Both in Yosemite and El Capitan. Any idea?
