### ISSUE TITLE
Moving groups of windows

### ISSUE THREAD

**Issue by theposey** [eczarny/spectacle#432]
First would just like to say love the app and great work. Not sure if this is possible but it would be super cool to be able to move all windows of a particular app to one side of the screen, other screen etc. Apps like Preview and Xcode have multiple windows that can be open and it would be great to be able to move them all at once. Might already be possible and I just don't see it in the app. Thanks!

**Comment by theInternauts** [comment]
+1 for this.  I'd use it for resizing/moving multiple browser windows, as well

**Comment by scottkall** [comment]
another +1 for this. I'd love to take all open Finder windows and tile them across the screen, for instance.
