### ISSUE TITLE
Feature Request: Pin a window to view across all desktop spaces, similar to a tv 'picture in picture' mode

### ISSUE THREAD

**Issue by mrbfrank** [eczarny/spectacle#433]
Hi I love Spectacle but recently have been looking for this feature in a window manager. The idea is to emulate a tv 'picture in picture' mode, allowing you to pin a window to the screen and make it appear on all desktop spaces. An opacity setting for this window would be nice as well. I want to use this feature for watching videos, or monitoring logs from my terminal, etc. while working on other things.

I have not yet dug enough into the Spectacle source code to size this task, but wanted to post this to gauge interest at the very least.

Do you like this idea? Please comment, thanks.

**Comment by eczarny** [comment]
Sorry, not a feature I'm likely to add to the app.
