### ISSUE TITLE
MenuAndDockless Fullscreen issue

### ISSUE THREAD

**Issue by arkrozycki** [eczarny/spectacle#434]
I'm trying to use Spectacle with MenuAndDockless so that I can have a full screen real estate for every application. 

However, when I hide the menu bar and then attempt to use spectacle to move windows around or go full screen the application will leave room for the menu bar. Is there a way to over ride this behavior so that it will take advantage of all screen real estate.

**Comment by eczarny** [comment]
Duplicate of #277.
