### ISSUE TITLE
Serve site over HTTPS

### ISSUE THREAD

**Issue by feross** [eczarny/spectacle#435]
It's not safe to install software from sites that are served over plaintext http. The download link could be replaced by a man-in-the-middle (i.e. a coffee shop owner, or a naughty ISP).

HTTPS is the only way to guarantee that users will get the right web page, and thus, the right software.

:)

**Comment by ptz0n** [comment]
The binary can be hosted on S3 to biggy back on their SSL cert.

**Comment by feross** [comment]
The binary is currently hosted on S3 with SSL. That's not enough. The actual site needs SSL too, or else the download link can be replaced with a link to anything by a man-in-the-middle.

**Comment by eczarny** [comment]
I'm less concerned since the binary is signed by me. Of course this doesn't prevent people from doing crazy things like disabling Gatekeeper and running untrusted binaries.

Still, it would be nice to serve spectacleapp.com over HTTPS.

**Comment by feross** [comment]
HTTPS all the things! A sophisticated attacker can sign binaries too.

**Comment by eczarny** [comment]
:+1:

**Comment by eczarny** [comment]
Any suggestions on obtaining inexpensive and reputable certificates?

**Comment by kokarn** [comment]
If you'r not in a hurry, https://letsencrypt.org/ will open Q4 and be free

**Comment by eczarny** [comment]
I could probably wait for a while.

**Comment by dsernst** [comment]
Cloudflare offers free SSL between their servers and the users: https://www.cloudflare.com/ssl . It's very  easy and quick to set up.

It's an incomplete solution, because the connection Cloudflare and your server is still unencrypted. But it's better than the current setup, and protects against MITM on the downloader's local network (the coffee-shop case).

**Comment by eczarny** [comment]
I did exactly this. We'll see if it works once the changes take effect!

Once I know it works I'll move towards their Full SSL option.
