### ISSUE TITLE
Option + Command + C conflicts with dev tools shortcut for Firefox/Chrome

### ISSUE THREAD

**Issue by ryanpcmcquen** [eczarny/spectacle#436]
I would like to suggest that the default for this shortcut be changed to something that does not conflict with this universal shortcut for dev tools.

Perhaps <kbd>Option</kbd> + <kbd>Command</kbd> + <kbd>M</kbd> for "Middle"?

**Comment by eczarny** [comment]
I'm not inclined to change the defaults. Just change the shortcuts to fit your needs.

**Comment by ryanpcmcquen** [comment]
Thank you for the reply.

**Comment by ryanpcmcquen** [comment]
@eczarny, is spectacle configurable through the command line?
