### ISSUE TITLE
Selecting Preferences in menu does nothing in Yosemite

### ISSUE THREAD

**Issue by nastysloper** [eczarny/spectacle#439]
I'm trying to change some keyboard shortcuts so I can navigate tabs in Chrome (which use the same key bindings Spectacle uses to move a window to the left or right side of the screen. When I select Preferences, however, apparently nothing happens.

**Comment by eczarny** [comment]
Is the window opening behind another? Maybe it's opening on another display?

**Comment by nastysloper** [comment]
It appears that no window opens anywhere. I'm not using a second display, and when I hit F3 to see which windows are active, I don't see a window associated with Spectacle. Command-Tab also doesn't show a Preferences window.

**Comment by eczarny** [comment]
The window will not appear like a typical window since Spectacle runs in the background. Have you tried launching Spectacle a second time (keep it running when you do so)? This should force the window to appear.

**Comment by nastysloper** [comment]
That did the trick. Thank you!
