### ISSUE TITLE
Spectacle keyboard shortcuts fail to work with Adobe Reader DC after Duet Display is enabled

### ISSUE THREAD

**Issue by jadchaar** [eczarny/spectacle#445]
Recently, I got back into using Duet Display with my iPad. Unfortunately, once I enabled it, my keyboard shortcuts for Spectacle stopped working with Adobe Reader DC. Manually clicking the positioning options using the menu bar icon still worked though. If you need more information, please let me know.

**Comment by eczarny** [comment]
Adobe Reader is not supported by Spectacle. What version of Spectacle are you seeing this with?

**Comment by jadchaar** [comment]
Hey Eric, I am using the latest version: Adobe Acrobat Reader DC (2015 Release | 2015.008.20082).

I was able to use the shortcuts just yesterday with it. I have a feeling it stopped working after I enabled Duet Display. Furthermore, the window positioning functions correctly when manually done through the menu bar icon, but not through the keyboard shortcuts. That caveat is a huge part of the puzzle.

Secondly, I tried window positioning on another Mac earlier (with the latest version of Adobe Reader (the pre-DC version)) and the previous release of Spectacle. Spectacle did not function there either. It seems to be an issue with Adobe Reader, not Spectacle.

Just curious, do you have to add support for applications manually, or is it just a process of bug fixing certain applications (automatically supported)?

**Comment by eczarny** [comment]
I don't explicitly support anything. Spectacle tries to move windows around with builtin system APIs. From https://github.com/eczarny/spectacle#spectacle-does-not-work-with-all-applications:

> __Spectacle does not work with all applications__
>
> Most applications built with the Cocoa frameworks can be readily manipulated via the OS X Accessibility Protocol; allowing Spectacle to interact with nearly every window it encounters. Unfortunately this is not always the case. Spectacle will be unable to manipulate the windows of applications that build their user interfaces in unexpected ways.

**Comment by jadchaar** [comment]
Thanks for investigating this.

**Comment by JesseSlim** [comment]
I think the case here is that Acrobat Reader catches the keyboard presses before they are sent to Spectacle, so Spectacle never actually receives a window resizing command. You can see the mouse cursor changing in Adobe Reader if you press the option key (signifying some different selection mode) so I suppose that causes the conflict. It would also explain why the menu options still work.

I fear the only solution then is to switch pdf readers or to somehow disable the Acrobat Reader keyboard shortcuts and hoping that the commands will then come through to Spectacle - I haven't looked in to this yet.
