### ISSUE TITLE
Hotkey command-option-left, left, left not working

### ISSUE THREAD

**Issue by moveout2** [eczarny/spectacle#448]
**I was prompted to install the latest version of spectacle yesterday (1.0 / 503) and since then some of the hotkeys are acting very strangely.**

I use the hotkey combination *command-option-left*, then *left* again, then *left* again, to cycle between 2/3 screen size, then 1/2, then 1/3. I LOVE that feature and use it all the time. However with the new version the apps just wig out. It's especially annoying in Microsoft Outlook 2016, because it causes my reading pane to disappear.

I have similar results with Finder, Chrome, and Safari.

This worked beautifully before, so whatever changed in the last build broke this functionality.

Thanks for a great product BTW.

-Todd

**Comment by eczarny** [comment]
Can you provide some screenshots?

**Comment by moveout2** [comment]
See attached. I created this running Chrome, and using the hotkey combination "command-option-left, left, left".

Let me know if the GIF doesn't work for you...

-Todd

![spectaclebug](https://cloud.githubusercontent.com/assets/14075372/9669575/f57061c2-523c-11e5-9408-cbd1be9e85bc.gif)

**Comment by eczarny** [comment]
What happens if you reboot?

**Comment by moveout2** [comment]
It makes no difference.

So am I the only person experiencing this?

-Todd

On Thu, Sep 3, 2015 at 4:47 PM Eric Czarny <notifications@github.com> wrote:

> What happens if you reboot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eczarny/spectacle/issues/448#issuecomment-137603192>.
>
-- 
-Todd

**Comment by anandgraves** [comment]
I experience the same issue with Spectacle version 1.0 (503) on OSX 10.10,4 (14E46), but only in Safari version 8.0.7 (10600.7.12). In Chrome, Firefox, iTerm, Atom and other applications it all works without issues. In Safari it gives the error sound and goes back to the 2/3 screen.
![spectacle_safari](https://cloud.githubusercontent.com/assets/6824459/9695187/999f168a-535f-11e5-8e10-45dfb908af06.gif)

**Comment by moveout2** [comment]
I'm running OS X Yosemite v10.10.5 (14F27) on a mid 2012 MacBook Pro Retina (2.3 GHz Intel Core i7 / 16 GB 1600 MHz DDR3 / NVIDIA GeForce GT 650M 1024 MB).

Hope that helps.

-Todd

**Comment by moveout2** [comment]
A little more information that should be helpful: When I use the menus to do the same thing, the positioning works as expected. So it looks like its only the hotkey that is a problem.

-Todd

**Comment by eczarny** [comment]
I was just able to reproduce this issue! I'll work on a fix for 1.0.1. :+1:

**Comment by eczarny** [comment]
I was only able to reproduce with Safari, but I think this is just a case of the behavior outlined here:

https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected

Safari 8.0.8 on my 15-inch MacBook Pro will not let windows be resized small enough to fit into 1/3 of the display. Unfortunately this behavior is expected.

The issue @moveout2 is seeing with Chrome is much stranger and not something I can reproduce. What version of Chrome is it?

**Comment by moveout2** [comment]
The version of Chrome is 45.0.2454.85. I get the same behavior with Finder, Safari, Outlook, pretty much every app.

I did not have this problem before I upgraded to the latest version, and I use this hotkey all day long. Also, using the menus seems to work as expected (click Spectacle then Left Half, Spectacle the Left Half, etc.) so I'm not sure the link above applies.

-Todd

**Comment by moveout2** [comment]
Some more information...

I was trying to cycle through tabs in Chrome, wasn't sure what the keyboard hotkeys were, and when I looked them up, some looked to be the same as Spectacle - exactly what I was trying to do (command-option-left, etc).

So I closed Spectacle via the menu bar to try it in Chrome, and rather than allowing me to control Chrome tabs, it actually fixed my issue! Even though Spectacle is no longer in my menu bar, the hotkey is working on all my apps as expected.

Hope that helps you out.

-Todd

**Comment by eczarny** [comment]
Sounds like you had more than one process of Spectacle running? Use Activity Monitor to make sure all Spectacle processes have been terminated and check that there is only one login item (if you enabled Spectacle to launch on login). With all that cleared up you can reboot to make sure everything is good.

**Comment by moveout2** [comment]
You nailed it on the head - had 2 Spectacle items in Login Items. I removed one and rebooted, and I'm back to normal.

I'm guessing the latest installer did that.

Anyway, I really appreciate your help. As I stated at the beginning, I love Spectacle!

**Comment by eczarny** [comment]
Glad you were able to get things working! I actually have no idea how you managed to get two Spectacle login items. Crazy.

**Comment by jackwilsdon** [comment]
+1 I'm still experiencing this. It seems to be that Safari has a minimum window size, and Spectacle is trying to resize it to be smaller than that. When I press "Left Half" the third time (to scale it from 2/3 to 1/3), it makes an error sound, flashes at the size 1/3 and then resizes back to 2/3.

**Comment by eczarny** [comment]
@jackwilsdon That's expect behavior.
