### ISSUE TITLE
Export and import Spectacle preferences

### ISSUE THREAD

**Issue by eczarny** [eczarny/spectacle#45]
It should be possible to export and import Spectacle's hot keys.

**Comment by mathiasbynens** [comment]
Instead of an app, here’s a simple Bash script that extracts the current configuration: https://github.com/mathiasbynens/dotfiles/issues/507#issue-59460151

**Comment by s10wen** [comment]
:+1:

**Comment by pozix604** [comment]
+1 for proper method to import/export settings, preferably accessible via command line.

**Comment by eczarny** [comment]
Closing in favor of #424.
