### ISSUE TITLE
Spectacle icon no longer shows up in status bar

### ISSUE THREAD

**Issue by cpeterso** [eczarny/spectacle#451]
After the recent update to Spectacle 1.0 on two different MacBook Pros running OS X 10.10.4, Spectacle's icon no longer shows up in status bar, though even though Spectacle is configured to launch at login. I see the Spectacle process running and it correctly responds to keyboard shortcuts.

**Comment by eczarny** [comment]
What happens if you try toggling the setting to display in the status bar?

**Comment by cpeterso** [comment]
Switching from "Run in the status menu" to "Run as a background application" and back does restore the icon.

**Comment by eczarny** [comment]
I'm closing out this issue and tracking the problem in #451 instead.
