### ISSUE TITLE
Stopped working with BBEdit

### ISSUE THREAD

**Issue by useEvil** [eczarny/spectacle#452]
0.8.6 was working just fine.  Since I've updated to 1.0 it stopped working a couple applications specifically BBEdit.  I've reverted to 0.8.6.

MacBook Pro (Retina, 15-inch, Late 2013)
2.3 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB
OS X 10.10.5

**Comment by eczarny** [comment]
Can you elaborate? Are there any relevant messages in your Console?

**Comment by useEvil** [comment]
None of the commands work in v1.0 for BBEdit.  It does not move any of BBEdit's windows.  There is nothing in the console logs.

**Comment by eczarny** [comment]
Just look for a line with Spectacle present.

**Comment by useEvil** [comment]
I didn't see any errors.  I reinstalled v1.0 this morning.  This time I downloaded the application instead of having the application update itself.  So far it's working.

**Comment by eczarny** [comment]
Interesting! Did you happen to reboot at any point?

**Comment by useEvil** [comment]
I didn't reboot, just quit the applications.  All the windows are resizing and moving now, except for the "Find" window.  I had to revert to version 0.8.8.
