### ISSUE TITLE
Is there any support for external monitors? (Feature)

### ISSUE THREAD

**Issue by g12mcgov** [eczarny/spectacle#454]
Hi Guys, 

I love spectacle, it's totally awesome, but I was wondering if there is/are any plans for external monitor support? I.e. windows can be sent to either left or right monitors in the case of dual monitors?

**Comment by eczarny** [comment]
This feature exists. From the README (https://github.com/eczarny/spectacle#multiple-displays):

> __Multiple displays__
> 
> The ⌃⌥⌘→ keyboard shortcut will move a window to the next available display. ⌃⌥⌘← can be used to move a window to the previous display.
