### ISSUE TITLE
Spectacle not working with specific app

### ISSUE THREAD

**Issue by FlyingSufi** [eczarny/spectacle#455]
First : thank you for this app, I just can't use my Mac without it.

Since Spectacle 1.0 (on Yosemite, MBP late '11) , I cannot resize the windows for an app I use every day : Satimage's Smile (for writing Applescripts). I get an error sound instead.
There may be something it this particular app that makes it impossible for Spectacle to move it : I have no trouble with Chrome for instance. 

The previous version of Spectacle I used to run had no pb. 
I tried to get back to it (while quitting the new one) but for the previous version
- I cannot get the icon in the menu bar, even if I ask to run it in the menu bar (= not as background application)
- Once Spectacle.app is off, the settings disappear.

Do you have any lead I can investigate to get the new version working with Smile, or ask Smile's developers to change a little thing in their own app so that it's again compatible with Spectacle ?

**Comment by pevoje** [comment]
Have the same problem with Office 2011 apps. Any ideas?

**Comment by FlyingSufi** [comment]
Hadn't noticed yet, but same here. Thx @pevoje !

**Comment by eczarny** [comment]
Certain versions of Office 2011 don't work with Spectacle. See #447 for a bit more information.

@FlyingSufi do you see anything in Console.app when you run into trouble with Smile? Also, have you tried restarting your computer to see if it fixes anything?

**Comment by FlyingSufi** [comment]
@eczarny I upgraded Excel and it's now working, indeed.
I find it strange that previous version of Smile was OK with the previous version of Excel...
Would you mind telling me what changed in the way Spectacle deals with windows between 1.0 and the previous version, so that I can give some hints to Satimage support ?

**Comment by FlyingSufi** [comment]
Oh : and here is a Console warning concerning Smile 

WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.10.5. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.

I feel like there may be some link with our problem, don't you think so ?

**Comment by spry-rproud** [comment]
It appears that since the 1.0 update spectacle no longer works with pgAdmin III.

**Comment by FlyingSufi** [comment]
Very weird : Excel is now again not responding to Spectacle 1.0
So I rebooted the system : I observe a new line with the Console talking about the Gestalt selector thing for Excel...
In the Console as well, Smile is telling me this :
 "-[CarbonWindowFrame aspectRatio]: unrecognized selector sent to instance 0x12d0ca20"

**Comment by eczarny** [comment]
Microsoft products have always been notoriously difficult for Spectacle to work with. There is quite a bit of information on the README that explains what can cause problems for Spectacle.

The only other change in Spectacle 1.0 that could cause problems is if the windows you are trying to interact with are considered system dialogs. Spectacle will not move a system dialog (e.g. the Notification Center). The Accessibility Inspector will tell you more information about an accessibility entity, just hover your mouse over a window to see what it is.

**Comment by spry-rproud** [comment]
PGAdmin III shows up as AXWindow:AXDialog, but I do remember it working prior to 1.0.  Is the dialog restriction/limitation a new addition with 1.0?

**Comment by eczarny** [comment]
Spectacle only ignores dialogs with a system subrole. Here is the check:

https://github.com/eczarny/spectacle/blob/master/Spectacle/Sources/SpectacleAccessibilityElement.m#L148

**Comment by eczarny** [comment]
It's new in 1.0.

**Comment by FlyingSufi** [comment]
I don't get it, it's working again right now with Excel. Awkward.
Smile is not responding, I'll see with the developers what can be done...

Is there a particular reason for ignoring such "dialogs with system subrole", whatever this means ?

(I'm quite new here, my sincere apologies if my manners don't follow the code of behavior in use...)

**Comment by eczarny** [comment]
The specific case for ignoring system dialogs was to prevent Spectacle from resizing Notification Center or the Spotlight system dialog. There may also be other dialogs with this subrole so I figured it would be a good check to have in place. I don't really know why an app would (or could) specify this subrole on a window.

**Comment by FlyingSufi** [comment]
I used the Accessibility Inspector on the two windows of Excel (the first one that fails, and the one I created that works).
The Attributes are pretty much the same and Hierarchy shows for both windows
AXApplication > AXWindow:AXStandardWindow>AXUnknown>AXUnknown

For both, accessibilityRole is AXUnknown.
Not much help I'm afraid...

**Comment by spry-rproud** [comment]
PGAdmin also has AXUnknown.

**Comment by pevoje** [comment]
got the new update for Office 2011 package and now Spectacle works just fine, haven't encountered this behaviour before (for 2 years for how long I'm using Spectacle) , very strange indeed...

**Comment by FlyingSufi** [comment]
What about the very first sheet that is automatically created when you call Excel ?
For me, it's impossible to move with Spectacle this very precise window.
The other work fine.

And Satimage's Smile ? Would you mind install it (it's free) and tell me if it works OK on your installation ?

**Comment by eczarny** [comment]
Spectacle will not move sheets.

I'll try installing Smile and see if I can reproduce the issue.

**Comment by FlyingSufi** [comment]
Yes it does, at least when the sheets are in their own window, which is the case on my laptop.
Or maybe it's not really the sheets, but the workbooks I'm talking about. 
But it did with Spectacle 0.8.8 and still does with the 1.0, apart from the very first window.

**Comment by eczarny** [comment]
Sorry. I'm not too keen on installing an app that requires an installer, or an app I don't really know about on a laptop I use for work. I won't be able to dig into the issues you are seeing with Smile.

**Comment by jsynowiec** [comment]
Spectacle 1.0 (503) can't resize or move Omnie Graffle 6.2. I don't know if it worked with earlier versions but other apps like SizeUp or BTT works without problem. Omni Graffle has AXWindow / AXStandardWindow.

**Comment by FlyingSufi** [comment]
@eczarny I have Smile on my work laptop for 4 years, it's a tool I use almost daily, but it's your choice.
Anyway : do you manage to reproduce the pb I was talking about with Excel 2011 ? You have this application, haven't you ?

**Comment by eczarny** [comment]
@FlyingSufi I see the issue you are having with Excel and I'm investigating. It could be related to other issues folks are reporting as well. I'll dig into this tonight.

**Comment by eczarny** [comment]
I think this check is the issue:

https://github.com/eczarny/spectacle/blob/72838b939c9374167e82e99288efd34fd2c38ddb/Spectacle/Sources/SpectacleAccessibilityElement.m#L139-L144

This change was to address issues like #206. Looks like I'll need to think of a new way handle this.

**Comment by FlyingSufi** [comment]
Cool, thank you Eric !

**Comment by eczarny** [comment]
I have one more fix I would like to finish but I hope to release Spectacle 1.0.1 sometime today or tomorrow.

**Comment by eczarny** [comment]
I just released a fix. @FlyingSufi could you try Spectacle 1.0.1 and let me know if it fixes your issues?

**Comment by FlyingSufi** [comment]
Yes indeed it does, works like a charm ! Shugoi !!
Thank you so much Eric !

Glad I tipped you a few days ago ;)

**Comment by spry-rproud** [comment]
pgAdmin works now.  Thanks!

**Comment by FlyingSufi** [comment]
I don't know how/if I can close the thread now, for me the actual behavior is perfect.
You rule mate !

**Comment by jsynowiec** [comment]
Unfortunately OmniGraffle still doesn't work with 1.0.1

**Comment by cybersam** [comment]
I have been seeing (with version 1.0.0, and now with 1.0.1) that Spectacle would occasionally stop working with Android Studio windows. If this happens (not very common), I believe I notice it right after I re-login to my Mac (Yosemite 10.10.5). I can recover if I close the window and reopen it, or if I open a second Android Studio window.

**Comment by spdavern** [comment]
Spectacle v 1.0.1 (509) doesn't seem to be working with Adobe Reader v 11.0.13 and OS X El Capitan v 10.11.1.  It works with Chrome in the same environment.

**Comment by scottkall** [comment]
@jsynowiec Spectacle 1.0.1 still doesn't work with OmniGraffle 6.4.1. But since this thread is closed, should I post this elsewhere?

**Comment by jsynowiec** [comment]
@scottkall most likely.

**Comment by marioluan** [comment]
Doesn't work with TIDAL [1] app neither.

[1] https://tidal.com/
