### ISSUE TITLE
"Spectacle.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by mjeightyfive** [eczarny/spectacle#456]
> "Spectacle.app" is damaged and can't be opened. You should move it to the Trash.

![spectacle.app](https://s3.amazonaws.com/f.cl.ly/items/2m2q0k3T4524133F3S3C/spectacle.app.png)

Version 1.0 (503) on OSX Yosemite 10.10.5. Happens after reboot when 'Launch Spectacle at login' is checked.

**Comment by eczarny** [comment]
Have you tried downloading it again?

**Comment by mjeightyfive** [comment]
Yes. A few times. I've not tested if with 'Run.. in the status menu' and 'Run.. as a background application' makes any difference, but will try as soon as I can.

**Comment by eczarny** [comment]
I honestly don't know what would cause this error except issues downloading the binary or your disk is corrupting the file. What if you download with Safari?

**Comment by mjeightyfive** [comment]
Downloading with Safari seems removing the issue.

Before, when downloaded with Chrome it worked fine until auto launching at login.
Thank you for your help!
