### ISSUE TITLE
Spectacle 1.0.1 - Doesn't work with Twitter.app mainwindow

### ISSUE THREAD

**Issue by Grunerd** [eczarny/spectacle#457]
Almost every application I work with works with Spectacle 1.1 now, but the main window from the official Twitter.app (Mac App Store) stopped working. The "new tweet" window however still works and moves absolutely fine in every corner and every connection. The Console.app doesn't give me any useful output to post here.

<img width="712" alt="screen shot 2015-09-11 at 15 11 38" src="https://cloud.githubusercontent.com/assets/11262143/9815574/6c47ded2-5897-11e5-903d-70844a377f16.png">

My spectacle-setup, by the way:

<img width="728" alt="screen shot 2015-09-11 at 15 13 54" src="https://cloud.githubusercontent.com/assets/11262143/9815606/c2257d50-5897-11e5-9b82-9935dc6855bb.png">

**Comment by eczarny** [comment]
So, I believe I found the problem. How did Spectacle behave when manipulating the main window prior to the latest release?

**Comment by Grunerd** [comment]
It moved correctly - and then snapped into the upper-left corner of the set quadrant. That behaviour was strange, but it worked for me. Now it’s not moving at all.

**Comment by eczarny** [comment]
I should have a fix for you but I want Spectacle to behave a bit more consistently. I'll work on getting this into a 1.0.2 release!
