### ISSUE TITLE
Undo no longer works on the first window movement

### ISSUE THREAD

**Issue by eczarny** [eczarny/spectacle#459]
I just noticed this issue in Spectacle 1.0.1. If you use Spectacle to move a window you cannot undo the first window movement. Subsequent window movements appear to work.

For example, suppose you open Chrome and move a window to the left half of the screen. Prior to 1.0.1 (and most likely 1.0 as well) you could undo the window movement and Spectacle will put the window back where it was. If you move a window to the left half of the screen then to the top half of the screen you can undo the second window movement. Spectacle will move the window back to the left half of the screen. Trying to use undo again will not work.

**Comment by fl0at** [comment]
I can duplicate this too, on OS X 10.11.3. Happy to help if you need any! :)

**Comment by eczarny** [comment]
I'm unable to reproduce this issue with Spectacle 1.0.6.
