### ISSUE TITLE
One Third wide window on Macbook won't work

### ISSUE THREAD

**Issue by OneThirdWindow** [eczarny/spectacle#460]
I am using a MacbookPro 13 inch, and have regular settings in use. Running 10.9.5 and also tested Yosemite with same issue). This issue us about controlling the software to show Finder Windows at 1/3 the space on the Macbook.

Spectacle Versions will not work on this machine. They do work on an iMac 27 inch. If the setting is used, by menu or key-combo to set a Finder window to 1/3 it does so for split second and then jumps back to the former width and position.
What can be done, so the 1/3 wide finder-window stays so?

**Comment by eczarny** [comment]
Please read https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected for some details on why this isn't working for you.

**Comment by OneThirdWindow** [comment]
Hello Eric,

Thank you for your information.
Regards, Peter

Von:  Eric Czarny <notifications@github.com>
Antworten an:  eczarny/spectacle
<reply+00d96f3f0d9db03ca0950e33500adf21569366043db2534e92cf00000001120c4be09
2a169ce0653ecad@reply.github.com>
Datum:  Samstag, 12. September 2015 22:24
An:  eczarny/spectacle <spectacle@noreply.github.com>
Cc:  Office <brendel@compuserve.com>
Betreff:  Re: [spectacle] One Third wide window on Macbook won't work (#460)


Please read 
https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-
window-as-expected for some details on why this isn't working for you.


Reply to this email directly or view it on GitHub
<https://github.com/eczarny/spectacle/issues/460#issuecomment-139817700> .
