### ISSUE TITLE
[1.0.1] Error sound with every action

### ISSUE THREAD

**Issue by mcnesium** [eczarny/spectacle#462]
On Yosemite since v1.0.1 upgrade, it does the system error sound with every spectacle action. Is this behaviour intended?

**Comment by eczarny** [comment]
Have you tried rebooting?

**Comment by eczarny** [comment]
Also, any relevant messages in Console?

**Comment by mcnesium** [comment]
I do have rebooted during the last week. Paying attention to this now I have to admit that the sound is gone. No clue though, whether this is caused by the reboot, but it's now showing expected behaviour. Thank you for the advice and for providing this software :+1:
