### ISSUE TITLE
Order of 1/3, 1/2, 2/3 switch is wrong again

### ISSUE THREAD

**Issue by medv** [eczarny/spectacle#463]
#366 is back, could not re-open.

**Comment by eczarny** [comment]
The expected order is 1/2, 2/3, then 1/3. The change was made as 1/3 can often fail due to size restrictions on certain windows. If 1/3 failed so would 2/3 (despite size restrictions not being an issue). Is this not the behavior you are observing?

**Comment by medv** [comment]
My mac is currently being fixed, will check when I have it back and reply.

However it's counter intuitive if you're trying to push something to the LEFT (shortcut that utilises left arrow) and the window going from half to 2/3s, therefore being bigger as its first move.

As someone that splits his screen in half (left half is browser, right is sublime text) and working on mobile sites/apps, it's odd having to cycle to 2/3 first up since by doing a shortcut that feels like LEFT should squash it first rather than grow the window first..

**Comment by eczarny** [comment]
The 1/2, 1/3, and 2/3 order definitely causes problems for different apps and different screen dimensions. To unblock folks from getting to 2/3 this is definitely the best solution at the moment.

I probably won't get around to making it configurable, but feel free to submit a pull request that uses an hidden preference.
