### ISSUE TITLE
spectacle constantly stops working 

### ISSUE THREAD

**Issue by iIswip** [eczarny/spectacle#464]
Every day, and sometimes during the same day, Spectacle stops resizing my page when I use the shortcut combination cmd+shft+F. (I never had this problem with Right Zoom). How can I fix this glitch?

T

**Comment by eczarny** [comment]
Have you tried rebooting? Are there any messages in Console?

**Comment by iIswip** [comment]
Hi Eric,

Thanks for your reply.

I shut down my computer often. Actually, that's when the problems often
occur. I just booted up for the day, and Spectacle is not working again.
That means I have to download the app again, if I want to zoom page size.

I checked Console, but Spectacle doesn't appear. I don't know what other
logs might be relevant.I hope you can help me.

Thanks,

Tamara

**Comment by iIswip** [comment]
Hi Eric,

I changed the shortcut key for zooming. I think the problem was that cmd+opt+F is already taken as a search shortcut key. Perhaps this combination should not be used as the default key for zooming in Spectacle. Cmd+opt+E (the combination used by Right Zoom) seems to work well.

Tamara

**Comment by eczarny** [comment]
Oddly enough, I ran into the same problem today. I think there is an issue with the way Spectacle observes shortcuts.

**Comment by capnfabs** [comment]
I just observed the same issue; it's a problem for one tab (http://inbox.google.com) but not for another (this page).

**Comment by dhallgb** [comment]
I had the same issue and re-mapped fullscreen away from cmd+opt+F and it seems to work better.  I'd have to agree that it is something to do with the way Spectacle observes shortcuts, as it'd work more consistently on windows other than browsers windows.
