### ISSUE TITLE
Feature Request: Upper Third and Half

### ISSUE THREAD

**Issue by Soubkia** [eczarny/spectacle#465]
*All shortcuts listed are in the default configuration*

When moving a window to half the screen (⌥⌘→, ⌥⌘←, ⌥⌘↑, ⌥⌘↓ ) if you continue to press → it will cycle through 1/2, 2/3's, and then 1/3 widths for the window.

I think it would make a lot of sense to have that same functionality when moving to the upper/bottom left/right (⌃⌘→, ⌃⇧⌘→, ⌃⇧⌘←, ⌃⌘←). As it is now there is no way to make a half height window that is of 1/3 width.

**Comment by eczarny** [comment]
Not sure this is something I would want to implement and maintain. This would be something better suited for #427. I hope to begin work on the initial implementation of that functionality over the winter.
