### ISSUE TITLE
retab extension for safari

### ISSUE THREAD

**Issue by iIswip** [eczarny/spectacle#466]
Doesn't work. Has never worked. Does anyone have any suggestions about how to bring this extension to life?

Thanks

**Comment by eczarny** [comment]
I have no idea what this extension is/does?

**Comment by iIswip** [comment]
Supposedly, you can open a whole string of closed tabs, not just the single
one that Safari allows.

**Comment by iIswip** [comment]
Eric,

How come you closed my case? You didn't resolve the problem.

Tamara

**Comment by eczarny** [comment]
Could you provide some more information about the exact problems you are having? I closed the issue because I don't see how Spectacle should work with a Safari extension.

**Comment by iIswip** [comment]
Retab IS a safari extension. It works like cmd+z, except you can reopen
many generations of closed tabs, not just one. The extension is activated
by means of the shortcut keys cmd+shft+T. But when I use those keys,
nothing happens. If you need more info, google;
http://definecult.com/2015/05/retab-reopen-all-older-recently-closed-tabs-in-os-x-safari/
.

Thanks,

Tamara

**Comment by eczarny** [comment]
Does the shortcut work when Spectacle is not running or disabled? Did you add that shortcut to Spectacle?
