### ISSUE TITLE
Spectacle does not work with Safari 9.0

### ISSUE THREAD

**Issue by loc4me** [eczarny/spectacle#470]
Spectacle 1.0.1 will not resize Safari after updating to 9.0 on 10.10.5 Yosemite.

**Comment by eczarny** [comment]
Could you be more specific? Are there any errors in Console? What happens if it quit and relaunch Spectacle or reboot?

**Comment by loc4me** [comment]
Well it's working now. I had previously quit and relaunched spectacle and it did not fix my issues but now it is working fine with Safari 9.0.

**Comment by eczarny** [comment]
Is the behavior the same as described in #446?
