### ISSUE TITLE
Small gap at the top of a window

### ISSUE THREAD

**Issue by nickschot** [eczarny/spectacle#473]
When I stretch a window I get a small gap on the top through which I can see the wallpaper. Is this meant to be like this? 

 * MBPR 13
 * El Capitan
 * Spectacle 1.0.1

Examples:

<img width="392" alt="screen shot 2015-10-04 at 18 58 18" src="https://cloud.githubusercontent.com/assets/334789/10269022/2b261988-6aca-11e5-96d0-af27824c40dd.png">
<img width="251" alt="screen shot 2015-10-04 at 19 00 08" src="https://cloud.githubusercontent.com/assets/334789/10269023/2b4cf940-6aca-11e5-9f09-45dd105c2f7e.png">

**Comment by eczarny** [comment]
Does the gap exist if you drag the window to be flush with the menu bar?

**Comment by eczarny** [comment]
Closing as OS X forces this gap on all windows.

**Comment by nickschot** [comment]
Indeed, it seems this is forced. Didn't notice it on Yosemite, so thought it could be a bug ;-)
