### ISSUE TITLE
Spectacle does not completely maximize windows OS X El Capitan

### ISSUE THREAD

**Issue by jbernardo95** [eczarny/spectacle#474]
As you can see on this screenshot after trying to maximize a window using spectacle there is a slight portion of the window on the left side which is not completely touching  the left side of the screen.

<img width="31" alt="screen shot 2015-10-05 at 15 10 23" src="https://cloud.githubusercontent.com/assets/6342528/10282585/8f8ae436-6b73-11e5-8f25-d74e9ae23855.png">

Macbook Pro Retina 2013

**Comment by eczarny** [comment]
Is your Dock hidden on the left side?

**Comment by jbernardo95** [comment]
It is, is that a problem ?

This really is annoying.

**Comment by eczarny** [comment]
That's how the Dock works. OS X always leaves a little room for it. Since Spectacle honors the visible frame of the screen this will always be there.

**Comment by joaocunha** [comment]
Had trouble finding this issue (which I was also experiencing), so I'm adding a few more search keywords.

Fullscreen, full screen, gap, left, side, offset, margin, screen.
