### ISSUE TITLE
Please allow per-keyboard hotkeys (or any other viable solution to my issue)

### ISSUE THREAD

**Issue by muesic** [eczarny/spectacle#475]
I have an external extended keyboard hooked up to my MacBook Pro and I made the Spectacle hotkeys spacially correspond to the numeric pad on the right side of the keyboard. I've indicated the layout of the numeric pad below (crap - I just previewed my post and all the tabs got replaced with spaces so my key pad "drawing" doesn't look any good):
	C	+	/	*
	7	8	9	-
	4	5	6	+
	1	2	3	E
	0	0	.	E
I made my hotkeys intuitively be Control Option <number> spacially according to:
	prev	next	Und	Redo
	TL	T	TR	Smaller
	L	C	R	Bigger
	BL	B	BR	E
	Full	Full	.	E
So that all works great - until I disconnect my external keyboard and take the laptop with me to a conference room. Suddenly I don't have a numeric pad on the laptop keyboard and so none of the hotkeys work anymore.
Now I guess I already know that my hotkeys are mapped as e.g. TopLeft = Control Option KP_7, where KP_7 categorically means the 7 on the Key Pad and not the 7 in main part of the keyboard. So Control Option 7 won't work to get me Top Left. When the external keyboard is missing KP_Anything doesn't exist on the remaining keyboard and so I have no hotkeys available, and I'm looking for a solution to that problem.
So one solution is to allow hotkey mappings on a per keyboard basis, or multiple hotkeys per function, or if Spectacle can't execute a hotkey because the key doesn't exist then maybe it could fall back on the system default. I dunno - any other suggestions?

**Comment by eczarny** [comment]
Unfortunately I'm not sure what to do here. As per #241 this behavior is expected and I'm not inclined to deviate from existing system behavior.

**Comment by muesic** [comment]
So it looks like someone else (in issue #241) has had virtually exactly the same idea! That numeric pad on the extended keyboard is a very intuitive way to move windows around. Would you please consider allowing the user to manually select from a choice of named hotkey sets. The Spectacle defaults would be one set, and (in my case) I would have two others - one for when the external keyboard is attached and another for just the native MacBook Pro keyboard itself. I think that could solve the problem nicely :-).

**Comment by eczarny** [comment]
No promises I will get a chance to work on this. Pull requests welcome!

**Comment by olivierlefloch** [comment]
This is also affecting me, as I sometimes have my MacBook Pro plugged into an external keyboard+monitor, but not at all times.
Perhaps detecting extended/normal keyboard, or having the possibility to define multiple shortcuts for each command would help?

**Comment by muesic** [comment]
Just wondering - what does it mean now that the issue is "closed". Has it been fixed for a future release or has the request been shut down?

**Comment by eczarny** [comment]
@muesic In this particular case I closed this enhancement because it isn't something I intend to build myself or accept as a pull request.

**Comment by muesic** [comment]
Hi Eric,

Not sure what a pull request is, but I'm interpreting this email as "it's not going to be done". Is that correct?

Regards,

Mick


On Aug 31, 2016, at 03:04 PM, Eric Czarny <notifications@github.com> wrote:

@muesic In this particular case I closed this enhancement because it isn't something I intend to build myself or accept as a pull request.

**Comment by eczarny** [comment]
@muesic correct.
