### ISSUE TITLE
moving to next/previous display does not work in El captian

### ISSUE THREAD

**Issue by sarjan** [eczarny/spectacle#476]

**Comment by eczarny** [comment]
More information would be helpful.

**Comment by Wizmann** [comment]
same problem here

**Comment by Grunerd** [comment]
It works for me (with Safari, Transmit, VMWare, Finder and several other applications on both, 10.11.0 and 10.11.1 beta - I was just about to file in a feature-request that allows "switching the monitor focus" while moving.
