### ISSUE TITLE
Include Spectacle in startup

### ISSUE THREAD

**Issue by Andrew-Chapman** [eczarny/spectacle#477]
Hi, is it possible to include Spectacle in the startup - I have to launch it each time. It doesn't show up in the list of applications to add to start up in System Preferences. Am running El Capitan 10.11 on a mid-2010 MacBook. Am new to Mac, so please bear with me. Thanks for your help, Andrew

**Comment by jonafato** [comment]
- When you add a startup item from the Users & Groups preference pane, you can click the plus icon to get a normal file dialog. Then, navigate to where you installed Spectacle (most likely in `/Applications` or `~/Applications`), select Spectacle.app, and click the Add button.

- Spectacle has a checkbox for this in the preferences window (though it was hidden for me at first). If you don't see this checkbox at the bottom of the preferences window, you should see an arrow in the bottom right corner. Clicking the arrow should reveal this option.

**Comment by Andrew-Chapman** [comment]
Thanks a lot, jonafoto, I should have seen that arrow.

Andrew

**Comment by chris-fa** [comment]
Is there any way to do this via CLI? I'm installing spectacle from `brew-cask`, so I thought I might as well automatize it completely.
