### ISSUE TITLE
Not to edge on El Captain

### ISSUE THREAD

**Issue by krusnof** [eczarny/spectacle#478]
With the final El Captain, some apps (and I cannot figure out the logic of why some and not all apps) are not aligning to the edge of the screen in either top, bottom, left or right. Full screen works for most apps I've tried, but not iTerm. But none seems to go to edge in Upper Left, Upper Right, Lower Left etc.
<img width="866" alt="screen shot 2015-10-09 at 3 34 54 pm" src="https://cloud.githubusercontent.com/assets/564745/10407142/bdb2b386-6e9b-11e5-8624-b820f12381a4.png">

**Comment by spaluchiewicz** [comment]
Hi @krusnof, I think this is "Common Issues - Spectacle behaves strangely with Terminal windows".
Try to increase number of rows in Terminal in Window Size section - I did tests with newest version and it works fine.

**Comment by krusnof** [comment]
Didn't work for me. And only started after El Captain, and tried again on Yosemite with no issues. But thanks

**Comment by eczarny** [comment]
@spaluchiewicz, are you using Spectacle with 10.11 as well?

**Comment by spaluchiewicz** [comment]
Yes, and I also did some tests with iTerm (2.1.4) - works fine (both version 1.0.1 and from master).

**Comment by eczarny** [comment]
@krusnof, if you change the font size used by iTerm does the behavior change at all?

**Comment by krusnof** [comment]
@eczarny No, unfortuantely not. Still not sticking to the edges like other apps and prior to 10.11

**Comment by ningt** [comment]
I'm using Spectacle 1.0.1 with EI Captain and it works fine for iTerm 2.1.4. 

iTerm window setting is **30 * 120** and font is **13pt Inconsolata for Powerline** (not the default font)

**Comment by smartygus** [comment]
Just wanted to report I'm having the same issue here with Terminal.app (Spectacle 1.0.1 (509) + El Capitan 10.11.1), but this is just related to the [common problems](https://github.com/eczarny/spectacle#spectacle-behaves-strangely-with-terminal-windows) with Terminal apps mentioned in the readme.
Though strangely I can get the Terminal window to exactly fill my screen if I manually position and expand it with my mouse.

**Comment by vinkla** [comment]
Also having problems with this on El Capitan. Having the exact same setup as @smartygus above.

**Comment by medv** [comment]
Is it just Terminal for you guys? Because my Chrome and Sublime does this too. After a fresh restart it's back to normal. But it looks exactly like the screenshot from original post.

It just seems like windows are maybe 99.8% of the height they are meant to be, but normally snap to the top. So there is always a sliver of space at the bottom (dating back many versions, and on Yosemite). But with El Capitan now the height issue is also paired with the fact that the window now snaps to the bottom, thus ending up looking like the screenshot.

**Comment by smartygus** [comment]
@medv For me it's just with Terminal. I haven't noticed any issues with other apps. Chrome and Finder work fine for me.

**Comment by vinkla** [comment]
@medv @smartygus Same here.

**Comment by aly006** [comment]
+1, having this issue as well in iterm2

**Comment by medv** [comment]
Ok, so it just happened now. Haven't restarted in a few days. Here is Chrome and Sublime side-by-side sized by Spectacle. As you can see there is a gap at the top. If I use the mouse to drag the top edge of the window, I can get it flush to the edge. But if I size that window again by Spectacle, it will go back down again.

Usually I would see this gap below my windows (not always, perhaps after extended use too? can't be sure), but it seems to be shifted to the top now with El Capitan.

<img width="1680" alt="screen shot 2015-12-05 at 10 35 19 am" src="https://cloud.githubusercontent.com/assets/1631737/11605817/128b76f0-9b3c-11e5-825d-d4c20a6013c2.png">

**Comment by docbiz** [comment]
+1. I just want to report that I'm having the same issue as the OP, seemingly only with Terminal, with Spectacle 1.0.1 on a mid-2014 rMBP running El Capitan (10.11.2).

To echo something from earlier: when moving the Terminal window to the left-half of the display with Spectacle, the position of the left-hand edge of the window depends on the font size used with Terminal...

**Comment by jmpace** [comment]
I'm having this issue too, but it's with all windows.

**Comment by margoussian** [comment]
Same issue on El Cap 10.11.3 (mid-2014 rMBP) and Spectacle 1.0.2. Only occurs with iTerm (version 2.1.4) and Terminal.

**Comment by eczarny** [comment]
I'm unable to reproduce this issue with Terminal in 10.11.4.

**Comment by vinkla** [comment]
I'm running 10.11.4 with Spectacle 1.0.6 and I can still reproduce this with the Terminal.

Here is a screencast: https://vink.la/lAOLbmh
