### ISSUE TITLE
Spectacle keeps warning me of a new version, which I have

### ISSUE THREAD

**Issue by WoLpH** [eczarny/spectacle#479]
Not sure what is causing this but I've thoroughly removed and reinstalled Spectacle several times but I keep getting the message to update from 0.8.10 to 1.0.1:

![screen shot 2015-10-12 at 09 30 02](https://cloud.githubusercontent.com/assets/270571/10423178/09b05c96-70c4-11e5-8712-90defec67382.png)

**Comment by eczarny** [comment]
I don't know anything about Spectacle working with Homebrew. Can you confirm that the version of Spectacle you are actually running is 1.0.1? What does Spectacle say about its version?

**Comment by WoLpH** [comment]
The strange thing is, when I manually check the version it says there are
no updates. When I look at what Spectacle says it's actually running
version 1.0.1, but after rebooting I always get this notification.

Just to check, I have done a full search of my system for Spectacle and I
don't have any other versions anywhere.

**Comment by eczarny** [comment]
Do you happen to see more than one Spectacle process running?

**Comment by WoLpH** [comment]
No, as you can see from the `ps aux` output, there is only one spectacle process. Perhaps it's just a bug in the homebrew install. I'll try to investigate more. 

It's just difficult to debug since it only occurs after a reboot.

**Comment by eczarny** [comment]
Ah, yeah. That's tricky. Maybe poke around in the app bundle and make sure everything looks reasonable?

**Comment by WoLpH** [comment]
I've cleared a bunch of caches (`~/Library/Cache/`and `/Library/Cache`) and I haven't seen it since. If it returns I'll reopen the issue but that appears to have solved it. Still not a clue how/why I got the error... makes no sense whatsoever.
