### ISSUE TITLE
Create a shortcut to show the spectacle menu

### ISSUE THREAD

**Issue by karnajani** [eczarny/spectacle#480]
I'm trying to learn the spectacle shortcuts and often have to use my mouse to point to spectacle in the menubar to reference the shortcuts.

Is it possible to have a spectacle shortcut that acts like a mouseclick on the spectacle icon?

**Comment by eczarny** [comment]
I'm not entirely sure I want to dedicate a shortcut to this.

**Comment by karnajani** [comment]
totally understand @eczarny 

only reason i'm bringing it up is because it's initially difficult for me to remember all the spectacle shortcuts. 

Here's an example: 
  1.  I want to move the window to the left third of the screen
  2.  Having looked at the list before, I know there's a shortcut for moving the window to the left third of the screen but I can't recall it off the top of my head.
  3.  I'll try a bunch of guesses as to what the shortcut might be, make a few mistakes (and move the window to a position I totally didn't want), and ultimately use the mouse to click on the spectacle icon and find the correct shortcut.

I know over time this sort of this will improve my memory of all the shortcuts, but in the interim, it basically takes my hands off the keyboard, which kind of goes against why I use spectacle.

This is totally your call, and if you don't like the idea then I'll just have a text file open all the time and cmd+tab to reference it. Feel free to go ahead and close this issue if I haven't convinced you :)

**Comment by eczarny** [comment]
I appreciate you taking the time to open the issue but I don't want to add another shortcut just to help learn the shortcuts.

I'll send you some flashcards. :smile:
