### ISSUE TITLE
Feature Request: Swap all windows between two displays

### ISSUE THREAD

**Issue by unusualbob** [eczarny/spectacle#485]
One thing I get frustrated with is that on some days when I connect my laptop up to my displays at work all the windows on my left display have moved to the right display and vice versa. This is a bug in how OSX handles 'dumb' displays, so it would be very handy to be able to swap them at will, even if its not a keyboard shortcut.

**Comment by rdewolff** [comment]
Interesting feature request :)

**Comment by eczarny** [comment]
Would an app like https://cordlessdog.com/stay/ help here?
