### ISSUE TITLE
[Request] Show/Hide unbound commands in the Spectacle menu

### ISSUE THREAD

**Issue by benweier** [eczarny/spectacle#492]
I only use a subset of the available commands as I don't need to use corners or thirds. I'd like to have a checkbox option in Preferences to remove the unbound commands from the Spectacle menu.

![image](https://cloud.githubusercontent.com/assets/814402/11291015/9591888e-8f87-11e5-9e26-ad9798e8faff.png)

**Comment by eczarny** [comment]
Interesting, but not something I'm likely to support. This functionality would require significant changes that would complicate the app while providing limited benefit. I appreciate you taking the time to request this feature though!

**Comment by benweier** [comment]
I understand. Thanks for the consideration :)
