### ISSUE TITLE
Keys `home` (`fn left-arrow`) and `end` (`fn right-arrow`) not recognized. 

### ISSUE THREAD

**Issue by jaepage** [eczarny/spectacle#493]
Pressing `page-up` (`fn up-arrow`) and `page-down` (`fn down-arrow`) works fine in the app's prefs. 

But pressing `home` (`fn left-arrow`) and `end` (`fn right-arrow`) seems to encounter some kind of timing issue (it variously records as simply `control option` or `control option left/right-arrow`). 

Mac OS X El Capitan (10.11.1)
MacBook Pro 13"

<img width="728" alt="pic 2015-11-24 at 11 29 17" src="https://cloud.githubusercontent.com/assets/4712441/11378172/c2fd12b0-929e-11e5-8ad8-5e6a35bdf521.png">

**Comment by potsky** [comment]
Hi,

same problem with a MacBook Pro (Retina, 15-inch, Late 2013) with 10.10.5. The `fn` key does not work with left or right arrow and with or without any other special key (option, control, etc...).

At the same time, the `fn` key works with the up or down arrow and any other special key.

I use [Size Up](http://www.irradiatedsoftware.com/sizeup/) today on my mac and the `fn` key works with any other key, so this is not a hardware or OS X problem.
