### ISSUE TITLE
Notify Safari window that the monitor on which it is has changed (youtube fullscreen problem)

### ISSUE THREAD

**Issue by masteranza** [eczarny/spectacle#494]
I've noticed a small, but very annoying thing, let me describe it:
I've got a 2 monitor setup (laptop + external) and I'm watching a video on youtube through Safari on my laptop monitor. I decide to watch it fullscreen on external monitor so I use the keyboard shortcut to move the Safari window the second monitor (external) and then I press the fullscreen button in youtube interface.

The result is not what I'd expect - that is: the video maximizes on the laptop screen instead of the external screen on which the Safari window is now.

There's a small workaround around this problem which requires moving the Safari window manually a bit.

**Comment by eczarny** [comment]
I don't think this is necessarily an issue with Spectacle. I've seen this behavior before (with Chrome if I'm remembering correctly) even without using Spectacle to move windows around. My guess is that Safari sometimes has trouble know which display a window is on.
