### ISSUE TITLE
Great app!

### ISSUE THREAD

**Issue by xthepoet** [eczarny/spectacle#495]
No issue. Just installed it and I found it so useful that I put all the window actions into a one pager to post on my wall. Thought I'd share in case it helps others

[Spectacle shortcuts.pdf](https://github.com/eczarny/spectacle/files/49854/Spectacle.shortcuts.pdf)
[Spectacle shortcuts.docx](https://github.com/eczarny/spectacle/files/49853/Spectacle.shortcuts.docx)

**Comment by eczarny** [comment]
Very cool! Thanks for sharing.

I'm going to close this issue out but feel free to open a pull request with a link to the reference sheet in the README.
