### ISSUE TITLE
[BUG] Launch Spectacle on login

### ISSUE THREAD

**Issue by vinkla** [eczarny/spectacle#497]
Spectacle fails to launch at startup on OS X 10.11.1 El Capitan? It seems the Login Items list is reset after I restart my computer? Am I doing something wrong?

**Comment by SpaceK33z** [comment]
Are all your login items cleared after a restart?

**Comment by vinkla** [comment]
@SpaceK33z Yes, I've tried both adding Spectacle to the login items list and checking the box within Spectacle's preferences. Both were cleared after restart.

**Comment by eczarny** [comment]
I'm inclined to close this issue since it sounds like other login items are being removed. Please reopen if Spectacle remains the only login item that gets cleared after restart.
