### ISSUE TITLE
Cannot map anything to the keypad enter key

### ISSUE THREAD

**Issue by diwu1989** [eczarny/spectacle#498]
I want to be able to map `next monitor` to `cmd, alt, keypad-enter` but whenever i press `enter`, it ends the shortcut input process

**Comment by eczarny** [comment]
Good find! Thanks for opening the issue.

**Comment by diwu1989** [comment]
would love to see this fixed, I use both linux and mac, and the problem I use to get spectacleApp functionality on linux uses a text file for shortcut configuration and I'm able to code in that particular combo

this would help me use the same set of combo on both platforms

**Comment by eczarny** [comment]
@diwu1989 I think I may finally have a fix for this. Are you able to test this out at all? My changes are on `master` or I can create a build for you.

**Comment by eczarny** [comment]
I'd appreciate it if somebody could try out this 1.1a build to see if this issue is resolved:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.1a.zip

**Comment by eczarny** [comment]
This may be fixed in Spectacle 1.1 and newer. Closing for now since nobody else has been able to confirm. Please reopen if the issue persists.
