### ISSUE TITLE
Supporting Force touch?

### ISSUE THREAD

**Issue by bdejong** [eczarny/spectacle#499]
Hi!

Been using Spectacle since forever, I love it. I recently got a magic trackpad 2 (dear lord the size of it) and now I'm wondering if I could not define zones on it to position windows on my screen with force touch. 4 corners and the middle of the pad would be perfect.

So, the basic question is: would Spectacle be able to capture random mouse events on windows of different applications?

**Comment by zevlag** [comment]
I haven't tried it with spectacle yet but I love better touch tool. It has tons of options and allows integration with about anything. 

 http://www.boastr.net

-Josh

**Comment by bdejong** [comment]
As what I wanted is not possible in BTT, I already sent an email to the BTT dev. Then again Spectacle is open source and BTT is not...

**Comment by eczarny** [comment]
Interesting enhancement but not something I think fits well into Spectacle's keyboard-driven focus. Thanks for the suggestion though!
