### ISSUE TITLE
[Feature Request] Allow multi-touch gestures as shortcuts

### ISSUE THREAD

**Issue by dillonkrug** [eczarny/spectacle#503]
Not sure how possible this is, but it would be awesome to allow something like

`ctrl`+`option`+`two finger swipe <direction>`

 to move the current window to whichever side of the screen

**Comment by riordan** [comment]
Seconded. I spend a lot of time moving between apps that have overlapping hotkeys to Spectacle. This would be amazingly useful to get them to play together well.

**Comment by eczarny** [comment]
Thanks for the suggestion but this isn't something I would want add to Spectacle right now. I like to keep Spectacle simple and adding the functionality to support this would increase complexity substantially. My focus in 2016 is to make what Spectacle can do more flexible (within the realm of actions triggered by keyboard shortcuts).
