### ISSUE TITLE
Full screen isn't going full screen

### ISSUE THREAD

**Issue by rjjacobson** [eczarny/spectacle#504]
Not sure why but full screen no longer goes full screen. The left hand side is a few millimeters away from the actual left. I have it so the top bar on my mac automatically hides -- maybe this is why?
<img width="1440" alt="screen shot 2015-12-28 at 8 51 29 pm" src="https://cloud.githubusercontent.com/assets/742817/12028389/da5f5a8c-ada4-11e5-97ba-74ed4e197855.png">

**Comment by eczarny** [comment]
Is your Dock hidden on the left edge of the screen? If so OS X always leaves a bit of a gap on the edge where the Dock is hidden.

Personally I work around this by hiding my Dock on the bottom edge of the screen. The gap is a lot less noticeable (you really need to look hard to see it).
