### ISSUE TITLE
How to install Spectacle??

### ISSUE THREAD

**Issue by jaspoia** [eczarny/spectacle#505]
Hi guys, 

simple question: how do I install the app on windows 7?

I'm only used to .exe install files and this here is a riddle to me :-)

Thanks a big bunch, looking forward to using this!

Cheers

PS: I extracted the zip folder and inside there's the spectacle.app folder. But from there I am lost!

**Comment by EduardoRT** [comment]
Spectacle is a mac only app, sorry.
