### ISSUE TITLE
More Verbose Custom Shortcuts

### ISSUE THREAD

**Issue by cpheps** [eczarny/spectacle#507]
It would be nice if the custom key combinations could be more verbose than they are in version 1.0.1. I would like the ability to combine the (Shift, Control, Command, Option) keys with multiple other keys. An example would be Command + Space + n.

**Comment by eczarny** [comment]
Closing out in favor of #442. Please reopen and clarify you suggestion if that issue doesn't capture the spirit of the enhancement.
