### ISSUE TITLE
Suggested Feature: Ability to move app to the next Desktop

### ISSUE THREAD

**Issue by Nemesarial** [eczarny/spectacle#508]
For many, a primary way of organizing their open apps is to make use of different desktops for each screen. It would be great if one could have a spectacle shortcut to move the current window to the next desktop, and then also switch over to that desktop and then re-activate the window so that if the keypress is repeated, the process will continue with the same window.

**Comment by hkim823** [comment]
+1

**Comment by herheque** [comment]
I found your project when searching for a way to move a window (or all windows belonging to an application) to a different "space" in mission control.  I am not sure what Nemesarial means by "keypress is repeated, the process will continue with the same window." - but I think he is suggesting basically the same feature - "move the current window to the next desktop"

**Comment by eczarny** [comment]
This sounds very similar to #15. Is this a duplicate?

**Comment by Nemesarial** [comment]
@eczarny yes it seems to be a duplicate .. I neglected to search for 'spaces' in addition to searching for 'desktops'.
