### ISSUE TITLE
Suggested Feature: drag & drop resize

### ISSUE THREAD

**Issue by geoHeil** [eczarny/spectacle#509]
Moving the window with keyboard shortcuts is great. However sometimes it would be nicer if a simple drag & drop would work as well to snap the window.

**Comment by 54mu3l** [comment]
yeah, that would be nice.
maybe touch-gestures support would be also very nice. to snap the window right away in my workflow.

**Comment by mnewmedia** [comment]
+1

**Comment by jakirkham** [comment]
Yeah, some sort of drag to boundary and adjust to size. Top should make a full window. Left and right half windows on those sides. Corners make quarter windows.

**Comment by triffski** [comment]
+1 for this, especially since BetterTouchTool has stopped working on my machine.

**Comment by mnewmedia** [comment]
I use sticker app for exactly this.. also because of betterTouchTool stopped.. It doesn't work so smooth like btt, but it's ok. Maybe this helps someone =)

**Comment by jakirkham** [comment]
Do you have a link for that?

**Comment by triffski** [comment]
http://www.chompstomp.com/sticker.html

**Comment by jakirkham** [comment]
Thanks.

**Comment by eczarny** [comment]
https://manytricks.com/moom/ may also be a potential alternative. Unfortunately this isn't a feature I would like to support in Spectacle.

**Comment by triffski** [comment]
Unfortunate. Uninstalling.

**Comment by 54mu3l** [comment]
too bad. now the searching for a alternative starts again - since better touch tool doesn't work anymore :(
