### ISSUE TITLE
Maximize vertically

### ISSUE THREAD

**Issue by toonn** [eczarny/spectacle#512]
I would like to be able to maximize windows vertically. This was my original motivation for checking out Spectacle and although it currently lacks this functionality, the other features are great.
I often work with terminal windows and I like the default 80x24 size for small tasks but when writing a larger piece of text for example this is less desirable.
Going fullscreen with the terminal is often not really an option because of other windows, often browser windows, which contain documentation or something you're researching.

**Comment by sscherfke** [comment]
This would also be useful for web browsers, since some sites don’t have a max-width, so lines will become really long and unreadable on larger screens with fullscreen windows.

**Comment by eczarny** [comment]
I thought this is what sometimes happened when you click on the green window button. In Yosemite this now makes the window fullscreen but you can still use the old behavior by holding option and clicking on the same button.

**Comment by toonn** [comment]
Actually the green button used to go fullscreen without going fullscreen, it maximized the window vertically as well as horizontally. Vertical maximization has never been included in the base operating system as far as I know.

**Comment by toonn** [comment]
For those of us who can't live without this any longer, I forgot to mention that I have a stopgap solution.
https://gist.github.com/toonn/ab6ac34480911a9895ce
:blowfish: disclaimer: Consider this fugu prepared by an inexperienced chef, consume at your own risk.

**Comment by albertop9** [comment]
I miss this feature too! - or a shortcut to "center at top". Still a great app though. :)

**Comment by cobrabr** [comment]
+1! I'd also add a request for maximizing both ways (much like Shift-Alt-clicking the green button does).

**Comment by toonn** [comment]
@eczarny why was this issue closed? There's obviously some interest in it. I didn't mind it being labeled enhancement and having a low priority but I would appreciate at least a reason for closing the issue.

**Comment by eczarny** [comment]
@toonn I closed this issue because I'd likely not get around to it and I wouldn't merge in a pull request that did. Sorry for closing with no context.

**Comment by zkendall** [comment]
I want this feature too. I often want a window vertically maximized without snapping to the side positionally or to half-width.
