### ISSUE TITLE
Suggested Feature: "Next Display" should work for full screen windows

### ISSUE THREAD

**Issue by willerup** [eczarny/spectacle#513]
The short cut "Next Display" doesn't work for full screen windows. Assuming it is not a bug I am marking as suggested feature.

Use case: I often have windows in full screen mode on some of my displays. It would be nice to quickly move windows to the right screen instead of 1) take window out of full screen mode, 2) move to new display, 3) put window back in full screen mode. This is especially useful when undocking and redocking because windows get shuffled around in that scenario.

ps: LOVE spectacle!

**Comment by eczarny** [comment]
How does Spectacle behave when you try doing this now?

The expected behavior is that Spectacle is not supposed to allow you to do this. Supporting this functionality does sounds like a good enhancement though.

**Comment by tntimo** [comment]
Same problem; it creates a new dashboard in the current display, which is blacked out. Taking the app out of full screen fixes it, but it is still on the wrong display.

**Comment by testerez** [comment]
+1
On El Captain, when I use `Next display` shortcut, I get a black screen and the current window disappear. Not the best possible experience...
It would be great to also support docking for fullscreen windows. OSX already support it but as far as I know, you have to use the mouse for it: long click on maximise button.

**Comment by eczarny** [comment]
Closing in favor of #468. Spectacle should not manipulate fullscreen windows.

**Comment by zedwick** [comment]
I realise this has been closed in favour of disabling spectacle in fullscreen apps entirely, but I just wanted to add my +1 in the hopes you will reconsider supporting fullscreen windows and moving them between monitors.
