### ISSUE TITLE
Issue with half right/left commands and second screen

### ISSUE THREAD

**Issue by kbariotis** [eczarny/spectacle#515]
I currently have a second screen on a Macbook Pro with El Capitan. Spectacle 1.0.1(509)

Here's a screen recording of the external screen.

![spectacl](https://cloud.githubusercontent.com/assets/605742/12366825/571b9c30-bbe6-11e5-9ca1-bf54eae598e9.gif)

the key strokes are :

* half right command and the Chrome window goes to the main screen
* half right command again and the Chrome window comes to the external screen but centered
* half left command and the Chrome window goes to the main screen
* half top/bottom works fine

the same behaviour goes for the main screen too.

**Comment by eczarny** [comment]
@kbariotis Is this still an issue with Spectacle 1.0.6 and more recent versions of El Capitan?

**Comment by kbariotis** [comment]
no @eczarny. thank you so much for your support.
