### ISSUE TITLE
Spectacle resizing behind dock after unplugging monitors

### ISSUE THREAD

**Issue by mcmccaleb** [eczarny/spectacle#516]
Spectacle Version 1.0.1 (509) 
OSX 10.11.2 

When I unplug my second display and the dock moves back to the primary display on my laptop, Spectacle continues to calculate window sizes as if the dock was not there. This leads to windows being partially covered by the dock when resized.

**Comment by jherman3** [comment]
I'm also experiencing this issue with Spectacle 1.0.1 (509) and OSX 10.11.3

**Comment by eczarny** [comment]
This is a similar issue to #562.

**Comment by eczarny** [comment]
@jherman3 Can you reproduce the issue if you try hiding and showing the Dock?

**Comment by nitinsurana** [comment]
MacOS : 10.14.5
Spectacle : 1.2

Had the same issue. Windows resizing behind dock
Toggling the hide/show for dock in SystemPreferences worked and now it no longer resizes the window behind the dock.

**Comment by sergiofagostinho** [comment]
Same issue on MacOS 10.14.6 (Mojave). It's quite annoying.

**Comment by barczaG** [comment]
+1 
osx 10.15.3
Spectacle 1.2
