### ISSUE TITLE
Spectacle intercepting keys when in Windows on full screen

### ISSUE THREAD

**Issue by jchannon** [eczarny/spectacle#520]
I am using Spectacle, great app, thanks, however when I have Windows running in full screen on VMFusion when I press Ctrl+Alt+Left Spectacle kicks in, not the code selection its supposed to do in my text editor.

Any ideas?

Thanks

**Comment by eczarny** [comment]
Does VMWare Fusion fail to receive other global shortcuts? What about a shortcut for Spotlight? I did find this bit of documentation that leads me to believe this is working as intended:

https://pubs.vmware.com/fusion-7/topic/com.vmware.fusion.help.doc/GUID-A50D0E3C-9549-43B5-AB57-070F805780A3.html

Notably this first sentence:

> By default in VMware Fusion, global keyboard shortcuts that the Mac operating system or third-party applications have registered are sent to the Mac operating system instead of your virtual machine.

**Comment by jchannon** [comment]
I have selected the option Disable for VMFusion and it seems ok however when in Fusion and you press CMD+Space, Spotlight does appear
