### ISSUE TITLE
Move/"Snap" without resize?

### ISSUE THREAD

**Issue by diego898** [eczarny/spectacle#522]
Is it possible to move something like a terminal to the top right/left **without** resizing it? I searched but cant seem to find anything

**Comment by eczarny** [comment]
This is currently not supported, and likely will not be supported as a core feature of Spectacle. I do hope that #427 will make it possible for folks to further customize Spectacle's behavior.

**Comment by diego898** [comment]
Just curious, can you elaborate a bit further? Do you think this feature does not belong in spectacle? Is currently to difficult to implement (but would be open to pull request?)

**Comment by eczarny** [comment]
It isn't difficult to implement. I'm more concerned about the added complexity of even more shortcuts for folks to use. The current UI doesn't handle it well and I want to keep the core set of features Spectacle provides as simple as possible.

**Comment by diego898** [comment]
got it.  thanks!
