### ISSUE TITLE
Does not work with most recent update of Acrobat Reader

### ISSUE THREAD

**Issue by DocileRaptor** [eczarny/spectacle#525]
Key commands fail for some reason.

**Comment by eczarny** [comment]
Spectacle explicitly blacklists this application.

**Comment by DocileRaptor** [comment]
Can we handle whitelisting the application for personal use on our local build? 
I am Developer able.

**Comment by eczarny** [comment]
If you open the application bundle you can modify the property list. You may also need to modify Spectacle's preferences file as well.

**Comment by DocileRaptor** [comment]
I'll give it a go and let you know how it goes.
Where in the bundle are the preferneces file and properylist located / what
are their exact filenames?

**Comment by ch333** [comment]
@SethGoodLuckMartin 

I removed Reader from the Default.plist file and so far so good.

Instructions:
Right click Spectacle in the Applications folder and select "Show Package Contents"
Navigate to the file: "Contents/Resources/Defaults.plist"  
Open the file using TextEdit
Remove the line "<string>com.adobe.Photoshop</string>" and save
Restart Spectacle.

My current reader info:
Adobe Acrobat Reader DC: 15.10.20060.174425
OS X 10.11.4
Spectacle 1.0.3
Macbook Pro Retina 13"

**Comment by SethGoodLuckMartin** [comment]
Lovely. Worked like a charm.
