### ISSUE TITLE
Stop working after sometime with Webstorm and Rubymine IDE from JetBrain

### ISSUE THREAD

**Issue by sainiAman** [eczarny/spectacle#526]
When you open Webstorm or Rubymine is works fine but after sometimes it stop working with only those.

**Comment by jmaciasluque** [comment]
:+1: IntelliJ 

This is pretty annoying.

**Comment by tells** [comment]
I have to restart webstorm to have spectacle work again.

**Comment by mpalmujoki** [comment]
It's sufficient that you swap a couple times between files to reproduce it. Really annoying

**Comment by eczarny** [comment]
I believe this is an issue with these IDEs recently moving to a recent JVM. Here is the issue being tracked by JetBrains:

https://youtrack.jetbrains.com/issue/IDEA-149718

Closing this as a duplicate of #500.
