### ISSUE TITLE
Window upper and lower third resizing issue

### ISSUE THREAD

**Issue by HighDensityAwesome** [eczarny/spectacle#532]
So far a few applications such as OS X notepad and dictionary when resized to upper and lower third using CMD + OPTION + up and CMD + OPTION + down respectively, they slide too far in the set direction by around 1cm on screen (not sure how many pixels). User error, application incompatibility or issue!?

**Comment by eczarny** [comment]
Does the behavior change if you are using a display with different resolutions? The Dictionary app definitely doesn't work when resizing horizontally into thirds. The main window cannot be resized appropriately so the window positions itself somewhat erratically.

If Spectacle cannot move a window to fit into the desired size and position it should abort the window action and prevent it from happening. This section of the README explains the usual problem a bit better:

https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected

**Comment by eczarny** [comment]
I need to investigate further but this does sound like a regression. Given the behavior I witnessed Spectacle does not work as expected when resizing the Dictionary app's main window into horizontal thirds.

**Comment by eczarny** [comment]
@HighDensityAwesome is the issue you are seeing described in #533?

**Comment by eczarny** [comment]
I pushed a fix for #533 to master that may address this issue. Once we confirm the fix for that issue I'll release Spectacle 1.0.3; it would be awesome if you could upgrade once this version has been released and try reproducing this issue.

**Comment by HighDensityAwesome** [comment]
Yes @eczarny that is the exact issue as described in #533 . Absolutely, I would love to test out the new fix, thank you so much for your time and response! Awesome project, I plan to follow it as it grows and becomes even more amazing!!

**Comment by eczarny** [comment]
I would love some additional help testing the fix. I created a beta release that should resolve the issue, you can download it here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.3b.zip

**Comment by HighDensityAwesome** [comment]
Downloaded and installed. So far I have found the previous issues to be fixed! Thank you, great work! Can't wait to continue testing!!!!
