### ISSUE TITLE
Some Windows slide downwards after being moved to (Upper|Lower)(Right|Left)

### ISSUE THREAD

**Issue by themightyoarfish** [eczarny/spectacle#533]
OSX Version: 10.10.5
Spectacle Version: 1.0.2 (536)

I have seen this happen only with Telegram, but since the most recent update, when I press e.g. `⌃` `⌘` `←`,  the window will move to the upper left corner, but then slide downwards to stop at the middle left. In the attached gif, I first pressed `⌃` `⌘` `←`, then `⌃` `⇧` `⌘` `←` and repeated both. You can see, the window moves to the corner, then slides down and then moves to the lower corner.

![spectacle_bug](https://cloud.githubusercontent.com/assets/11613312/13032962/7e8dbaa0-d306-11e5-9b4b-002c2b2eff6c.gif)

**Comment by Aqueum** [comment]
OSX Version 10.11.3
Spectacle Version 1.0.2
15" Retina Macbook Pro late 2013 with 27" Thunderbolt display.

Since updating, I have had the same problem with a number of apps (Skype, iCal, and Toggl Desktop) but not with others (Finder, Mail, Chrome & Safari for example are fine).  This happens with any window orientation that is not full height, and only happens on my main retina screen not on the Thunderbolt Display

OmniFocus is also misbehaving (the edge of the window is off-screen).  

Where can I download 1.0.1?  It was working beautifully.  I'd live to revert until this issue is fixed.

**Comment by eczarny** [comment]
@Aqueum you can download Spectacle 1.0.1 here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.1.zip

Keep in mind that this version of Spectacle is bundled with a version of Sparkle with a known security vulnerability.

**Comment by Aqueum** [comment]
Thanks Eric - good point, probably best avoiding the vulnerable Sparkle...  I presume all prior versions of Spectacle were vulnerable?

Do you have a feel for when the downward slide issue might be resolved?

**Comment by eczarny** [comment]
I'm currently looking at it. Hoping to have a fix ready tomorrow.

**Comment by Aqueum** [comment]
Wonderful, thanks Eric

**Comment by eczarny** [comment]
@Aqueum I pushed a potential fix to master. Once I am able to get confirmation from others that the issue is resolved I'll release 1.0.3.

Folks able to reliably reproduce this issue it would be great to test the fix. Building and running Spectacle from master should be enough to try the fix out.

**Comment by Aqueum** [comment]
I tried to build and run but had problems with missing Podfile.lock & Manifest.lock...

**Comment by eczarny** [comment]
What error did CocoaPods provide when running `pod install`?

**Comment by Aqueum** [comment]
![screen shot 2016-02-16 at 02 14 14](https://cloud.githubusercontent.com/assets/6342315/13061715/14b797b0-d453-11e5-95a0-46f7f54c30d4.png)

**Comment by Aqueum** [comment]
pod install now fine, but I'm now getting 
`ld: library not found for -lPods`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by tablador** [comment]
Just wanted to say I noticed this too.  Specifically VLC is a culprit.Seems to be something with the new version. I'll look into build instructions, etc. as soon as I have some time.

**Comment by tablador** [comment]
Built branch/master and the problem seems to have gone away.

**Comment by eczarny** [comment]
I would love some additional help testing the fix. I created a beta release that should resolve the issue, you can download it here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.3b.zip

**Comment by danthegoodman** [comment]
I can confirm that the beta fixes this issue for me. I was experiencing it with Spotify on Yosemite. Thank you!

**Comment by Aqueum** [comment]
I confirm 1.0.3b has also resolved my issues with Skype, iCal, OmniFocus and Toggl Desktop.  Thanks for the rapid fix Eric.

**Comment by sharq88** [comment]
Spectacle 1.0.2, 1.0.3b, on Yosemite, mac pro retina 2015 + thunderbolt display
https://youtu.be/y1G_kiNzw38

**Comment by eczarny** [comment]
@sharq88 That's really strange. I wonder if it has anything to do with your resolution? Does it work on other displays?

**Comment by eczarny** [comment]
@sharq88 Could you also confirm that Spectacle behaved correctly in 1.0.1? You can download it here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.1.zip

**Comment by sharq88** [comment]
Hi, yes it was fine before, and indeed I can confirm now the 1.0.3b works fine! Yeyy! The problem was I had multiple instances of the application running. (I didn't know I can do that!) :) So after close all, and run 1.0.3b, works perfectly. THANK YOU!!

**Comment by themightyoarfish** [comment]
Can confirm, 1.0.3b fixes the problem.
