### ISSUE TITLE
Left/Right half issue

### ISSUE THREAD

**Issue by jkdufair** [eczarny/spectacle#535]
After upgrading to 1.0.2, using the Left/Right half issue with on retina MBP causes windows to be adjusted to just off the left/right edges of the display. My dock is on the left side of my monitor. This does not happen to windows on my external display (an iMac in Target Display Mode). It does happen regardless of whether the external display is plugged in or not.
![screen shot 2016-02-15 at 5 10 58 pm](https://cloud.githubusercontent.com/assets/623494/13061694/7b028648-d407-11e5-918c-8cb4f1d241a2.png)
<img width="1440" alt="screen shot 2016-02-15 at 5 11 13 pm" src="https://cloud.githubusercontent.com/assets/623494/13061693/7b01465c-d407-11e5-85b5-a46f85676042.png">

**Comment by eczarny** [comment]
I would love some additional help testing the fix. I created a beta release that should resolve the issue, you can download it here:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.3b.zip

**Comment by jkdufair** [comment]
Seems to be working great. Thank you!
