### ISSUE TITLE
Slack client moves partially off screen in OSX El Capitan

### ISSUE THREAD

**Issue by dsaint-pierre-sonian** [eczarny/spectacle#537]
Spectacle 1.0.2
OS 10.11.3
No console output of note.

This behavior began after upgrading from Yosemite yesterday.

![Screenshot]
(https://www.evernote.com/l/AS6DYD1VVpRMMbVc1Mc0gfvn86jKWXwHJhEB/image.png)

Note the red x is not visible. This is an issue for me because Slack has dots next to org icons indicating new messages if multiple orgs are configured. Hope this is a quick fix. Thanks!

**Comment by dcaixinha** [comment]
This is also happening to me! And FIY, it also happens when using Spectacle's commands in the iTunes window!

**Comment by eczarny** [comment]
Does this happen with Spectacle 1.0.1?

**Comment by dcaixinha** [comment]
I don't know. How can I rollback to 1.0.1?

**Comment by eczarny** [comment]
Does https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.3b.zip fix the issue for you at all?

**Comment by dsaint-pierre-sonian** [comment]
@eczarny +1. Resolved the issue for me.

**Comment by eczarny** [comment]
:+1:

**Comment by moonwave99** [comment]
I was experiencing the same problem on El Capitan (with VLC only), 1.0.3b worked fine. Thanks!
