### ISSUE TITLE
Gap down left edge

### ISSUE THREAD

**Issue by mattburns** [eczarny/spectacle#540]
I always get a gap of a few pixels on my screen. It doesn't matter what application I'm resizing, but if I snap fullsize or to the left, there is always a gap:
![image](https://cloud.githubusercontent.com/assets/1316126/13183173/7364e9ac-d72d-11e5-866a-5badd7daa47b.png)

OSX 10.11
Dell P2415Q (a 4K display running at 3840x2160, but with scaling to "look like" 2304x1296)

If I select a different scaled resolution, then snap the window fullsize, the problem is the same:
![image](https://cloud.githubusercontent.com/assets/1316126/13183284/120cd010-d72e-11e5-875d-691108eccac2.png)

If I alt-click and go to native resolution, I still get the same problem. I'm including this just because it's silly!

![image](https://cloud.githubusercontent.com/assets/1316126/13183337/58c16e3a-d72e-11e5-82ce-0912c6fc26aa.png)

**Comment by eczarny** [comment]
Is that where you Dock is hidden? If so that would explain the gap. OS X enforces it.

**Comment by mattburns** [comment]
@eczarny yep, that was it, sorry
