### ISSUE TITLE
Upper and lower corners able to be made into thirds.

### ISSUE THREAD

**Issue by zdkroot** [eczarny/spectacle#541]
I have lately taken to having a large editor window on the right side taking up 2/3rds of the screen, and two windows on the left split horizontally. It would be great if the upper/lower keybinding could be pressed multiple times to resize the window just like the left/right half bindings.

I can only achieve this and I resize the window manually from there:
![screen shot 2016-02-22 at 11 39 46 2](https://cloud.githubusercontent.com/assets/638336/13225009/0f7103f8-d959-11e5-84e2-652781359d5a.png)

The left/right direction of the respective corner binding could take multiple presses to adjust the width from 1/3 - 1/2 - 2/3, and the up/down direction could be used to adjust the height in the same increments.

Thanks for the consideration and excellent tool! It's a core part of my workflow.

**Comment by qpowell** [comment]
+1 This would be a great feature to have. Spectacle actually makes managing windows in OSX bearable :)

**Comment by DarthPumpkin** [comment]
I agree, this would be very useful especially for high-resolution displays where 1/9 of your screen is enough for your terminal or finder window. As an alternative key binding, the numbers `1` to `9` could be used, e.g. &#8963;&#8984;1 for upper-left, &#8963;&#8984;2 for upper-center, &#8963;&#8984;4 for center-left, etc.

**Comment by lowski** [comment]
+1 for that.

**Comment by josiasds** [comment]
Hi everyone! I submitted a PR (#561) trying to address this issue.

Hopefully, everything is ok and we'll get it merged soon!

:beers:

**Comment by eczarny** [comment]
Thank you @josiasds for the contribution!
