### ISSUE TITLE
Finder windows do not shrink to 1/3 size vertically

### ISSUE THREAD

**Issue by kymcarlsson** [eczarny/spectacle#542]
Hi, I'm experiencing the same as in #531 (fixed for terminal), but now with resizing Finder windows to 1/3 size vertically.

OS X: El Capitan
Spectacle: 1.0.3

**Comment by eczarny** [comment]
Can you provide a screenshot? What is your resolution?

**Comment by kymcarlsson** [comment]
Quick screencast: https://cloudup.com/cVkIFU9uZdQ
MacBook Pro: Retina

**Comment by eczarny** [comment]
That's usually how Spectacle behaves if the window restricts its dimensions and it can be resized to fit into a 1/3:

https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected

If you remove the tab bar does it work as expected?

**Comment by kymcarlsson** [comment]
> If you remove the tab bar does it work as expected?
Yes.. 
Terminal 1/3 vertical sizing works with a tab bar.

**Comment by kymcarlsson** [comment]
> https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected

If I disable/close Spectacle, I am able to resize a Finder window to 1/3 vertically.
