### ISSUE TITLE
Automatic updating sends logging data to Google Analytics

### ISSUE THREAD

**Issue by driverdan** [eczarny/spectacle#543]
When a new update is available Spectacle sends data to Google Analytics (ssl-google-analytics.l.google.com). This is not disclosed and there is no preference to disable tracking.

It also doesn't seem to be in the source code in this repo so it's either part of a 3rd party library or is compiled into releases without disclosure.

Tracking should be removed or disabled by default.

**Comment by eczarny** [comment]
I have always used Google Analytics to get an idea how frequently Spectacle is downloaded and upgraded:

https://github.com/eczarny/spectacle/blob/gh-pages/updates/changes/1.0.3.html#L9-L17

spectacleapp.com also does this:

https://github.com/eczarny/spectacle/blob/gh-pages/index.html#L51

I can add a section to the README explaining how I use Google Analytics. Would that be helpful?
