### ISSUE TITLE
Automatic resize lower half windows at dock height change +  Sizing XQuartz windows

### ISSUE THREAD

**Issue by ElStuiterbal** [eczarny/spectacle#546]
Dear eczarny,

First of all, thank you so much for this great application. I enjoy it everyday :)
However, I have two requests:
- Since my dock (located at the bottom of my screen) is completely filled, as soon as I minimise a window the height of my dock decreases and windows in the lower half no longer touch the dock. I would like the lower half windows to automatically resize themselves to touch the dock again.
- Spectacle can't resize windows from XQuartz. I would really love to be able to do this.

If I can help in any way, let me know.

Currently I am using Spectacle 1.0.3 on OS X 10.10.5

**Comment by eczarny** [comment]
Sorry, this isn't something I would expect Spectacle to support.

I'm rather certain that Spectacle will never be able to work with XQuartz. If I remember correctly XQuartz Windows don't support OS X's Accessibility APIs.

**Comment by ElStuiterbal** [comment]
Thank you for your reply. How about my first bullet point?

**Comment by eczarny** [comment]
Ah, I apologize for not making it clear in my initial reply. The functionality you described in your first bullet point isn't something I would want Spectacle to support. The work involved would be complex and likely wouldn't address a common need for most folks.

**Comment by ElStuiterbal** [comment]
I get it. Thanks for your reply and keep up the great work with Spectacle!
