### ISSUE TITLE
keyboard shortcuts fail with Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by fairlit** [eczarny/spectacle#551]
Keyboard shortcuts do not affect the main document window of Adobe Reader (though the equivalent Spectacle status menu items work fine). The keyboard shortcuts work with all other apps.

Adobe Acrobat Reader DC 2015.010.20059
OS X 10.11
Spectacle 1.0.3
Macbook Pro Retina 15"

Great app btw.

**Comment by eczarny** [comment]
Interesting. Historically these apps have not worked well with Spectacle. I'm curious if Adobe has fixed the prior issues. Do all window actions behave as expected?

**Comment by eczarny** [comment]
The reason keyboard shortcuts don't work is that Spectacle explicitly blacklists certain apps known to behave strangely. You can try removing this app from the blacklist by modifying the plist file in the app bundle.

**Comment by ch333** [comment]
I removed Reader from the Default.plist file and so far so good.

Instructions:
Right click Spectacle in the Applications folder and select "Show Package Contents"
Navigate to the file: "Contents/Resources/Defaults.plist"  
Open the file using TextEdit
Remove the line "<string>com.adobe.Photoshop</string>" and save
Restart Spectacle.

My current reader info:
Adobe Acrobat Reader DC: 15.10.20060.174425
OS X 10.11.4
Spectacle 1.0.3
Macbook Pro Retina 13"

**Comment by eczarny** [comment]
I went ahead and removed Adobe Reader from the application blacklist.
