### ISSUE TITLE
Spectacle gone from Accessiblity setting and therefore does not work

### ISSUE THREAD

**Issue by lovelyhomie** [eczarny/spectacle#552]
Hello there

I love Spectacle. It is a great App!

But it does not work anymore on my system since last week.

Problem is, that the app is not "registered" on the Accessibility part inside the System Settings. It's simple not there.

Restarting the app does not do anything either.

What can I do?

I am using OS X 10.9.5

**Comment by eczarny** [comment]
Does rebooting help? This seems like an OS X issue.
