### ISSUE TITLE
Download link changes with each new version

### ISSUE THREAD

**Issue by iancdavidson** [eczarny/spectacle#553]
Would it be possible to remove the version number from the download hyperlink? This would allow me to use batch scripts to download and install the most current version.

**Comment by eczarny** [comment]
This isn't something I want to do. I very much prefer having a unique, yet predictable, URL for each release. I'd suggest parsing the appcast to determine the latest version or rely on Sparkle to update Spectacle after installation.

**Comment by iancdavidson** [comment]
I'm all for that.  What about a redirect URL which always points to the current unique but predictable stable release?

**Comment by eczarny** [comment]
Reopening so we can track adding a canonical download URL with redirection.
