### ISSUE TITLE
After using Right half there is a gap on the right side on screen sometimes 

### ISSUE THREAD

**Issue by Bilalh** [eczarny/spectacle#554]
Left half still works correctly when this occurs.   This  oddity only happens for a short period of time then Right side starts to work correctly again.

Here is a gif showing that Left half still works correctly and Right half leaving a gap on the right.

![Comparing Left half and Right half](https://cloud.githubusercontent.com/assets/171602/13730461/dbccbab6-e947-11e5-9629-5ad0f1b94092.gif)

Spectacle  Version 1.0.3 (552)

OS X  10.11.3 (15D21)
MacBook Pro (Retina, Mid 2012)
 
This has happened  with at lest  TextEdit  and Textmate and Safari.

**Comment by eczarny** [comment]
Do you happen to have multiple monitors?

**Comment by Bilalh** [comment]
I do have an extra monitor, but this happened when I was only using my laptop screen.

**Comment by eczarny** [comment]
@Bilalh Is this happening with Spectacle 1.0.6?

**Comment by Bilalh** [comment]
I have not seen it happen with 1.0.6.
