### ISSUE TITLE
Feature: Custom Window Sizes

### ISSUE THREAD

**Issue by chucksense** [eczarny/spectacle#557]
Instead of maximizing fully, I like to leave ~75px of space on the right of windows exposed desktop for a "quick dragging" temporary work space.  I'd like to be able to create a new behavior for this while retaining the normal maximize behavior (as I do occasionally go "full", e.g., when screen sharing/presenting).

**Comment by chucksense** [comment]
I found #427—guessing this will be rolled into that so consider this a plug for this capability as part of that.

**Comment by eczarny** [comment]
Agreed. This sounds like a good candidate for the functionality described in #427. I started working on this a month ago but haven't had much time to spend on it.
