### ISSUE TITLE
Resize to 2/3 option

### ISSUE THREAD

**Issue by garethrees** [eczarny/spectacle#558]
I have a 2560 x 1440 display, so often like to use 1/3 for web browser and 2/3 for terminal. Creating the 2/3 size is currently a manual process.

![screen shot 2016-03-18 at 09 49 49](https://cloud.githubusercontent.com/assets/282788/13874276/cb2ebe3e-ecee-11e5-83df-e6063facfaff.png)

Looks like 2/3 was also mentioned in https://github.com/eczarny/spectacle/issues/397.

Thanks! :beers:

**Comment by zachwood** [comment]
This already works for me by repeating the keyboard commands. To get that arrangement you'd focus on Chrome and enter whatever your commands are for 
`<Left Half> <Left Half> <Left Half>` then focus the Terminal and do `<Right Half> <Right Half>`.

**Comment by garethrees** [comment]
So you can! That's not what I'd have expected.

**Comment by MiroHibler** [comment]
Yeah, it would be more intuitive tho to have shortcuts, for example "Next 2/3" and "Previous 2/3" or something like that...
