### ISSUE TITLE
Dock and Finder freezing

### ISSUE THREAD

**Issue by wfendler** [eczarny/spectacle#559]
Is anyone else experiencing a frozen Dock and/or Finder while running this? I've disabled applications one by one and I think I've identified Spectacle as the culprit. I've had it happen on two machines and Spectacle is the last thing I've added to both of them.

Cmd+tab stops working. The dock won't show and all OSX features like expose, dashboard, mission control, all stop working.

Apologies in advance if I find out this wasn't Spectacle.

**Comment by danechitoaie** [comment]
Not sure if it's the same issue but I had Chrome freezing a few times. As in scroll still works but not link is clickable anymore and the cursor is always a pointer like there is no link in the browser and like everything is just an image. All it takes to fix Chrome is to just disable Spectacle and enable it back and then it works again (until next time - which is kind of random)

**Comment by danechitoaie** [comment]
Just had finder freezing. And the "file open" dialog in Chrome. It was all weird with graphic glitches. Like only the border was visible and the contents were all white. Closing Spectacle fixes the issue.

Not sure what's going on. I had to stop using it due to these issues that keep happening. Other than this great program, I like it more than the other ones that have similar functionality and I hope this can be fixed.

**Comment by eczarny** [comment]
I honestly have no idea what could be going on here. Is there any telling information in the logs? You can check by using the Console app.

**Comment by danechitoaie** [comment]
More updates on this. After multiple days of using it as I didn't want to just give up without a clear understanding of what's going on I was able to "unfreeze" Chrome by just clicking on the 1Password Icon so now I'm kind of inclined to believe that in fact  Password plugin was the one making Chrome to freeze and it was just a coincidence that I started having this issues soon after installing Spectacle.

**Comment by eczarny** [comment]
In that case I'm going to go ahead and close this issue. Feel free to reopen if you continue running into problems.
