### ISSUE TITLE
Feature request: Ability to increase and decrease the width of the window without affecting the height.

### ISSUE THREAD

**Issue by gdance** [eczarny/spectacle#560]
Hello,

I think it would be great if there was an option to increase/decrease the width of the window without affecting the height. I am trying to test breakpoints in my web development so it would be nice to have a keyboard shortcut to easily change the width of the window but not the height.

Thanks,
Gary

**Comment by diwu1989** [comment]
likewise, an option to increase/decrease the height of the window without affecting the width

**Comment by eczarny** [comment]
Closing in favor of #590.
