### ISSUE TITLE
Gap at top with Finder windows and hidden menu bar

### ISSUE THREAD

**Issue by BrendanEMahon** [eczarny/spectacle#562]
When you select to automatically hide and show menu bar in system preferences, Finder windows are leaving a gap where the menu bar would be.  The problem seems to be limited to finder windows.  WIndows for other applications do not leave the gap.
![spectacle_hidden_menu](https://cloud.githubusercontent.com/assets/6766504/14224425/1752a254-f86a-11e5-8643-ef6073cab828.png)

Edit: The issue seems to be intermittent.  Currently all windows, including finder windows, are resizing as intended.

**Comment by eczarny** [comment]
Interestingly if I enable the option to hide the menu bar windows will consume the space it once occupied. Once the menu bar is shown for the first time windows will no longer consume that space. This feels like an issue with the way OS X computes the visible frame of the screen.
