### ISSUE TITLE
How does Spectacle know when it has been granted Accessibility Permissions to it?

### ISSUE THREAD

**Issue by eeschimosu** [eczarny/spectacle#564]
I'm developing an app and have a hard time finding out how to notify my app that it has the right permissions and restart it. So here is a question:

How does Spectacle know when it has been granted Accessibility Permissions in the System Preferences?

**Comment by eczarny** [comment]
Look here:

https://github.com/eczarny/spectacle/blob/master/Spectacle/Sources/SpectacleAppDelegate.m#L123

The Accessibility APIs expose a function to do this check for you.

**Comment by eeschimosu** [comment]
Thanks!
