### ISSUE TITLE
not working over Synergy

### ISSUE THREAD

**Issue by xiaokunx** [eczarny/spectacle#565]
Using the default setting, Spectacle works perfectly on my MacbookproRetina. For example the Cmd+Alt+left/right arrow, and the Cmd+Alt+Shift+left/right move windows to left/right, and upper left/right, as intended. However, it does not work on a keyboard that's connected to Mac via Synergy.

Synergy 1.7.4 setup: Host Ubuntu 12.04, Mac OsX 10.11.4

Keyboard connected to Ubuntu host via USB: http://au.ttesports.com/Keyboard/143/POSEIDON_ZX/productPage.htm?a=a&g=ftr#.VxfUvOduFhE

Synergy key mapping: (Mac - Ubuntu):
Shift -> Shift
Ctrl -> Ctrl
Alt -> Super
Meta -> Meta
Super -> Alt

Anyone has similar issue? I wonder if it is a keyboard issue, or a Synergy setting issue. I suspect the former since this keyboard's hardware is not "standard" such that it had issues when physically connected to the mac via usb.

Thanks!

**Comment by eczarny** [comment]
Do other common keyboard shortcuts work?

**Comment by xiaokunx** [comment]
Yes, for example, via Synergy I could do Cmd-Space (Alt-Space on real keyboard) to open spotlight search, Cmd-Tab (Alt-Tab on keyboard) to change program, and Ctrl-A / Ctrl-E to move cursor in the terminal or iTerm2 window.
