### ISSUE TITLE
Next Display wrong direction when primary monitor changed

### ISSUE THREAD

**Issue by unclhos** [eczarny/spectacle#566]
When you change the "primary monitor" (white bar on arrangement displays) to an external monitor, the direction of "next/previous" monitor is incorrect. 

Spectacle 1.0.3
OSX 10.11.4

**Comment by eczarny** [comment]
Closing as a duplicate of #298.

**Comment by unclhos** [comment]
I think this is different. On my system it works correctly when primary is set to my MBP. But incorrectly when I change "primary" to one of the externals. But up to you.
