### ISSUE TITLE
New 1.0.4 update overwrites preferences

### ISSUE THREAD

**Issue by ldionne** [eczarny/spectacle#568]
After updating Spectacle to 1.0.4, I observed that my preferences had been changed to (I believe) the default values. Is this possible, or am I making things up? If so, it would be nice if the update could be fixed so it doesn't do that to other people. Putting the preferences back is annoying, especially if you don't remember exactly what shortcuts were used for what action.

**Comment by eczarny** [comment]
Sorry to hear about that! Spectacle should definitely not be resetting your shortcuts. I even tested this earlier today by verifying that shortcuts created in 0.8.6 worked in 1.0.4. I'll spend some time this week to try and reproduce the issue.

**Comment by ldionne** [comment]
No biggie. Do you know where Spectacle's preferences are stored? I have a backup that predates the update, so I could just fetch my preferences from there I guess.

**Comment by eczarny** [comment]
You should find Spectacle's preferences in a file named `com.divisiblebyzero.Spectacle.plist` In`~/Library/Preferences`.

**Comment by ldionne** [comment]
Thanks, now it feels like home again!
