### ISSUE TITLE
New 1.0.4 update top / bottom half not working on Word windows

### ISSUE THREAD

**Issue by ShaulT** [eczarny/spectacle#569]
Hello, I updated to the 1.0.4 version and the top half / bottom half command stopped working for Word files (it still works for browser windows / PDFs, etc). With Word files, it brings the window to the top (or bottom) half position for a moment but then flickers and reverts to what it was before.

Thanks for your trouble.

**Comment by eczarny** [comment]
Does rebooting help?

**Comment by ShaulT** [comment]
Unfortunately not. And the issue still seems to affect only the top half / bottom half command, and only Word windows.

**Comment by michaeldjeffrey** [comment]
This seems like the most similar issue to mine.

None of my half commands are working, for any windows. 
Thirds still work.
Centering and full screen still work.
Screen switching still works.

I'm still running osx 10.10.5

**Comment by eczarny** [comment]
@michaeldjeffrey Are you seeing the same problems when you try moving windows to corners?

**Comment by eczarny** [comment]
@ShaulT What version of Word are you using?

**Comment by ShaulT** [comment]
No, concerns are fine for me.

Word for Mac 2011. Version 14.6.3.

Running OS X 10.11.4.

**Comment by ShaulT** [comment]
*corners*

**Comment by eczarny** [comment]
I have no trouble with Word 15.21.1. This issue sounds very similar to #447 so I don't think it's specific to Spectacle 1.0.4.

**Comment by michaeldjeffrey** [comment]
Corners work fine for me. 
It seems a second restart has brought back half functionality.
Switching screens is hit or miss.
Spotify, and Notes are the only apps I've found that switch screens then immediately switch back.
Flowdock, Sublime Text, iTerm work fine.

**Comment by eczarny** [comment]
@michaeldjeffrey Spectacle 1.0.5 should address your issues with Spotify and Notes.

**Comment by eczarny** [comment]
Can folks see if this build helps at all?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6b.zip

**Comment by michaeldjeffrey** [comment]
1.0.5 Spotify still had issues when switching screens. Weirdly, it would work if on the first window it was attached to the left or right half. But any other configuration and it would automatically switch back.

1.0.6 this issue is resolved.

**Comment by ShaulT** [comment]
Issue solved - thanks!
