### ISSUE TITLE
Mail.app won't go half screen after Spectacle 1.04 update

### ISSUE THREAD

**Issue by jjabrams** [eczarny/spectacle#570]
Previously this worked fine.  Using hotkey to go half screen (left or right) causes the mail.app to go half screen for 0.5 second and then revert instantly back to its last position. 

Only occurs when Mail is showing the Mailbox list (I have multiple accounts so have that on display all time).

**Comment by eczarny** [comment]
Have you tried rebooting? That sometimes resolves transient issues.

In my experience Mail actively restricts the size of its main window. Showing the mailbox list has exacerbated this kind of issue in the past.

**Comment by seehadley** [comment]
Same thing is happening to me with Todoist and Sketch. Seems to be working with Chrome.

**Comment by eczarny** [comment]
Does downgrading back to 1.0.3 help at all? I'm still a bit unsure why this wouldn't work now but did work before.

Displaying the mailboxes does prevent Spectacle from resizing Mail's main window to 1/3 of some displays. A video demonstrating the issue would be very helpful.

**Comment by diwu1989** [comment]
Got a similar problem on slack chrome app

**Comment by BrendanEMahon** [comment]
Having the same issue with Mail.app since the upgrade.  Rebooting didn't help.   The window transiently resizes and moves, but then jumps back to its original configuration.  Oddly, it seems to work when resizing to the top or bottom half or full screen.  It doesn't work for the left or right half or any of the corners.  I've demonstrated this here https://youtu.be/uZ3U076WuE0

**Comment by eczarny** [comment]
@BrendanEMahon If you close the "Mailboxes" column does the problem continue?

**Comment by eczarny** [comment]
Can folks see if this build helps at all?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6b.zip

**Comment by jjabrams** [comment]
Hi! Thanks to Brendan for making that video - its the same issue as mine.  Messages wasn't affected on mine.

The new build 1.06b seems to fix the Mail.app problem - many many thanks for looking into this!

**Comment by BrendanEMahon** [comment]
Sounds like you knew what was going on and fixed the problem with the update, but I just tested it without the sidebar present (mailboxes column) and was able to resize without issue.

**Comment by seehadley** [comment]
1.0.6 fixed it for me too. Thanks @eczarny !
