### ISSUE TITLE
New 1.0.4 method of switching between display causes shrinking Terminal windows

### ISSUE THREAD

**Issue by quinncomendant** [eczarny/spectacle#571]
If I have a Terminal window in the bottom-left corner of my screen, then repeatedly move this window to my external display and back, the window slowly shrinks in size. The window does not return to the size it was on the previous window, but one slightly smaller. This doesn't appear to occur with other windows, just the Terminal.

**Comment by eczarny** [comment]
Have you tried Spectacle 1.0.5?

**Comment by quinncomendant** [comment]
I just noticed v1.0.5 is available. Its change-display function works same as versions before 1.0.4 (which I prefer, actually). Was there other serious issues with the new change-display function?

**Comment by eczarny** [comment]
It would sometimes break and folks were reporting they couldn't move any windows between displays. Decided it was best to just fallback to the 1.0.3 behavior for now.
