### ISSUE TITLE
1.0.5 - Slack will not snap to left or right half

### ISSUE THREAD

**Issue by Waveharp** [eczarny/spectacle#572]
The latest update seems to work for everything except moving a Slack window left or right. Slack will snap to the intended position and then immediately snap back to its original position. This occurs when using the shortcuts for left half / right half as well as the four quarters (top right, etc.). The other shortcuts seem to work as intended.

**Comment by eczarny** [comment]
Can you manually resize Slack to fit half of your display? Does it prevent you from making its windows small enough to fit?

**Comment by coroner4817** [comment]
Same here for WeChat.

**Comment by geary** [comment]
This bug affects every app I've tried on my system. They all snap to the other monitor and then immediately snap back. I built Spectacle from the d493fe90eca26b5191d945951c73289b025ed612 commit ("The 1.0.4 release of Spectacle is ready", just before "Move windows to the next or previous display less intelligently") and it works OK.

**Comment by ftvs** [comment]
Spectacle is an amazing app.

As for this issue, in the meantime I am using https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.4.zip. Same issue for Chrome 50.0.2661.94. Late 2011 13-inch MacBook Pro on Yosemite.

**Comment by Waveharp** [comment]
I can resize Slack to less than half of my display. The half/quarter screen shortcuts were working for Slack yesterday - this problem was brought about 1.0.5.

Thanks for looking into this! And for the great app.

**Comment by diwu1989** [comment]
yep also seeing this...

**Comment by eczarny** [comment]
Can folks see if this build helps at all?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6b.zip

**Comment by docbiz** [comment]
I was having a similar problem with Preview not snapping to the left- or right-hand halves, but 1.0.6b fixes it. Thanks!

**Comment by eczarny** [comment]
This (the Slack issue specifically) may or may not be fixed in 1.0.6. I just released it.

**Comment by eczarny** [comment]
@Waveharp does 1.0.6 resolve your issue?

**Comment by geary** [comment]
1.0.6 is working nicely here, including Slack. Thanks for the quick fix!

**Comment by Waveharp** [comment]
@eczarny Yes, 1.0.6 resolved my issue. Thanks so much for getting the fix out so quickly!

**Comment by AndrewRayCode** [comment]
This appears to be an issue again. I'm not sure if Slack is blocking keypresses from bubbling out. I'm using Spectacle `Version 1.2 (672)` and Slack `Version 4.11.3`
