### ISSUE TITLE
1.0.5 - Xcode 7.3 can not snap to any directions.

### ISSUE THREAD

**Issue by ImsungChoi** [eczarny/spectacle#573]
I update Xcode to 7.3 and Xcode can't snap to any directions. 
Actually, Xcode snap to a direction and it restore immediatley.

**Comment by eczarny** [comment]
Xcode 7.3 restricts the width of its main window. You can verify this behavior by trying to manually resize the main window to fit half of the display.

Top and bottom halves seem to work for me on my 15-inch MacBook Pro. That's about all that works.
