### ISSUE TITLE
Unable to move applications between displays

### ISSUE THREAD

**Issue by qinty** [eczarny/spectacle#575]
I have a dual display setup for my workstation, with the dock at the left hand side of my left display.
When trying to move (using Control+Option+Command+left arrow) a window that is maximized on the right display (the one that doesn't have the dock) to the left display, it snaps back to the right display.

If I manually resize the window to account for the space taken by the dock, I am able to move it.

**Comment by timiyay** [comment]
+1 This started happening after upgrading to v1.0.5 (590) this morning.

**Comment by juliennicouleaud** [comment]
Same thing here, I tried quitting and relaunching the app, and changing the shortcuts but it doesn't work anymore. Same version -> 1.0.5.

**Comment by parreirat** [comment]
Same thing here.

**Comment by zuzkins** [comment]
It seems to me, that, whenever the window is bigger than the resolution of the other display, it cannot be moved to that display using spectacle, if I make it smaller, it works.

**Comment by joaopimentel** [comment]
Not exactly if the window is bigger that the target display, but if the window-width is bigger than the target display, then the window is not movable.
Shortening the window width makes it movable to the smaller display.

**Comment by guy-zuckerman** [comment]
same for me, after latest update is got broken

**Comment by parreirat** [comment]
Yup, I confirm it on my side as well: if the window is bigger than target display, it snaps back.

**Comment by eczarny** [comment]
I was just able to reproduce the issue. Unfortunately I don't have multiple displays at home so I need to work on this after hours at the office. It may take me a bit of time to track down a fix but I'm confident I'll have something ready this week.

**Comment by eczarny** [comment]
Can folks see if this build helps at all?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6b.zip

**Comment by zuzkins** [comment]
@eczarny That build seems to work properly when moving bigger window to smaller display. Thanks!

**Comment by andrewcl** [comment]
@eczarny Checked your latest build and it fixes this thread's issue. Many thanks!

**Comment by eeichinger** [comment]
if it's any help, the problem was introduced between 1.0.4 and 1.0.5 - I reverted to 1.0.4 and this works fine
