### ISSUE TITLE
1.0.5 - Unable to maximise windows

### ISSUE THREAD

**Issue by huntie** [eczarny/spectacle#577]
'Fullscreen' has stopped working since the last update with any shortcut I assign to it. Previously I could get the current window to fill the available screen space. (OS X 10.11.4)

**Comment by eczarny** [comment]
What is the current behavior you are seeing? Does rebooting help at all? Does the issue go away after some time?

**Comment by huntie** [comment]
Tried rebooting, Spectacle is working and responsive minus this one command.

**Comment by eczarny** [comment]
Can you see if this build helps at all?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6b.zip

**Comment by huntie** [comment]
Yes! That's fixed it, thank you :)

**Comment by JulianNorton** [comment]
@eczarny I want to confirm that that build fixes a bug I was having. I couldn't move my full-screen windows between my monitors. The beta version resolves it.
