### ISSUE TITLE
Issue moving between displays

### ISSUE THREAD

**Issue by jeffreyzinn** [eczarny/spectacle#580]
I'm experiencing an issue when using the ⌃⌥⌘→/← keyboard shortcut to move a window to available displays. I have a laptop and a large display. If a window is on the large display and I try to send it to the laptop display, the window moves to the laptop display for a moment, shrinks in size, then jumps back to the large display. But I do not have an issue moving windows from the laptop display to the large display.

**Comment by eczarny** [comment]
Known issue. Monitor #575 for updates.

**Comment by jeffreyzinn** [comment]
Awesome! Thank you! Sorry for not seeing the previous, duplicate issue.
