### ISSUE TITLE
Shortcut for Next Display doesn't appear in menu

### ISSUE THREAD

**Issue by quinncomendant** [eczarny/spectacle#581]
When using "space" as a key. Probably an OS X issue with long shortcut sequences, feel free to 'wontfix`. 

![screen shot 2016-05-02 at 22 35 45](https://cloud.githubusercontent.com/assets/6884276/14989494/c8a9668e-111d-11e6-82af-124fc359c38f.png)

**Comment by eczarny** [comment]
That's likely the reason though it would be good to display something helpful.

**Comment by michaelghinrichs** [comment]
my next display isn't working with the new update, anyone else seeing this?

**Comment by tseven** [comment]
@michaelghinrichs I am experiencing the same. I've created a separate issue for this: https://github.com/eczarny/spectacle/issues/589
