### ISSUE TITLE
Next/previous (partially) display broken in 1.0.5 version

### ISSUE THREAD

**Issue by jshado1** [eczarny/spectacle#582]
I installed 1.0.5 this morning and now I can't send windows to my laptop's built-in screen. Spectacle initially moves the window to the correct screen, but almost immediately kicks it back to the previous screen. I tried it with multiple/different applications (Chrome, Firefox, SublimeText), and experienced the same behaviour.

I reverted back to 1.0.4, and it's fine.

OS X 10.11.4

**Comment by ludicruz** [comment]
I am also seeing the same issue.
If the window I am trying to move is larger than the target screen, the window "jumps back" to where it was.
if the window I am trying to move is smaller than the target screen, the window moves properly to the target.
hope this helps

**Comment by jshado1** [comment]
Ah, yes that is it. 1.0.4 would downscale the window to fit on the smaller screen.

**Comment by eczarny** [comment]
Closing as a duplication of #575.
