### ISSUE TITLE
1.0.5

### ISSUE THREAD

**Issue by darylknight** [eczarny/spectacle#585]
Since yesterday's update I can't use the keyboard shortcut to move windows from my main display (a 1920x1080 monitor) to my Macbook screen, it moves then just bounces back to where it was. Monitor setup is:

1920x1080 monitor | 1920x1080 monitor | Macbook 13" retina

I assume the issue is that you can't move a window from a larger screen to a smaller one.

**Comment by williamboman** [comment]
As a temporary workaround, one can reduce the size of the window before issuing the prev/next display command, like so;

<img src="https://cloud.githubusercontent.com/assets/6705160/15012824/0c984f98-11fc-11e6-824d-46e39828a2db.gif" width="100%">

**Comment by alabeduarte** [comment]
Hi @williamboman 
Thank you for the workaround, but doesn't work for all applications.

**Comment by eczarny** [comment]
@alabeduarte and @williamboman does 1.0.6 work for you?

**Comment by williamboman** [comment]
> @alabeduarte and @williamboman does 1.0.6 work for you?

Yep, works great. Thanks!

**Comment by alabeduarte** [comment]
works for me too!

Thank you so much

**Comment by darylknight** [comment]
Problem solved :)
