### ISSUE TITLE
Tiling to corner does not work for some apps

### ISSUE THREAD

**Issue by themightyoarfish** [eczarny/spectacle#586]
It is Telegram again for me, but I don't know if that is the only affected app. When pressing `ctrl-opt-left` or `ctrl-opt-right` or with shift combined, the window snaps to the corner for a split-second, but is moved back to its original position immediately. Tiling to the left or right half still works, but the undo shortcut is broken as well. Happens since the most recent update 1.0.5 (590). See below gif.

![spectacle_bug](https://cloud.githubusercontent.com/assets/11613312/15015706/b4874d2e-120d-11e6-9bb4-125f39602aae.gif)

**Comment by eczarny** [comment]
@themightyoarfish does 1.0.6 work for you?

**Comment by themightyoarfish** [comment]
@eczarny Yes, the issue with the corner snapping has disappeared. The undo action still does not work, however. While previously, it sometimes did something, but not the right thing, now it does not do anything at all and I hear this 'pling' alert system sound which indicates error.

**Comment by eczarny** [comment]
@themightyoarfish would you mind opening a new issue for the problems you are seeing with the undo action? A video or GIF demonstrating the issue would also be helpful.

I'm closing this issue because 1.0.6 fixes the primary problem moving windows to corners.
