### ISSUE TITLE
Make it possible to update through Spectacle's main/config window

### ISSUE THREAD

**Issue by williamboman** [eczarny/spectacle#587]
I use [Bartender](https://www.macbartender.com/) to hide excessive menu bar items that I don't really use (Spectacle is one of them). In order to check for new updates I have to go into my Bartender settings, re-allow Spectacle, and then check for updates through the contextual menu.

Since the only interface I can access seamlessly is Spectacle's "main" window, would it be possible to add a `Check for updates` button in there too?

**Comment by eczarny** [comment]
I've thought about this a bit in the past since Spectacle also allows you to hide its status bar item. Since Spectacle automatically checks for updates I figured that was typically fine for 90% of the time. The menu item is there for the rare times you need to check for an update manually.
