### ISSUE TITLE
Next / Previous display no longer works 1.0.5

### ISSUE THREAD

**Issue by tseven** [eczarny/spectacle#589]
Activating the shortcut to move a window from my main display to my secondary display will move the window the other display for a fraction of a second before it returns to its original spot.

This appears to have cropped up over the last update.

**Comment by tseven** [comment]
This was just fixed in 1.0.6.
Thanks!

**Comment by michaelghinrichs** [comment]
thank you spectacle :) very speedy!

**Comment by s7anley** [comment]
Thanks for quick fix 👍
