### ISSUE TITLE
Unable to select text with ⇧← until quitting Spectacles 1.0.6

### ISSUE THREAD

**Issue by richard-mansfield** [eczarny/spectacle#592]
With reference to #578 I am unable to select text with ⇧← until I quite Spectacles 1.0.6 even after reassign keyboard shortcuts for moving the windows to upper left/right and lower left/right.

![image](https://cloud.githubusercontent.com/assets/7224292/15046457/b0140820-12d7-11e6-8079-92aa5434f9d3.png)

**Comment by eczarny** [comment]
After reassigning these keyboard shortcuts can you try rebooting? I wonder if the old keyboard shortcuts aren't being removed correctly.

**Comment by richard-mansfield** [comment]
Unfortunately rebooting didn't resolve the issue.

**Comment by richard-mansfield** [comment]
I've downgraded to 1.0.4 and no longer have the same issues.
