### ISSUE TITLE
Don't steal focus to prompt to upgrade

### ISSUE THREAD

**Issue by lieut-data** [eczarny/spectacle#593]
I literally just got a prompt to upgrade Spectacle (to 1.0.6 593, running OSX El Capitan 10.11.4) that stole my focus and consumed the enter key I pressed (which was intended for another application) as consent to upgrade the application. The download completed and I was left with the option to restart the application and complete the upgrade.

I really love Spectacle and I usually don't have an issue with upgrading, but surely this is broken. Would you consider another way to notify me about updates? I'm a big fan of, for example, 1Password's Notification Centre prompt.

**Comment by eczarny** [comment]
Spectacle uses [Sparkle](https://sparkle-project.org/) for handling app updates. This issue may be better handled by that team. In all honesty this likely isn't something I would get around to looking at in any reasonable amount of time.
