### ISSUE TITLE
full screen problem in Spectacle 1.0.6

### ISSUE THREAD

**Issue by amirj** [eczarny/spectacle#594]
After upgrading to 1.0.6 full screen shortcut does not works for different applications. Using full screen command from menu bar or the corresponding shortcut, the window is positioned on the center of the screen.

**Comment by eczarny** [comment]
Can you find any log output in Console? What happens if you reboot?

**Comment by mardlin** [comment]
Same issue here. Rebooting fixed it, but then changing the shortcut breaks it again. 

How can I get log out put from the console for you?

**Comment by Chris911** [comment]
I'm also getting some weird behaviour on 1.0.6 with the full screen shortcut and Chrome and Safari. Still works as expected with other apps. After restarting it works for a while and then it breaks again. 

When it "breaks" the fullscreen shortcut doesn't maximize the window and I have to either hold the keys down or press multiple times and it slowly gets to fullscreen.

**Comment by GabeIsman** [comment]
Getting the same behavior with Chrome and Slack (although not other Chromium-based apps). Hitting make full screen repeatedly centers, and then enlarges slightly, centers, enlarges slightly, and so on. Possibly related: the apps that exhibit this behavior are also animating through size transitions, which they didn't used to do.

**Comment by kjfl** [comment]
Same issue here--seems to be specific to Chrome and Slack as the previous poster suggested.  I tried downgrading to Spectacle 1.0.5 and I still experience the "slowly getting to maximize as I keep pressing the shortcut combo" issue.  I see this with pretty much every operation when these apps in focus (top half, left half, full screen, etc).  El Capitan 10.11.5 (15F34), Chrome 50.0.2661.102 (64-bit), Slack 2.0.2 (3412) in case that helps.

**Comment by Chris911** [comment]
I'm on OS X 10.11.4 and Chrome 50.0.2661.102.

**Comment by vgrafe** [comment]
same bugs here - OSX 10.11.5 (15F34), Chrome 51.0.2704.79 (64bit).

Chrome and Slack won't behave as expected when using Spectacle's shortcuts

**Comment by kagarlickijd** [comment]
For me the same issue with Chrome and vSSH

**Comment by vgrafe** [comment]
Well the problem disappeared from my laptop altogether - I have no explanation for that (I restarted it before, with the problem persisting, but didn't try to fix it otherwise)

**Comment by Chris911** [comment]
Same here. No longer a problem with Chrome. I'm on 51.0.2704.84 now.

**Comment by kjfl** [comment]
Yep, seems like it was a Chrome bug.  Fixed for me in Chrome 51.0.2704.79
