### ISSUE TITLE
1.0.6, I've observed changes to key-command behavior

### ISSUE THREAD

**Issue by monte-hayward** [eczarny/spectacle#597]
after upgrade to 1.0.6, I've observed changes to key-command behavior. commands in my favorite editor is now intercepted by Spectacle, as follows.

- my copy-line-downward, Command-option-down arrow shrinks window to 1/4, lower right.
- my copy-line-upward, Command-option-up arrow shrinks window to 1/4, upper right.

I have fiddled with Spectacle prefs and was able to workaround the issue by using modifiers ctrl-option-command with arrow keys.

- ctrl-Command-F still works - maximize current window (which is much nicer than OS X `enter full screen`)

**Comment by eczarny** [comment]
If you reset Spectacle to the default shortcuts does everything work as you intended? Did you customize your shortcuts before upgrading to 1.0.6? If so what were they?
