### ISSUE TITLE
[FEAT] More Window Sizes

### ISSUE THREAD

**Issue by pnovotnak** [eczarny/spectacle#600]
I've just gotten a 31" display which is cool, look at me the cool guy with the 31" display!

Anyway, the larger screen size got me thinking it would be cool if spectacle supported more screen divisions. Stuff like this:

             1     2     3     4     5     6     7     8     9
        _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
       |     |     |                 |
     1 | - - +     |                 |
       |     |     |                 |
     2 | - - + - - +                 |
       |     |     |                 |
     3 | - - + - - +- - -+- - - - - -+- - -+
       |                 |                 |
     4 |                 |                 |
       |                 |                 |
     5 |                 |                 |
       |                 |                 |
     6 |- - - - - - - - -+ - - - - - + - - +
       |                             |
     7 |                             |
       |                             |
     8 |                             |
       |                             |
     9 |                             |
       |_ _ _ _ _ _ _ _ _ _ _ _ _ _ _|

I used to run into this every once and a while with itty bitty terminal windows running `watch` or something, even on my 15" notebook screen, so I think it's applicable to more than just gigantor displays.

My current thinking is that this might be 2 different new high-level features;

- resize on a single axis
- support 1-9 divisions of the display on each axis

cc @javierbq

**Comment by pnovotnak** [comment]
I saw #427, which looks like might yield support for this via user-generated scripts?

**Comment by eczarny** [comment]
@pnovotnak You're right. The work I'm doing in #427 will likely be exactly what you're looking for.

I haven't settled on the API yet so beginning on any documentation right now would be premature. If you're interested in contributing to the project documentation is a great place to start. Feel free to create an issue to track that work and assign it to yourself. I'll continue to comment in #427 with updates as I move towards a final JS API.
