### ISSUE TITLE
1.0.6 not working on iMac

### ISSUE THREAD

**Issue by Dave-ZenTech** [eczarny/spectacle#606]
I have Spectacle installed on a MacBook Air and an iMac, both running 10.11.5. All is well on the laptop but not at all on the desktop where a) custom shortcuts are not appearing correctly (Reference #602 below), which initially prevented me realising that Spectacle is simply not responding at all. 

Whether I use a custom or default shortcut, or select from the dropdown menu, I get the standard error sound and nothing else happens.

**Comment by eczarny** [comment]
Does rebooting help at all? Could you provide any error messages from Console.app?

**Comment by Dave-ZenTech** [comment]
Hi Eric

attached are two screen shots from my iMac, which has been rebooted, showing the Spectacle prefs screen after ‘restore defaults’ and then after trying to set the full screen shortcut as ⌥␣. There is no obvious error message, but I know nothing about Console so could be wrong. You can see from the second screenshot that the quick ref dropdown shows ⌥Space as the shortcut, but the Spectacle prefs sheet is missing the Space.

For comparison, I have attached a screen dump from my MacBook, where Spectacle is working properly. The only oddity here is the the drop down QR menu shows nothing against Full screen, but it works.


https://dl.dropboxusercontent.com/u/68879/Misc/iMac1.png

https://dl.dropboxusercontent.com/u/68879/Misc/iMac2.png

https://dl.dropboxusercontent.com/u/68879/Misc/Macbook.png

Hope this helps, Dave

——————————————
making technology work for you

——————————————
making technology work for you

**Comment by elithrar** [comment]
Was it working at any stage? Never worked?

**Comment by Dave-ZenTech** [comment]
Never worked

——————————————  
making technology work for you

**Comment by eczarny** [comment]
@Dave-ZenTech can you try quitting Spectacle, deleting Spectacle's .plist files under `~/Library/Preferences`, and rebooting? That should completely reset Spectacle's preferences to the defaults and allow you to configure it once more.

**Comment by Dave-ZenTech** [comment]
Hi Eric

I have done all of that, still not working on the iMac.

Dave

——————————————
making technology work for you

**Comment by Dave-ZenTech** [comment]
Closed without resolution.

**Comment by eczarny** [comment]
@Dave-ZenTech this issue isn't actionable so I closed it.
