### ISSUE TITLE
Spectacle won't resize windows "left"

### ISSUE THREAD

**Issue by pkmoore** [eczarny/spectacle#611]
When using custom shortcuts or the default shortcuts I cannot get window to resize to the left side of the screen. This includes upper left, lower left, left half. etc.

Any ideas on how to troubleshoot this?

Thanks

**Comment by pkmoore** [comment]
I did a little more exploring and managed to get resize to the left half and left third of the screen working. I cannot get resize to lower left corner working with a keyboard shortcut. It works if I select it from the drop down menu but a definite reduction in the usefulness of this tool.

**Comment by sido378** [comment]
+1, cannot use shortcuts to resize windows to the left or right.
top or bottom works, as well as all other shortcuts.

**Comment by jondb** [comment]
This affects me too. Is there some way to troubleshoot why the keyboard shortcuts are not working / other information I can provide to help?

**Comment by eczarny** [comment]
@jondb did you happen to clear the shortcut then try to set it again? Does restarting the app help?

**Comment by eczarny** [comment]
I'd appreciate it if somebody could try out this 1.1a build to see if this issue is resolved:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.1a.zip

**Comment by hwangmoretime** [comment]
@eczarny I tried out the 1.1a build and it worked for me. The following commands (at the very least) weren't working for me prior to installing the new build:

upper left
bottom left
upper right
next display
previous

Huge thanks for the awesome tool!
