### ISSUE TITLE
Spectacle does not update OS X menu bar when moving a window between displays

### ISSUE THREAD

**Issue by sergej-koscejev** [eczarny/spectacle#614]
I have multiple displays, with the menu bar visible on each display. I have an application open on a display. I move it to the next display and the window now appears there. However, the menu bar on top of that display is not updated and still shows items from the last application that I used there. I'd expect the menu bar to change since another window is now active.

**Comment by eczarny** [comment]
I believe this only works properly if the windows has focus after Spectacle moves it. Not quite sure why that's the case but it's something I've noticed in more recent OS X releases.

**Comment by sergej-koscejev** [comment]
[Magnet](http://magnet.crowdcafe.com/) is able to do this properly, so I thought Spectacle could too.

**Comment by sergej-koscejev** [comment]
@eczarny also, I don't understand what you mean by your comment. The window does have focus since I'm doing the move using a keyboard shortcut, but the menu bar is not updated on the screen the window is moved to.

**Comment by rhollencamp** [comment]
@eczarny I am also experiencing this issue; I believe it should be re-opened. The menu bar does not update even if the window retains focus for me.
