### ISSUE TITLE
Shortcut for 2/3 screen width left or right ? possible ?

### ISSUE THREAD

**Issue by neocomien** [eczarny/spectacle#616]
Hi,
Having a big screen (Apple Thunderbolt Display 27") connected to my MacBook Pro, i often use the half-screen shortcuts, but for some projects it would help if i could have a 2/3 width left or right shortcuts !
Is this possible ?
Best regards,
Marc

**Comment by kbleabres** [comment]
Try ⌥ + ⌘ + twice the left or right arrow key.
