### ISSUE TITLE
macOS Sierra: windows "stick" to edges

### ISSUE THREAD

**Issue by goodworkguy** [eczarny/spectacle#617]
In the current macOS Sierra developer beta, if you try to resize or drag apps around, they will "stick" to edges of other windows or the desktop for a few pixels.

This interferes with Spectacle's window resizing functionality. For example, if I have a centered window that touches the top and bottom edges of the desktop, and I try to "Make Smaller," only the left and right sides shrink instead of all sides. The top and bottom stick to where they're at.

**Comment by eczarny** [comment]
This is actually how Spectacle is supposed to behave. Any edge of the screen a window "touches" Spectacle will stick to as you make smaller or larger.
