### ISSUE TITLE
Next Display keyboard shortcuts not working

### ISSUE THREAD

**Issue by alecfriedman3** [eczarny/spectacle#619]
Maybe I am just doing something incorrectly, but my next and previous display keyboard shortcuts are not working, seemingly no matter what I make them. The functionality works when I click next display with my mouse from the toolbar, but not with my keyboard shortcuts. If it matters, I'm on an 11 inch Macbook Air, with an Asus hd display positioned above my screen.

**Comment by alecfriedman3** [comment]
Meant to comment a few weeks ago on this, after I restarted my machine the shortcuts were working, which I believe means that for some reason the next and previous display shortcuts did not take effect until the program was closed and reopened. Either way, working fine now.

**Comment by zuernBernhard** [comment]
yes restarting the program helped here too
