### ISSUE TITLE
Spectacle doesn't work on my Macbook

### ISSUE THREAD

**Issue by Camboon** [eczarny/spectacle#622]
I'm currently using Macbook Pro early 2015, running on OS X El Capitan Version 10.11.5. 

I've allowed Spectacle to control my computer and even allowed all incoming connections for Spectacle in the firewall setting but whenever I try to use any command, the wrong beep will just sound. 

Any help? 
<img width="667" alt="screen shot 2016-07-16 at 12 01 07 pm" src="https://cloud.githubusercontent.com/assets/20485535/16892657/0ff1bf6e-4b4d-11e6-9a92-b186de961b87.png">
<img width="565" alt="screen shot 2016-07-16 at 12 02 05 pm" src="https://cloud.githubusercontent.com/assets/20485535/16892663/2b013762-4b4d-11e6-9807-e2b91e31a1c9.png">

**Comment by selfup** [comment]
Is the spectacle icon in your top bar?

**Comment by eczarny** [comment]
@Camboon can you provide any output from the Console? My guess is Spectacle is somehow unable to find the focused window of the frontmost app (I'm still not quite sure why this happens). Rebooting sometimes helps.
