### ISSUE TITLE
1px vertical line visible on the right side depending on the dock's size

### ISSUE THREAD

**Issue by hyperknot** [eczarny/spectacle#624]
I have the following setup:
1. OS X 10.11.5
2. Dock on the left side
3. Trying to align windows to the right side of the screen (either quarter or half).

What is happening:
Depending on the dock's size, Spectacle leaves a 1px line visible on the right side of the screen, when doing half screen alignments. It always happens for me in smaller dock sizes.

What should happen:
The half screen alignments should always be aligned to the right side of the screen, no matter how  wide is the dock on the right side. There should never be a 1px vertical line visible.

**Comment by eczarny** [comment]
@hyperknot mind providing a screenshot?

**Comment by hyperknot** [comment]
Sure, no border:
<img width="1920" alt="screen shot 2016-07-26 at 12 26 06" src="https://cloud.githubusercontent.com/assets/494223/17134849/bf6f2044-532c-11e6-9606-66147ffe0dea.png">

Border:
<img width="1920" alt="screen shot 2016-07-26 at 12 27 07" src="https://cloud.githubusercontent.com/assets/494223/17134853/ca322b0c-532c-11e6-96a2-8c3fa111c156.png">

BTW, I guess it might be an odd-even issue, it can happen on bigger dock sizes as well.

**Comment by eczarny** [comment]
Ah. This is likely an issue with iTerm2:

https://github.com/eczarny/spectacle#spectacle-behaves-strangely-with-terminal-windows

I believe there is a preference for iTerm2 that allows you to scale the terminal emulator. Worth a shot?

**Comment by hyperknot** [comment]
No, it is exactly the same in Sublime Text, etc.
<img width="97" alt="screen shot 2016-09-27 at 12 10 54" src="https://cloud.githubusercontent.com/assets/494223/18871072/96e9ad82-84ab-11e6-84d5-d41ff01c7451.png">

**Comment by hyperknot** [comment]
OK, I can reliably replicate the issue by setting the dock tilesize values to even-odd via command line:
`defaults write com.apple.dock tilesize -int 25; killall Dock` produces no gap
while
`defaults write com.apple.dock tilesize -int 24; killall Dock` produces 1px gap on the right side
