### ISSUE TITLE
Keep window 'Always on top' [enhancement]

### ISSUE THREAD

**Issue by bonilladisseny** [eczarny/spectacle#625]
I was looking for a solution to keep the window 'Always on top' and I see some solutions like Afloat, but it seems a bit [hacky](http://www.perfectlyrandom.org/2015/01/31/always-on-top-in-macos-yosemite/) to make it run on my machine, also I see other apps that they are supposed to do this but they also have similar functionalities as Spectacle app, and since this is the one I have installed and I am very happy with it I would like to suggest the possibility to have this option in a future, something like you can opt-in when you have a window focused.

Thanks for reading!

**Comment by eczarny** [comment]
Thanks for the suggestion! Unfortunately I don't have plans to expand Spectacle's set of features beyond more customizable window actions.
