### ISSUE TITLE
Inherit position when moving windows between monitors

### ISSUE THREAD

**Issue by alepuccetti** [eczarny/spectacle#626]
When moving a window from a smaller monitor to a bigger one (e.g. from macbook pro retina display to external 4K monitor), the window appears "centered". I think that a better behavior would be that the window matches the relative position of the source to the destination monitor.

Example:
The window **left corner** is on the **most high and most left** position in the macbook pro display moving it to the external display should appear in the **most high and most left**.

The final result should be that when you move a window that was on the left/right of one monitor will show up at the same "relative position.

**Comment by eczarny** [comment]
Closing as a duplicate of #609.
