### ISSUE TITLE
Video Fullscreen after using Spectacle Next Screen hotkey fills previous screen

### ISSUE THREAD

**Issue by FaultyJuggler** [eczarny/spectacle#627]
Running OS X 10.11.5

Actions to recreate:
1. Open a youtube or vimeo video page
2. use hotkey to move the window to next or previous display
3. hit play
4. hit the full screen mode in the video
5. Observe the video takes over the last display it was on, not the current one

This may be an OS level issue that cannot be fixed by Spectacle, especially given the changes to how OSX uses spaces and dragging windows with the mouse.

**Comment by eczarny** [comment]
Likely an issue with the web browser.
