### ISSUE TITLE
How to have Spectacle to launch at startup

### ISSUE THREAD

**Issue by wayne1964** [eczarny/spectacle#628]
When I try to add Spectacle to my startup items, it is nowhere to be found in the list of applications that appears on my Mac. Thanks for any help you can provide. … Wayne

**Comment by spiritphyz** [comment]
@wayne1964 In the Preferences window, down at the bottom section where there is a "icon map" for the Control, Option, Shift, and Command keys, there is a "right arrow" icon on the right. 

If you click that right arrow icon, an option will be revealed for "Launch Spectacle at login". 

After I turned that checkbox on, I can see Spectable listed in the "Login Items" of my Users & Groups system preferences.

**Comment by jaksmid** [comment]
I had the same problem. I suggest to make the option visible without clicking some arrow.
