### ISSUE TITLE
Feature Request: Shortcut to disable/enable spectacle for current app

### ISSUE THREAD

**Issue by sabuzuhlke** [eczarny/spectacle#632]
apps such as chrome and intellij share some keyboard shortcuts with spectacle, would be very useful to be able to quickly disable/enable for current app to be able to toggle between them

**Comment by eczarny** [comment]
There isn't a shortcut but you can disable Spectacle for the current app via the status bar menu.

**Comment by manojhl** [comment]
I agree with @sabuzuhlke.

**Disable for "Application"** feature is awesome but I would be even more powerful if we can disable a particular shortcut for an application.

**Comment by ZiFFeL1992** [comment]
+1 I really like Spectable but there are some shortcuts which are the same than VS Code or Google Chrome, that's why I don't usually have it running, but having a "switch shortcut" to enable or disable Spectacle shortcuts would be AWESOME!
