### ISSUE TITLE
Spectacle full screen and split left/right inconsistent with El Cap

### ISSUE THREAD

**Issue by stevenqzhang** [eczarny/spectacle#633]
I run spectacle on 3 macbookpros. On the one upgraded to el cap, spectacle's full screen and left/right commands are inconsistent. On certain apps, like Chrome and todoist, those commands don't work when activated from keyboard. Using the menu bar commands still do though.

**Comment by citylims** [comment]
The recent update to chrome Version 52.0.2743.116 has new keyboard shortcuts which conflict with and seem to override the default spectacle binds for half left/right and fullscreen. It's a bit of a drag, but you can customize spectacle preferences and change the binds to something that won't conflict with the new chrome, or you could rollback chrome.
