### ISSUE TITLE
Next/Previous Display only works from menu

### ISSUE THREAD

**Issue by marlonrichert** [eczarny/spectacle#634]
If I try to use a keyboard shortcut, nothing happens.

Spectacle 1.0.6 (593)
OS X El Capitan 10.11.2

**Comment by eczarny** [comment]
Out of curiosity what apps are you having trouble with?

**Comment by eczarny** [comment]
Also, did you clear the shortcut at all before adding your own? Does restarting the app help?

**Comment by marlonrichert** [comment]
I found this bug only happens when reassigning shortcuts in the preferences and it can affect almost any of the commands. When the bug takes place, it affects Spectacle in _all_ apps. Restarting Spectacle fixes the problem.

**Comment by eczarny** [comment]
@marlonrichert Thanks for the info! I think I have a fix on master for this very problem. Are you able to build and run Spectacle? It would be great to confirm.
