### ISSUE TITLE
Allow shifting to automatically walk across monitors.

### ISSUE THREAD

**Issue by rquadling** [eczarny/spectacle#636]
Hi.

I use Left/Right Half a lot. But on 3 monitors, it is a pain switching key strokes to shift monitor.

I'd like to propose an enhancement such that repeatedly pressing Left Half (or Right Half), walks the window through the different monitors.

So, as an example, assuming the window is on the far left display, currently left handed aligned.

0. `[* ][  ][  ]`
1. `[ *][  ][  ]`
2. `[  ][* ][  ]`
3. `[  ][ *][  ]`
4. `[  ][  ][* ]`
5. `[  ][  ][ *]`
6. `[* ][  ][  ]`

In the above list, the number is the number of times I pressed Right Half.`[  ]` is a monitor and `*` is the window moving across my displays each time I press Right Half.

Ideally, thirds too, so maybe 'Next Half' and 'Previous Half' (and thirds), rather than Left/Right.

I hope this makes some sense.

**Comment by eczarny** [comment]
Thanks for the suggestion but this isn't a feature I plan on adding. Especially since the same behavior exists today to support thirds.
