### ISSUE TITLE
1/3rds or even 1/4 ths for large monitors

### ISSUE THREAD

**Issue by saptarshiguha** [eczarny/spectacle#637]
Hello,
I've been planning on getting a 34" monitor. Setting a window (say emacs in terminal) to half the width would be waste of real estate. Rather I'd like to make it 1/3rd or even 1/4th.

Is there a way to do this? Would this be a feature request?

Thanks again, it's a very useful app.
Cheers
Saptarshi

**Comment by danyalaytekin** [comment]
Agreed, I'd like a way to split a 21:9 monitor into quarters horizontally, or even sixths.  See e.g. U2913WM.

**Comment by eczarny** [comment]
You can move windows to thirds using ctrl + option right or left arrow. I'll update the README to include more of the basic shortcuts.
