### ISSUE TITLE
Spectacle sometimes stops responding after either wake or external keyboard re-attach

### ISSUE THREAD

**Issue by zyklus** [eczarny/spectacle#638]
Basically when I come in to work and plug my laptop in Spectacle sometimes doesn't work.  Simple fix is to toggle "disable for an hour" then untoggle.

Sorry I don't have a more reproducible issue!  Running 1.0.6 on OSX 10.11.6

**Comment by eczarny** [comment]
Any Console output would be really helpful.

**Comment by mjpitta** [comment]
I have a similar problem for the last couple of weeks.  Quitting and restarting resolved it for about an hour, and it repeats several times a day.

**Comment by eczarny** [comment]
If anybody can build and run Spectacle from `master` I'd be curious if a recent fix helps in this situation.

**Comment by eczarny** [comment]
I'd appreciate it if somebody could try out this 1.1a build to see if this issue is resolved:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.1a.zip

**Comment by zyklus** [comment]
Installing now.  The bug usually only appears a couple of times per week, so if I haven't followed up in say 2 weeks feel free to mark it resolved!

**Comment by zyklus** [comment]
And FYI there's nothing at all in console save random launch & time logs.
