### ISSUE TITLE
System Preferences screenshot is out of date

### ISSUE THREAD

**Issue by ZevEisenberg** [eczarny/spectacle#639]
![screen shot 2016-08-29 at 3 04 54 pm](https://cloud.githubusercontent.com/assets/464574/18063688/099f087c-6dfa-11e6-85a3-39df053577a2.png)

That's a screenshot from the current app. I don't know if the appearance of System Preferences has changed between 10.11 and 10.12. Here's a screenshot from my installation of 10.11:

![screen shot 2016-08-29 at 3 06 22 pm](https://cloud.githubusercontent.com/assets/464574/18063718/28f83766-6dfa-11e6-88ca-f54768038708.png)

**Comment by ZevEisenberg** [comment]
Oh, it looks like this was updated in https://github.com/eczarny/spectacle/pull/601 but not released yet.

**Comment by eczarny** [comment]
@ZevEisenberg I'm hoping to release a new version over the coming weeks.
