### ISSUE TITLE
Unable to use global hotkeys for iTerm2

### ISSUE THREAD

**Issue by lamarqua** [eczarny/spectacle#640]
I can position iTerm2 windows using the menu, but the global hotkeys do not work. 
Example: menu > right half works OK. Using the keyboard shortcut (control option command right on my machine) doesn't work with iTerm 2 / works OK with all other apps.
I have tried explicitly setting the keyboard shortcut within iTerm to "do not remap" (not that I use remapping but hey...), but no cigar.
It used to work a while ago, but I can't remember when. I'm very surprised that I seem to be the only one encountering this problem.

**Comment by eczarny** [comment]
Does restarting Spectacle help at all? What if you try changing Spectacle's shortcuts and then restart the app?

**Comment by lamarqua** [comment]
Tried restarting both Spectacle and iTerm, changing shortcuts (including restoring Spectacle defaults and setting the keys to "do not remap" in iTerm) and nothing helps.

**Comment by chrisvmiller** [comment]
@lamarqua I had this same issue & setting the `remap modifier keys` back to their default values (not remapping the individual keys) within iterm's Preferences-Keys menu fixed it.  Hopefully this helps :-)

**Comment by lamarqua** [comment]
The thing is, I haven't remapped any key at all. They *are* at their default value.

**Comment by eczarny** [comment]
@lamarqua does @chrisvmiller's suggestion help at all? I'm honestly not sure how else to proceed here. It sounds like iTerm2 is somehow intercepting the shortcuts. I don't see the issue when I try resizing my iTerm2 window (though I normally use Terminal).

**Comment by lamarqua** [comment]
It didn't help at all. I'll submit an issue to iTerm2. But I'd have felt better if there was a way for me to prove (some log?) that Spectacle doesn't receive the key events.

**Comment by eczarny** [comment]
@lamarqua you can double check Console to see if Spectacle has logged anything.

**Comment by eczarny** [comment]
Closing this out for now. @lamarqua feel free to reopen if you find anything that can help diagnose the issue.

**Comment by lamarqua** [comment]
I downloaded the source code, compiled, ran under the XCode debugger and put a breakpoint into the global hotkey handler, and confirmed that Spectacle never receives the proper events when iTerm2 has the focus.

Here's the relevant iTerm2 issue:
https://gitlab.com/gnachman/iterm2/issues/5173
