### ISSUE TITLE
Alt+Cmd+Numpad1 and others not working

### ISSUE THREAD

**Issue by AndiDog** [eczarny/spectacle#642]
Spectacle 1.0.6, Mac OS X 10.11.6

I've assigned Alt+Cmd+Numpad<number> where <number> is

1=lower left
3=lower right
7=upper left
9=upper right

The numbers 3 and 9 are working fine, but 1 and 7 are not. Tested on different applications like Firefox and Skype. I guess that no global hotkey is defined for those combinations - they're too uncommon.

I've tried checking console output but the app asks for accessibility access which is already enabled and then fails to resize _anything_. Maybe you could add an explanation to the CONTRIBUTING file?

```
$ ~/Applications/Spectacle.app/Contents/MacOS/Spectacle
2016-09-05 14:01:48.959 Spectacle[20801:889349] Unable to obtain the accessibility element with the specified attribute: AXFocusedWindow (error code -25211)
2016-09-05 14:01:48.959 Spectacle[20801:889349] Invalid accessibility element provided, unable to determine the size and position of the window.
```

**Comment by eczarny** [comment]
@AndiDog I have yet to figure out why Spectacle sometimes runs into those errors. Try restarting the app (or if that doesn't work reboot). My current theory is it's actually an issue with OS X's accessibility APIs. I have yet to follow up with Apple on it however.

As for your original issue I'll do some investigating once I have access to a full keyboard.

**Comment by eczarny** [comment]
@AndiDog could you try out this 1.1a build to see if your issue is resolved?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.1a.zip

**Comment by AndiDog** [comment]
Today I couldn't reproduce the problem anymore and all four shortcuts work fine. I know I rebooted yesterday. Tried your 1.1a app anyway and it's still working. Let's close this issue for now. If I find out an error, I'll reopen. Is there a log file written?
