### ISSUE TITLE
Feature Request: Resize to sixths

### ISSUE THREAD

**Issue by garypaduana** [eczarny/spectacle#649]
I have a 3840x2160 monitor and I find myself resizing to vertical thirds and then splitting that in half manually.  Having a shortcut to split to sixths (6x approx 1280x1080 in my case) would really be helpful.  Thanks.

**Comment by eczarny** [comment]
Sorry @garypaduana but I'm not likely to get around to this enhancement. Closing in favor of #427 (which is partially implemented).

**Comment by garypaduana** [comment]
I came back to this months later and just wanted to say thanks because version 1.2 does exactly what I was looking for.

**Comment by sshleifer** [comment]
@garypaduana How does one get sixths in version 1.2?

**Comment by sshleifer** [comment]
That's exactly, what I needed, thank you so much!
