### ISSUE TITLE
[Bug] Fullscreen ignores dock

### ISSUE THREAD

**Issue by StephenGrider** [eczarny/spectacle#650]
Using Cmd Alt F used to full screen a window but take the OSX Dock's height into consideration.  This no longer appears to be the case after updating to 1.1.

I have not seen any other issues, open or closed, around this topic, which makes me think its either something wrong with my setup or it is an intended feature.

Current behavior - notice the window underlies the dock
<img width="1280" alt="screen shot 2016-09-15 at 10 57 13 am" src="https://cloud.githubusercontent.com/assets/5003903/18561080/2d9773a4-7b33-11e6-9e41-e2def928d99c.png">

Expected behavior:
<img width="1280" alt="screen shot 2016-09-15 at 10 57 04 am" src="https://cloud.githubusercontent.com/assets/5003903/18561088/34786ca0-7b33-11e6-8468-8e2c7f5d8a63.png">

**Comment by StephenGrider** [comment]
https://github.com/eczarny/spectacle/issues/392 might be a duplicate issue.

**Comment by awaegel** [comment]
Same problem here since the recent upgrade to version 1.1 (648); screenshot attached.
![screen shot 2016-09-15 at 12 26 25 pm](https://cloud.githubusercontent.com/assets/241286/18564307/cd98060a-7b3f-11e6-89da-6f6b8eae3bb4.png)

**Comment by eczarny** [comment]
Does hiding then showing the Dock help? How about restarting the app or your computer?

**Comment by awaegel** [comment]
Restarting my Mac actually solved this problem, thanks for the suggestion.

**Comment by eczarny** [comment]
No problem @awaegel! I think these types of issues are actually due to a bug in OS X.

**Comment by eczarny** [comment]
Closing this issue for now. Please reopen if the issue persists.

**Comment by Storyyeller** [comment]
I recently had this issue and restarting my computer fixed it for me as well.
