### ISSUE TITLE
Feature request: Maximize without going fullscreen

### ISSUE THREAD

**Issue by wulftone** [eczarny/spectacle#653]
I admit I was surprised to find that there is no option for simply maximizing the window, a-la Windows or Linux window managers.  Surely this is a common maneuver?  I do it all the time myself.  I would love to see it come to Spectacle, since OSX has horrible native support for it (especially as a keyboard shortcut).  The native "Zoom" shortcut only works to "Maximize" on certain windows.

I'm sure it's possible!

**Comment by ftvs** [comment]
There is, though I do not remember if the defaults have it enabled. Go to preferences and it should be the second option, below Center.

![screen shot 2016-09-20 at 5 30 39 pm](https://cloud.githubusercontent.com/assets/875561/18665070/06a6dbd0-7f58-11e6-87a3-66ea91367929.png)

**Comment by eczarny** [comment]
@wulftone @ftvs the default shortcut for this window action is ⌥⌘F.
