### ISSUE TITLE
macOS Sierra keystroke assignment

### ISSUE THREAD

**Issue by leavlzi** [eczarny/spectacle#656]
When upgrade to the new macOS Sierra, keystroke assignment with Logitech Options and BetterTouchTool do not worked correctly, but the shortcuts still works when using the keyboard. 
Examples: Left Half won't do anything in Finder, in Chrome, just switch between tabs.

**Comment by eczarny** [comment]
@leavlzi I'm not sure I follow. What do you mean by "keystroke assignment with Logitech Options and BetterTouchTool do not worked correctly"?

**Comment by leavlzi** [comment]
@eczarny I think I know what happened. You could check this: [https://github.com/tekezo/Karabiner/issues/660](https://github.com/tekezo/Karabiner/issues/660)

**Comment by eczarny** [comment]
@leavlzi please close this issue if you can confirm Spectacle is behaving properly.

**Comment by leavlzi** [comment]
@eczarny macOS Sierra changed drivers for keyboard and mouse, so now Spectacle is only worked well for keyboard. Any Spectacle updates could fixed this?

**Comment by eczarny** [comment]
@leavlzi Spectacle doesn't interact with the keyboard driver directly so I don't see what could be done to help. I'm also not exactly sure what you mean by "Spectacle is only worked well for keyboard". What exactly are the issues you are seeing in Sierra without using Karabiner?

**Comment by leavlzi** [comment]
@eczarny Take this for example, I setup the Right Half shortcut in Logitech Options, after upgrade to Sierra, this setting do not work any more. The same in Trackpad.
<img width="518" alt="screen shot 2016-09-25 at 01 29 33" src="https://cloud.githubusercontent.com/assets/3164183/18810427/8960f550-82bf-11e6-9cf4-5d49c7b19fe5.png">

**Comment by eczarny** [comment]
Oh, this isn't something Spectacle supports directly. If Karabiner provides you with this functionality you should continue to follow the issue you linked to.

**Comment by leavlzi** [comment]
@eczarny In fact, I haven't use Karabiner. Thank you to confirm this issue is nothing about Spectacle, I will follow the drivers update.
