### ISSUE TITLE
Can't map shortcut with Option as the only modifier key anymore

### ISSUE THREAD

**Issue by tambourine-man** [eczarny/spectacle#657]
I use Opt+hjkl to map to Left Half, Bottom Half, etc, the Vim way.
Old mappings from previous version still work, but I can't create new ones with option as the only modifier key anymore.

Still rocking El Capitan 10.11.6
Thanks

**Comment by eczarny** [comment]
This was an explicit decision on my part. I wanted to make sure folks couldn't accidentally set up a shortcut that would get in the way of using the Option key to write other characters (e.g. alt+a to produce å on US keyboards).

This is perhaps a bit too restrictive so I'm more than happy to reconsider this decision.

**Comment by tambourine-man** [comment]
Thanks for the reply eczarny.
I use diacritics all the time, but still chose this mapping, as most option characters are not very useful to me, for example: Opt+HJKL map to˙∆˚¬ by default.

Maybe an exclamation mark and tooltip warning the user that the current mapping will make it impossible to enter a specific character?

![spectacle-preferences-suggestion](https://cloud.githubusercontent.com/assets/7542560/18811833/3a3ef096-8295-11e6-9357-119151c3851e.png)

**Comment by eczarny** [comment]
I'll revert the restriction for now. I see no reason preventing folks from specifying shortcuts with only the option modifier.

In the interim folks can work around this restriction by manually modifying the shortcut JSON file.

**Comment by snakeninny** [comment]
@eczarny Is this feature reverted in the latest release? I still can't specify with only option.

**Comment by eczarny** [comment]
Not reverted yet. I should have a bit of time this weekend to catch up on Spectacle fixes.
