### ISSUE TITLE
Unable to resize down fullscreen window in external monitor

### ISSUE THREAD

**Issue by AlecRust** [eczarny/spectacle#659]
Since upgrading to macOS Sierra commands like <kbd>option</kbd> + <kbd>command</kbd> + <kbd>F</kbd> still work to maximize windows, but <kbd>shift</kbd> + <kbd>control</kbd> + <kbd>option</kbd> + <kbd>←</kbd> no longer works to resize windows down on my main external monitor (works fine on main MacBook screen).

This is only a problem when the window is full size i.e. if I manually reduce the size of the window <kbd>shift</kbd> + <kbd>control</kbd> + <kbd>option</kbd> + <kbd>←</kbd> works again.

I assumed macOS Sierra's [window snapping](https://www.youtube.com/watch?v=pzJGeTS49f4) was interferring here, though Spectacle still works fine on my MacBook's screen.

**Edit:** Resizing down if already maxed does not work always on my MacBook's screen actually.

**Comment by icolquhoun** [comment]
Experiencing a similar thing only it IS happening on my MacBook Pro's screen. Oddly enough, it only seems to happen with Chrome. Safari, Firefox, MS Word, all work as expect. Just for Chrome, after a fullscreen, make smaller no longer works after the Sierra upgrade.

**Comment by RickTheHat** [comment]
I'm also having the same issue and it's good to know that others like to go full screen / make smaller / center like I do but hopefully it's a macOS Sierra issue and can be fixed quickly.

btw - for automating these three sets of keystrokes, does anyone have a recommendation for a macro program or hot key program to do this for me?

**Comment by garethderioth** [comment]
I'm having the same issue after upgrade to Sierra.

**Comment by adriaanm** [comment]
Same here, I would like to be able to move a full screen window (in the macOS sense) between screens (and spaces). It works when I use spectacle's full screen command instead of the macOS one (green circle).

**Comment by eczarny** [comment]
As mentioned this definitely seems like an issue with Spectacle's edge stickiness behavior. I'll look into resolve the problem.

**Comment by AlecRust** [comment]
Thank you, this seems to have resolved the issue (https://github.com/eczarny/spectacle/commit/1eb0b5e8f10cdeebaff753606cd96603c37d461e)!

It may be separate, but I now notice when triggering full screen with <kbd>option</kbd> + <kbd>command</kbd> + <kbd>F</kbd> a small gap between the manu bar and the top of the app appears:

![screenshot](https://i.imgur.com/2VmuAc5.png)

Using <kbd>shift</kbd> + <kbd>option</kbd> + <kbd>→</kbd> resolves this.

**Comment by eczarny** [comment]
Looks like that may be a new problem. Mind creating a new issue to track it? I hope to work on a few more fixes over the holiday for a 1.1.2 release.
