### ISSUE TITLE
bind fn Key

### ISSUE THREAD

**Issue by gustavaum** [eczarny/spectacle#662]
Hello, why i cannot use "fn" key to bind spectacle commands?

Some shortcuts are used in other applications or are interesting to use with other finality.

Anyway, i think fn key tiny helpful... And can be interesting use to bind this commands.

(English isn’t my first language, so please excuse any mistakes.)

**Comment by gmm96** [comment]
I think it's not possible.
"fn" key is managed by hardware, not by software, so the app can't detect if it is pressed.
I'm not 100% sure, but I think so.

**Comment by eczarny** [comment]
@gmm96 is correct. The fn key is used to toggle the behavior of a key on a condensed (i.e. laptop) keyboard.
