### ISSUE TITLE
Fullscreen shortcut doesn't work all the time.

### ISSUE THREAD

**Issue by yifanchen** [eczarny/spectacle#663]
EL Captain

I have this issues with all Applications. Fullscreen works fine if I use cursor to select it every time. However, the shortcut doesn't work all the time. I have tried to set the shortcut to different keybindings to avoid the conflict with the native shortcuts of the applications. However, it doesn't work all the time. 

i.e Now, I have the shortcuts set as `alt` + `cmd` + `f`. In Chrome, it works fine sometimes. It doesn't work sometimes as well, in stead it puts the cursor to the url bar. 

Any idea what's going on?

**Comment by eczarny** [comment]
Is Chrome always running when you run into these problems?

It would also be helpful if you could include any log output from Console.app when you do run into this problem.

**Comment by yifanchen** [comment]
No, I quit Chrome all the time, as well as other applications. My monitor has lower resolution than my MBP. So, every time I unplug the monitor, applications go to smaller sizes. That's where I use fullscreen. I will include log when I run into the problem next time.

**Comment by yifanchen** [comment]
It's happening. I opened iTerm2 first, tried to use `cmd` + `alt` + `f` to fullscreen, failed. Then I tried Chrome, failed as well. However, if I go to menu bar use mouse to select fullscreen, it works. 

I checked console.app as well. How do you want me to include logs? I don't see any logs named after Spectacle.

**Comment by yifanchen** [comment]
Additional note:  I restarted Spectacle, it worked again. However, not sure how long this is going to last.
