### ISSUE TITLE
Shortcuts disappear on app restart

### ISSUE THREAD

**Issue by pjalybin** [eczarny/spectacle#664]
All shortcuts disappear after quit and restart. Shortcut is ⌘§
![2016-10-04_16-44-06](https://cloud.githubusercontent.com/assets/5345434/19076528/ceeaf686-8a51-11e6-8c77-ba9a9ff9d602.png)

**Comment by eczarny** [comment]
@pjalybin are you still seeing this issue? Can you try finding any relevant output in Console and paste it here?

**Comment by pjalybin** [comment]
It seems to be a duplicate of #681

**Comment by rarespintea** [comment]
Not quite a duplicate. 
For my issue, only one shortcut disappears, the one with "funky" chars.
For @pjalybin it's quite different, I think it's a permissions problem.

**Comment by eczarny** [comment]
In this case do all of the shortcuts disappear or just the shortcuts that use §?

**Comment by pjalybin** [comment]
Only the shortcuts that use § 
(I used different combinations with that symbol at the same time)

**Comment by eczarny** [comment]
In that case this does seem to be a duplicate of #681. Closing for now. Please reopen if this issue is tracking a different problem.
