### ISSUE TITLE
Consider submitting a spectacle as a cask for homebrew

### ISSUE THREAD

**Issue by mike-lawrence** [eczarny/spectacle#665]
This would make it possible to download and install spectacle from command line via homebrew. See https://caskroom.github.io/ for info on homebrew, casks, and how to make one for your app.

**Comment by olumby** [comment]
Spectacle already is on Homebrew Cask.

See https://github.com/caskroom/homebrew-cask/blob/master/Casks/spectacle.rb

**Comment by mike-lawrence** [comment]
My Bad, was searching on the html page without realizing the list had been truncated.
