### ISSUE TITLE
Feature Suggestion : Pin window to front

### ISSUE THREAD

**Issue by thibauddavid** [eczarny/spectacle#666]
Hey,

What about adding a togglable "Pin to front" feature to Spectacle menu, which will allows keeping focused window to front ? Working like iOS Simulator `Window -> Stay in front` feature.
That'd be a great addition :)

**Comment by yckart** [comment]
Possible duplicate of: #21, #201, #625, #654...

And:
> No luck with the accessibility API. I could try using something like SIMBL, which is what I believe Afloat is using.
> *https://github.com/eczarny/spectacle/issues/21#issuecomment-2755527*
> …
> Sorry Niv, but it looks like using SIMBL will become something of a mess. I would suggest continuing to use Afloat to do this
> *https://github.com/eczarny/spectacle/issues/21#issuecomment-2755666*

**Comment by eczarny** [comment]
Sorry @thibauddavid, this isn't likely something Spectacle will support. I appreciate you taking the time to open the issue though!
