### ISSUE TITLE
Next third should also align vertically

### ISSUE THREAD

**Issue by patricks** [eczarny/spectacle#668]
Spectral Version 1.1

It would be nice if I could arrange windows via next third also vertically. Currently  if I click next third it arranges the windows horizontally.

**Comment by burtonwilliamt** [comment]
I think that when you do "Next third" it will actually cycle through all 6 "thirds" so first it goes through horizontal, then vertical.

**Comment by eczarny** [comment]
@burtonwilliamt is correct. Try moving through each third by triggering the same shortcut multiple times.
