### ISSUE TITLE
Arrange window with custom padding

### ISSUE THREAD

**Issue by AnthonySchultz** [eczarny/spectacle#67]
It would be awesome if we could arbitrarily set a margin so that what ever app you are aligning, will not go all the way to the edge of the screen. So if I se a 20px margin, and I set an app to go lower left, it would place itself 20px up from the bottom and 20px in from the right. 

I suppose you would want to be able to set the margin individually for each monitor..

I'm not to sure I put this idea in the right place. My apologies if I didn't.

Thanks!

**Comment by s3ththompson** [comment]
+1 to margins/gutters

**Comment by eczarny** [comment]
With this enhancement Spectacle would introduce a configurable padding along the edges of a display and along edges of individual windows. This effectively combines #67 and #413 into one enhancement.

**Comment by solarroger** [comment]
This would be great to see!

**Comment by apazzolini** [comment]
:+1:

**Comment by wmertens** [comment]
And if this ever gets implemented, I'd also like the ability to configure the padding per display...

**Comment by leifniem** [comment]
With all the recent releases i still hope for this feature every time

**Comment by HighDensityAwesome** [comment]
Totally agree, a great little piece of software, with added customization for the user I think it could become even better!
And perhaps set presets, so you give a certain keybinding a preset if you are constantly manually re-sizing a window specifically.

**Comment by rootwork** [comment]
I'd love to see this too. I'm coming from SizeUp too and it's surprisingly helpful, for instance, having padding on the right side allows me to access a column of desktop icons even when a window is oriented to the right or fullscreen.

And making the padding configurable as well allows you to do things like have one app fullscreen-except-for-padding on one side, and another full-screen-except-for-padding on the other side.

**Comment by JesseLeite** [comment]
100% agree. I still use and prefer Divvy for it's margin and gutter customization.

**Comment by kingmatusevich** [comment]
I would like this feature as well

**Comment by chrisdrackett** [comment]
is this feature no longer on the roadmap?

**Comment by eczarny** [comment]
Closed as I have no plans to implement this functionality. Sorry, should have mentioned this when I originally closed the issue.

**Comment by movingobjects** [comment]
For those of us looking for this—I found an app that does it: [Mosaic](https://www.lightpillar.com/mosaic.html)

![mosaic_after](https://user-images.githubusercontent.com/53540/36759322-d179e72e-1bcb-11e8-8d93-f191d5cbfb86.jpg)

**Comment by ctr26** [comment]
Any hope of this being reopened?

**Comment by sniarn** [comment]
I would love to see this implemented. The current behavior just makes things look so cluttered that I find myself just using my mouse for window management.

**Comment by adamkdean** [comment]
Yep, here we are, 2019, and we still need this.

**Comment by karimhossenbux** [comment]
Instead of making a toxic/useless comment, why don't you give it a try if the app is open source?

**Comment by adamalbrecht** [comment]
For anyone interested in this feature, you should check out [Rectangle](https://rectangleapp.com), which is basically a clone of Spectacle, but written in swift.

https://github.com/rxhanson/Rectangle#adding-gaps-between-windows

**Comment by ctr26** [comment]
Doesn't have the window padding feature either as far as I see?On 28 Apr 2020 14:13, Adam Albrecht <notifications@github.com> wrote:
For anyone interested in this feature, you should check out Rectangle, which is basically a clone of Spectacle, but written in swift.
https://github.com/rxhanson/Rectangle#adding-gaps-between-windows

**Comment by sniarn** [comment]
@ctr26 Thanks for the tip. That seems to have the exact feature I was after.

**Comment by adamkdean** [comment]
@karimhossenbux feature demand ≠ toxic/useless. Signalling demand to product owners is simply feedback. For what it's worth, I moved over to Mosaic and couldn't be happier.

**Comment by karimhossenbux** [comment]
@adamkdean there is a better way of asking this
