### ISSUE TITLE
Weird Issue.

### ISSUE THREAD

**Issue by uber1geek** [eczarny/spectacle#670]
I don;t know how to describe this issue, however i will try my best to put it in clear words. If that doesn't work, i will probably do a screen recording.

I am unable to stack two windows side by side eg: chrome and terminal ( unless i explicitly goto that app icon on the dock and click on the open window)  otherwise only one app remains in vertical view and the other disappears on my macbook air 13 running osx 10.11.6 and the latest version of the spectacle app. 
This seems to be an issue with some settings/preferences because I created a new account on my mac and spectacle works as expected.

Any idea on how to fix this ?

**Comment by eczarny** [comment]
A screenshot or screen recording would be really helpful here.
