### ISSUE TITLE
Window not visible when moving a window to a display with a full screen window

### ISSUE THREAD

**Issue by Wietsedv** [eczarny/spectacle#671]
I have two displays and I often want to move a window from my main display to my secondary display. The secondary display has a full screen window open by default, so my moved window obviously moves to a different space on that secondary display, but the visible space does not change. I still see the space of my full screen window instead of the space which contains my newly moved window. Noteworthily, my moved window still has focus despite not being on a visible space, so probably it is not a problem of losing focus. Clicking the dock icon afterwards makes the correct space visible though.

macOS Sierra 10.12.1, Spectacle 1.1

EDIT: When trying to change window to full screen mode while it is still not visible with Control+Command+F, it first seems to go to full screen on top of the window that is already in full screen but when the animation is finished, it moves to my main display, since there can be no two full screen windows in one space.

**Comment by eczarny** [comment]
@Wietsedv mind providing some screenshots? They would help immensely.

**Comment by eczarny** [comment]
Ah, this is like due to the fact Spectacle doesn't play very well with Spaces. Unfortunately I'm not really sure how to resolve this without a substantial investigation into ways Spectacle could interact with Spaces (which Apple does not expose via public APIs).

**Comment by defaude** [comment]
/necro :)

Is there still no proper API available that enables handling Spaces?
