### ISSUE TITLE
Symbolic links to Shortcuts.json are replaced on startup

### ISSUE THREAD

**Issue by schreifels** [eczarny/spectacle#674]
First of all, thanks so much for switching from NSData to Shortcuts.json! This makes backups much, much easier.

However, I noticed some interesting behavior: it seems like if I create a symlink from Shortcuts.json to that file in another location (e.g. Dropbox or a Git repo), the symlink is removed and replaced with a file of the same contents on startup of Spectacle.

Here are steps to reproduce:

1. Quit Spectacle
2. `rm ~/Library/Application\ Support/Spectacle/Shortcuts.json`
3. Open Spectacle, note that the default settings are shown
4. Quit Spectacle
5. `rm ~/Library/Application\ Support/Spectacle/Shortcuts.json`
6. `ln -s ~/p/workstation/dotfiles/spectacle.json ~/Library/Application\ Support/Spectacle/Shortcuts.json`
7. Open Spectacle, note that the settings from the symlink have been loaded, but `ls -lah` reveals the symlink was replaced, which can be confirmed by trying to make a change to your Spectacle config and running `diff ~/p/workstation/dotfiles/spectacle.json ~/Library/Application\ Support/Spectacle/Shortcuts.json`

I'm using Spectacle version 1.1 (648) on OSX 10.12.1. When starting Spectacle on step 7, the only Console output I see is:

```
default	07:41:55.799709 -0700	Spectacle	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
```

Would love to hear your thoughts on this! Thanks,

Mike

**Comment by eczarny** [comment]
Good catch! I'll investigate. There's likely a problem with the way Spectacle is reading the content of this file.

**Comment by eczarny** [comment]
My fix here introduce a bug that would corrupt the shortcuts file. Reverting my changes and pushing a new release.

**Comment by eczarny** [comment]
7fb5f1c should resolve this issue without the problems with my original fix.

**Comment by schreifels** [comment]
Fantastic, thanks @eczarny!
