### ISSUE TITLE
Cannot assign ⌃⌥⌘↑

### ISSUE THREAD

**Issue by marlonrichert** [eczarny/spectacle#676]
I want to assign Top Half to ctrl-alt-cmd-up, but for some reason, Spectacle doesn't accept that. I get to see ⌃⌥⌘ in the input field when I hold the ctrl, option and cmd keys, but when I then press arrow up, nothing happens.

**Comment by sergej-koscejev** [comment]
This happens to me with another app (Magnet), only in my case it is the other way around: Spectacle accepts ctrl-alt-cmd-up but Magnet doesn't. I would also like to know the reason for this.

**Comment by eczarny** [comment]
Is there any relevant output from Console? This works as expected for me but I'd like to know a bit more about what may be going on.

**Comment by eczarny** [comment]
Duplicate of #652.

**Comment by marlonrichert** [comment]
@eczarny, I tried, but it does not seem to produce any output in Console.
