### ISSUE TITLE
Feature request: Drag to resize

### ISSUE THREAD

**Issue by iKristy** [eczarny/spectacle#678]
It would be great to have an alternative to keyboard shorcuts. So, if I would drag windows to the sides or corners of the screen, it would resize them, e.g. dragging to a side edge resizes the window to a half, or dragging to the top edge maximizes the window.

**Comment by syoung1128** [comment]
Yes that would be amazing!

**Comment by eczarny** [comment]
Unfortunately this isn't something I expect Spectacle will support. There are plenty of other full featured window managers that may support this behavior but Spectacle likely will not be one of them. Thanks for the suggestion though!
