### ISSUE TITLE
Option key not registering on MacBook Pro 2016

### ISSUE THREAD

**Issue by danpilat** [eczarny/spectacle#679]
Pressing the option key (both right and left) is not being recorded in the system. Thus, cannot see a way to set option key as part of a shortcut. This does not seem to be the case for any other key.

**Comment by Sekoul** [comment]
Having same issue....

**Comment by zgavin** [comment]
Also having this issue as well in version 1.1.  The issue is not present in 1.0.6.  

@danpilat and @Sekoul, you can work around this for the time being by manually modifying the shortcuts file.  It's a json file located in  ~/Library/Application Support/Spectacle .

**Comment by Sekoul** [comment]
Actually there is not "Spectacle" folder/file inside Application Support for me.... I'm on OSX 10.12 Sierra

**Comment by eczarny** [comment]
Duplicate of #657.
