### ISSUE TITLE
shortcuts stop working on latest mac os

### ISSUE THREAD

**Issue by HawkenKing** [eczarny/spectacle#684]
OS X El Capitan 10.11.3 (15D21)

Spectacle 1.1 (648)

When restarting machine, the only way to get shortcuts back is to quit Spectacle, remove it from Privacy settings, then reopen and re-add to privacy settings.

A normal restart stops Spectacle from working. (set to launch at login)

**Comment by eczarny** [comment]
Sounds like a bug with OS X. I'm not seeing any trouble on macOS Sierra.
