### ISSUE TITLE
Make larger / smaller no longer works in macOS Sierra

### ISSUE THREAD

**Issue by gerrytan** [eczarny/spectacle#685]
Have checked the key isn't clashing with mac's system key (ctrl + alt + shift + left / right). Triggering it via the menu doesn't work either.

This problem only occur with Chrome. iTerm and Finder window works fine

**Comment by wvdk** [comment]
Hmm. It's working fine for me. Even Chrome. Spectacle v1.1, macOS 10.12.1

**Comment by eczarny** [comment]
I'm unable to reproduce the issue with Chrome 55.0.2883.95.
