### ISSUE TITLE
Losing preferences on exiting the app

### ISSUE THREAD

**Issue by nandwana92** [eczarny/spectacle#690]
App version: Version 1.1.1 (657)
Mac OS version: 10.11.6 (15G31)

When I am quitting the app after changing key mappings and starting it again, they are getting reset to defaults. I changed them to the ones in the image, they work fine as long as the current session of the app runs, but get back to default values after quitting and starting the app again. Works fine in v1.1.

![screen shot 2016-12-18 at 10 16 36 pm](https://cloud.githubusercontent.com/assets/5328534/21294954/cab42a16-c56f-11e6-9019-a931d004d9d8.png)

**Comment by eczarny** [comment]
I just found this issue. I stopped pushing 1.1.1 and I'll be working on a fix right away.
