### ISSUE TITLE
Can't open Spectacle on OS X 10.9.5

### ISSUE THREAD

**Issue by sjurtf** [eczarny/spectacle#692]
After an upgrade to the latest spectacle I can no longer open the app.
It crashes on:

```
Application Specific Information:
Assertion failed: (tokenCount < maxCountIncludingZeroTerminator - 1), function CUIRenditionKeySetValueForAttribute, file /SourceCache/CoreUI/CoreUI-231.1/CoreTheme/ThemeStorage/CUIThemeRendition.m, line 136.
```

```
Process:         Spectacle [538]
Path:            /Applications/Spectacle.app/Contents/MacOS/Spectacle
Identifier:      com.divisiblebyzero.Spectacle
Version:         1.1.2 (659)
Code Type:       X86-64 (Native)
Parent Process:  launchd [196]
Responsible:     Spectacle [538]
User ID:         501

Date/Time:       2016-12-18 19:42:36.858 +0100
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  ADF166FD-DED8-0C0E-696A-FC96732AD595


Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
```

I also tried downgrading to 1.1.1, but the same issue is there. I might have used an older version than 1.1.1 before this upgrade to 1.1.2 today.

If the whole trace is needed it can be found here:  https://a.pomf.cat/qhdcns.txt

**Comment by eczarny** [comment]
Seems to be a known issue with Xcode 8, unfortunately. There do appear to be a workaround so I'll look into addressing this in the next release.

**Comment by eczarny** [comment]
@sjurtf let me know if Spectacle 1.0.6 works. I'm hoping to have a fix for this in 1.2.

**Comment by sjurtf** [comment]
@eczarny, 1.0.6 works fine.

**Comment by emjayess** [comment]
same boat / subscribed (thank you)

**Comment by michberr** [comment]
me too, thanks for the info

**Comment by mizzoji** [comment]
Where can I find the 1.0.6 Version. I could download only the 0.8.6. Thanks and hope a new version comes out soon with a fix :D

**Comment by emjayess** [comment]
@mizzoji (et al) fyi I just copied the download url from spectacleapp.com and modified the version... 
* like so, [1.06](https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.0.6.zip)

**Comment by eczarny** [comment]
Curious this build resolves the crash:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2b.zip

**Comment by misterjones** [comment]
**1.2b** didn't resolve the issue for me; continues to crash on open on OS X 10.9.5.
**1.06** continues to work in the interim. :)

**Comment by Meilenstein** [comment]
same to me on OS X 10.9.5
1.2b did not work, 1.06 works

**Comment by KenProchnow** [comment]
same here on OS X 10.9.5 , just upgraded to new version of Spectacle and it won't open. Thanks @emjayess just installed older version as you said and i'm back in action.

**Comment by agseco** [comment]
@eczarny mi crash report in case it's useful: https://github.com/eczarny/spectacle/files/663345/Spectacle_2016-12-20-104159_Alejandros-MacBook-Pro.crash.txt

Let me know if I can help.

Additionally, in the mean time is there any way of downloading the previous release which worked fine?

**Comment by skorth** [comment]
@agseco this one works for me after reboot. https://github.com/eczarny/spectacle/issues/692#issuecomment-268261909

**Comment by mizzoji** [comment]
@emjayess Thanks for the Link (v1.06). 
It worked after killing the previous spectacle process (v0.8.6).

**Comment by agseco** [comment]
@skorth thanks a lot!!!

**Comment by eczarny** [comment]
Sounds like I have a bit more work here. I'll update that test build later today with another attempt to fix the problem. Sorry about the inconvenience folks!

**Comment by eczarny** [comment]
Hey folks. I updated the test build:

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2b.zip

Please see if it helps!

**Comment by eczarny** [comment]
For those interested I'm using this as a guide to resolving the issue:

http://stackoverflow.com/questions/39616332/tokencount-maxcountincludingzeroterminator-assertion-osx-10-9

Crazy bug.
