### ISSUE TITLE
Spectacle not working after updating to 1.1.2 on MAC OSX 10.12.1

### ISSUE THREAD

**Issue by delanoka** [eczarny/spectacle#693]
App not working after updating to 1.1.2 on a Mac running Sierra (10.12.1) whether I use default or customized key commands.

**Comment by eczarny** [comment]
@delanoka can you elaborate more? What specifically isn't working?

Please also include any logging output from Console.

**Comment by delanoka** [comment]
None of the key commands are. The app will open and run in the background but when I have windows open and try to resize using the keyboard commands nothing happens.

**Comment by agseco** [comment]
Same issue here, I'mr running OSX 10.9.5:

![image](https://cloud.githubusercontent.com/assets/7592823/21345339/22c26660-c6a0-11e6-9263-f079ac7d0998.png)

When I launch the app doesn't seem to open, maybe it's crashing. I tried reinstalling after full uninstall and same thing.

I'll be glad to provide logs, where can I find them? Any instructions will be appreciated.

**Comment by agseco** [comment]
Found a crash report in case it helps...

[Spectacle_2016-12-20-104159_Alejandros-MacBook-Pro.crash.txt](https://github.com/eczarny/spectacle/files/663345/Spectacle_2016-12-20-104159_Alejandros-MacBook-Pro.crash.txt)

**Comment by murphyslaw** [comment]
Same for me on `macOS Sierra Version 10.12.2`.

Spectacle shortcuts are not working neither in background or status menu mode, but it does not seem to be crashing for me.

**Comment by eczarny** [comment]
@agseco that's a separate issue tracked by #692.

@delanoka and @murphyslaw does rebooting help at all?

**Comment by murphyslaw** [comment]
@eczarny Rebooting did not help for me. I also tried to quit and restart Spectacle in either background or status menu mode, but shortcuts still do not work. I also checked the accessibility options in the general settings and if the shortcuts might have been taken by other, potentially new keyboard shortcuts, but both is not the case.

**Comment by delanoka** [comment]
Rebooting helped somewhat but for some reason the keyboard commands Ctrl+1 and Ctrl+2 still do not work.

**Comment by murphyslaw** [comment]
I just checked based on @delanoka comment and it seems that only shortcuts with `ctrl` do not work. I tested my shortcuts with `alt` instead and it works.

**Comment by KaraAJC** [comment]
Same happening to me, I updated to 1.1.2, running Mac 10.9.5, but the app wouldn't open after that.  So I uninstalled , restarted my computer, and reinstalled, still not working. I even had a problem with the unzipping utility, so then I reverted to the 0.8.8 download I have, and the app opens, but does not work either. 

Just got a crash report that I emailed through the app.

**Comment by delanoka** [comment]
@murphyslaw my commands of Ctrl+3, 4 and 5 all worked it was just 1 and 2 that didn't

**Comment by barbutti** [comment]
Having the same issue from here on 1.1.2, OS X 10.11.6. It's only affect `ctrl+…` shortcuts; if I do `ctrl+cmd+…` it works normally.

Found these logs in Console.app:

```
20/12/16 2:48:06.025 PM Spectacle[1394]: Received the following error code when unregistering shortcut MoveToUpperRight: -50
20/12/16 2:48:06.026 PM Spectacle[1394]: Received the following error code when unregistering shortcut MoveToLowerLeft: -50
20/12/16 2:48:06.026 PM Spectacle[1394]: Received the following error code when unregistering shortcut MoveToLowerRight: -50
20/12/16 2:48:06.026 PM Spectacle[1394]: Received the following error code when unregistering shortcut MoveToUpperLeft: -50
20/12/16 2:48:09.463 PM Spectacle[1394]: There was a problem registering shortcut MoveToUpperRight.
20/12/16 2:48:09.463 PM Spectacle[1394]: There was a problem registering shortcut MoveToLowerLeft.
20/12/16 2:48:09.464 PM Spectacle[1394]: There was a problem registering shortcut MoveToLowerRight.
20/12/16 2:48:09.464 PM Spectacle[1394]: There was a problem registering shortcut MoveToUpperLeft.
```

**Comment by eczarny** [comment]
Those having trouble with certain shortcuts could you try out this build?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2b.zip

Let me know if it helps.

**Comment by eczarny** [comment]
@KaraAJC you're seeing this issue: #692

**Comment by ashaffer** [comment]
Hey @eczarny that build works for me, and I was also having this problem.

**Comment by morganfidesio** [comment]
I was having the problem as well with shortcuts using ctrl, the new build solved this.

thanks a lot 👍

**Comment by murphyslaw** [comment]
Thanks @eczarny for the quick fix. New build solved the issue for me as well.

**Comment by barbutti** [comment]
@eczarny Yeah, that new build fixed the issue for me here as well! 👍

**Comment by delanoka** [comment]
@eczarny Thanks so much! It fixed the issue for me as well 👍

**Comment by paulmz** [comment]
Hello. I had the same problem with certain "control" shortcuts not working. The Spectacle+1.2b.zip build linked above appears to have fixed the issue. Thanks!

**Comment by eczarny** [comment]
Awesome news! Happy to hear that build fixes the issue. I still have to fix the 10.9 crash but I hope to have a new release out tomorrow. Fingers crossed.

**Comment by zinking** [comment]
1.2b zip works, without icon on the status bar or anything installed. is that a rollback?
anyways, I can work around with 1.2b at the moment. hope 10.9 could be fixed as well. thanks a lot.

**Comment by mdarse** [comment]
Had the issue of the app crashing at launch on `10.9.5` too, got some error:
```
❯ /Applications/Spectacle.app/Contents/MacOS/Spectacle
Assertion failed: (tokenCount < maxCountIncludingZeroTerminator - 1), function CUIRenditionKeySetValueForAttribute, file /SourceCache/CoreUI/CoreUI-231.1/CoreTheme/ThemeStorage/CUIThemeRendition.m, line 136.
zsh: abort      /Applications/Spectacle.app/Contents/MacOS/Spectacle
```
Where can I find previous built versions?

**Comment by mdarse** [comment]
Oops sorry, seems to be more related to #692.
