### ISSUE TITLE
Unable to control windows of remote computer with keyboard shortcuts when using Screen Sharing

### ISSUE THREAD

**Issue by breschke** [eczarny/spectacle#694]
I would like to be able to control a remote computer's windows using spectacle while using Screen Sharing in OSX. This is especially true because I have two screens on the remote computer and often need to move a window in the non-visible screen to the focused screen.

Spectacle is installed on both the host and remote computers, and I can manipulate remote windows when I use the drop-down menu, but keyboard shortcuts are not working.

macOS Sierra 10.12.1 (both remote and host machines)
Screen Sharing 10.12.1
Spectacle 10.12.1 (both machines)

**Comment by eczarny** [comment]
Unfortunately this likely isn't something Spectacle can control. You will probably have to use unique shortcuts on the remote host. in order for this to work. Try adding a shortcut that is most definitely not in use and have Spectacle only running on the remote host.
