### ISSUE TITLE
Center & Size Down

### ISSUE THREAD

**Issue by ncwillia** [eczarny/spectacle#695]
A feature I really liked on SizeUp (similar app) was a "Center" function that resized the window to have a ~25% pixel buffer on each size of the window. Use Case: I have a bunch of other windows open in the background. I center my full screen window to see one of the other windows behind it, and then perform some action (usually snapping one window left and another window right so I can work side by side. See attached photo for desired end-state of "Center and Shrink" function.
![screen shot 2016-12-21 at 11 08 14 am](https://cloud.githubusercontent.com/assets/3877081/21402531/caad8062-c76d-11e6-9de8-c4b03de36f5b.png)

**Comment by eczarny** [comment]
Have you tried using Spectacle's "Make Smaller" command immediately following the "Center" command? Does that accomplish the same end result?

**Comment by mariusmateoc** [comment]
Would be nice when center to be able to choose a percentage of height and width or fixed width and height in pixels so the window to resize and center.

@eczarny using what you mention would not get the same result, and you would need to action multiple times "make smaller" command to get close to that result.

**Comment by eczarny** [comment]
I see. Unfortunately I don't anticipate spending time working on this enhancement. I appreciated the request though!
