### ISSUE TITLE
Fullscreen option: Maximize vs. Fullscreen

### ISSUE THREAD

**Issue by adamtwo** [eczarny/spectacle#696]
After I've upgraded to Spectactl 1.1.2 I've noticed Fullscreen mode behaves differently. It used to maximize windows. Now it put windows in fullscreen mode. 
I couldn't find any mention in the release notes/git commit comments that this change was intentional.

Could you please consider reverting back to maximize behavior or add another action that behaves like the old Fullscreen mode?

thnx,
Adam

**Comment by eczarny** [comment]
What version were you using before? There haven't been any changes to this behavior, at least none that I can remember. Can you provide a video of the behavior you are seeing?

**Comment by adamtwo** [comment]
Eric,
I originally started with 1.1 and it worked for me the way I wanted. It
maxed windows instead of putting them in Fullscreen mode. It was the
feature I needed from spectacle. Many people recommend spectacle because of
this feature.
I'm now on 1.2 and the fullscreen keyboard combo puts windows in Fullscreen
mode.

You are right, this change of behavior may have been caused by some other
O/S update and not by the change in the up itself. The end result is,
though, that the latest version of spectacle doesn't do what I need it to
do on OS X (I'm on 10.11.6 - 15G1212).

If you were able to determine why the behavior has changed I should be able
to submit a pull request with a fix.

BTW, thnx for providing me a free app that has improved my user experience
on Mac :).
Adam

**Comment by eczarny** [comment]
Is this happening with all apps? Or just a particular app? Spectacle isn't capable of moving windows into fullscreen mode so I imagine something else may be intercepting the shortcut.

Something you could try: change Spectacle's fullscreen shortcut to something else. See if that helps.

**Comment by adamtwo** [comment]
That helped, thnx! I looks like control + command + F stroke is serviced by
OS X itself. I've tried with multiple apps and get consistent fullscreen
behavior.
So maybe what changed is which keystroke event handler gets invoked first:
OS X vs Spectacle?

**Comment by eczarny** [comment]
Spectacle should honor it, though there has been some trouble recently with shortcut registration. Technically speaking Spectacle should prevent you from using the shortcut since it conflicts with a system shortcut. For some reason that logic has become really flaky.

In the meantime I'd recommend changing the system shortcut if you would prefer to have Spectacle use it.

**Comment by eczarny** [comment]
In my testing if I assign ctrl+cmd+f to Spectacle's fullscreen window action it works. Disabling Spectacle, or closing the app, results in the normal system behavior of fullscreen mode.

**Comment by adamtwo** [comment]
ok, cool. Thanks for the help and your suggestion!

**Comment by eczarny** [comment]
@adamtwo mind if I close?

**Comment by adamtwo** [comment]
I'm closing the issue.
