### ISSUE TITLE
Left/Right half and then Center leaves a couple of pixels between window and menubar

### ISSUE THREAD

**Issue by julioromano** [eczarny/spectacle#700]
I usually make a window half left and then center it.
This more often than not leaves a couple of pixels between the top of the window and the menubar. Attaching screenshot.
<img width="912" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1273124/21493044/a667499a-cc09-11e6-81e0-c3ed56b4ed68.png">

Running macOS 10.12.2

**Comment by worriorbg** [comment]
Ran into a similar issue and I think I fixed it. Let me know if you want me to send you a version so you can test it on your side.

**Comment by julioromano** [comment]
@worriorbg Yep, with the new file the glitch is gone!  Thanks! Can you submit a PR?

**Comment by worriorbg** [comment]
Done.
