### ISSUE TITLE
Not really an issue, more of a request

### ISSUE THREAD

**Issue by pechar** [eczarny/spectacle#701]
Hi, first of all thanks for this product it is amazing! Been looking for an alternative like this for ages.
What would be nice is to be able to get the window to its original position and size. Something similar to the way Windows does it. I would have thought the Undo and Redo functionality would do this however it only lists through the Spectacle layouts applied.
Many thanks

**Comment by eczarny** [comment]
@pechar similar to what is described in #510?

**Comment by pechar** [comment]
Agreed, apologies I did not see this!

**Comment by pechar** [comment]
Closing as it is no longer relevant
