### ISSUE TITLE
request/inquiry: customize percentage of screen allocation

### ISSUE THREAD

**Issue by mikeliucc** [eczarny/spectacle#706]
Hi,

Fist, great product - one of my MUST HAVE's for MBP!

I'm wondering if it'd be possible to create a shortcut key to customize a user-defined percentage of screen real estate.  For example,

___% left of screen: [short cut key here]
___% right of screen: [short cut key here]
... ..

Can we add this as a feature/enhancement request?

Thanks,
Mike

**Comment by eczarny** [comment]
Closing this in favor #427, which would make enhancements trivial for folks with a little JavaScript knowledge.
