### ISSUE TITLE
Move window one pixel

### ISSUE THREAD

**Issue by arigoldx** [eczarny/spectacle#710]
I looked through the menu options and read through as much of GitHub as possible and think that I might be looking for a feature.

Basically, I'd like to be able to move windows around pixel by pixel. The reason is that I like to line windows up to compare designs.

I'm guessing that I could probably make do by doing a combination of Spectacle commands on both windows but still feel that something that lets you bump windows around pixel by pixel would be quite handy.

**Comment by eczarny** [comment]
Sounds like a good candidate for #427 once I finish up that work.
