### ISSUE TITLE
Fullscreen shortcut collides with some standard searches

### ISSUE THREAD

**Issue by pitkling** [eczarny/spectacle#712]
The standard shortcut for fullscreen (⌥⌘F) collides with some standard applications' search shortcut (most prominently probably Mail.app's Mailbox Search). I suggest adding a shift key to it (and probably also to the Center shortcut, for consistency).

**Comment by reneweteling** [comment]
yeah you can just change the shortcut using the preferences. Had the same with sublime text

**Comment by pitkling** [comment]
Jep, that's true, just thought it might be better to change the default to something that does at least not collide with the standard apps that are boxed with macOS (although I can understand that changing a default setting might not be desirable).

**Comment by eczarny** [comment]
The defaults have been the same for years, changing them now would likely cause more trouble than relief. Thanks for reporting the issue though!
