### ISSUE TITLE
Add ability to use corners (top-left, top-bottom etc), useful for big screens

### ISSUE THREAD

**Issue by reneweteling** [eczarny/spectacle#716]
It would be great if you could add a feature where we can modify our windows in a X and Y manner so that we can easily get a setup with 4 screens for instance. 

Im running on a 4K screen and usually im coding like the screenshot below, now i can only use Spectacle for the X axis than i still need to resize the screens

Thanks guys! Excellent app!

![image](https://cloud.githubusercontent.com/assets/3830933/22285013/2d81f6e0-e2ea-11e6-8f85-45a75f8868a3.png)

**Comment by eczarny** [comment]
In the latest version of Spectacle you can move windows in the corners between thirds. Just repeat the same shortcut. Does that help at all?

**Comment by reneweteling** [comment]
Hey thanks for your response, i know about that feature and i use it allot on my mac 2800 px wide, but on a 4k or even 5k its still to large, so if you would look at better touch tool, that tool has a function to drop a window in a quarter of your screen zo bottom top etc. 

Spectacle is so much better than better touch tool, only.... im missing this feature a bit. 

Hope that youll consider the suggestion! Thanks!!

**Comment by andrewjharms** [comment]
I don't fully understand how to accomplish the corner behavior with the steps you described @eczarny, could you please elaborate?
