### ISSUE TITLE
iTerm2 windows all moved left

### ISSUE THREAD

**Issue by quinncomendant** [eczarny/spectacle#719]
I've started using iTerm2 (v3.0.13) and have enjoyed it's full-height windows (no title bar, only tabs). Sometimes (sorry, intermittent 😬) when using Spectacle to move a window to the left (50%) it moves all open windows to the left. Usually I'm moving a full-screen-width window to 50%, but it also occurs when I have two windows at the right (both 50%) and try to send the top one to the left (50%). 

Just putting this up here in case anyone else noticed this.

**Comment by eczarny** [comment]
@quinncomendant can you provide a video of this behavior? You can use QuickTime Player to record it.

**Comment by quinncomendant** [comment]
Closing this is fine, thanks. I've accepted it's just a conflict with iTerm2's pseudo-full-screen window behavior. It's not worth making an exception in Spectacle for this edge case.
