### ISSUE TITLE
Move fullscreen window to the next monitor

### ISSUE THREAD

**Issue by slaviT** [eczarny/spectacle#721]
It seems that "Next Display" feature doesnt work for full screen windows.

How to reproduce the error:
1. create new window in finder for example (cmd+N)
2. Enter full screen mode (cntr+cmd+f)
3. Hit ctrl+alt+cmd+right arrow for "Next Dispay"

Workaround is to exit the fullscreen mode (ctrl+cmd+f) then move to the next display and than enter the fullscreen mode again.

**Comment by eczarny** [comment]
Known issue. Duplicate of #468.
