### ISSUE TITLE
Chrome Keyboard Shortcuts Overriding Spectacle Shortcuts

### ISSUE THREAD

**Issue by alexrmacleod** [eczarny/spectacle#722]
This is really annoying, How do I remove these damn chrome hot keys which I don't even use? How to get spectacle to work on chrome again?

**Comment by bennypowers** [comment]
I used System Preferences > Keyboard > Shortcuts > App Shortcuts > [+] to change those menu item's shortcut keys, but this did not free up <kbd>opt</kbd>+<kbd>cmd</kbd>+<kbd>left</kbd> for spectacle.

**Comment by bennypowers** [comment]
@alexrmacleod  After you do ☝️ , try opening spectacle prefs and pressing `Restore Defaults`
See if that fixes it.

**Comment by pizzaeater** [comment]
Which shortcut should I change for Chrome? I use option + command + f for fullscreen in spectacle, but in Chrome it's Enter Full Screen menu. I changed it to command + 0, but spectacle still doesn't work.

**Comment by alexrmacleod** [comment]
@pizzaeater exact same problem. still haven't figured out a workaround :(

**Comment by Tensho** [comment]
The same problem, I guess #772 is related.

**Comment by jmatsushita** [comment]
I had the same annoying problem (not being able to use `command + option + f` for Spectacle)  and this worked for me:
 - Use `System Preferences > Keyboard > Shortcuts > App Shortcuts > [+]` and add `Search the web...` and assign it to a different shortcut (I used `command + option + g`)
 - [bonus trap] For some reason spectacle was disabled for Chrome. I had to go in the Spectacle menu bar option, go to Disable, and uncheck `for Google Chrome`.

**Comment by vishalsinha21** [comment]
Suggestions shared above didnt work for me. But somehow updating spectacle to latest version (1.2) did the trick, thought of sharing this info :)

**Comment by sentiasa** [comment]
I'm using 1.2 (672) and this issue is back today :( Any suggestions? (cmd + option + F is search in chrome apparently)

**Comment by James-E-Adams** [comment]
> @alexrmacleod After you do ☝️ , try opening spectacle prefs and pressing `Restore Defaults`
> See if that fixes it.

😅  Thanks @bennypowers! Somehow chrome overrode cmd + option + arrow keys for tab navigation. Hitting restore default fixed it so those shortcuts get routed to spectacle instead, even with chrome in focus.

**Comment by daniellizik** [comment]
I've tried every combination of ⌘ ⌃ ⌥ ⇧ nothing seems to work on 1.2 and osx 10.15.2
