### ISSUE TITLE
Spectacle does not open at login after restart

### ISSUE THREAD

**Issue by stevekm** [eczarny/spectacle#723]
I am using macOS Sierra. Never had this problem on El Capitan. 

From within the Spectacle app, I click the check box that sets the app to start on login. Upon checking my system preferences login items under my account, Spectacle appears correctly (see screenshot). 

<img width="451" alt="screen shot 2017-02-04 at 5 35 24 pm" src="https://cloud.githubusercontent.com/assets/10505524/22622316/38594d20-eb05-11e6-833f-7b291a183942.png">

However, after restarting the computer and logging back in, Spectacle does not actually start. If I go back into my login items page in the preferences, the icon for Spectacle has been replaced with a blank white icon, and there is a yellow notification icon next to it, and I have to start the app manually again. 

<img width="457" alt="screen shot 2017-02-04 at 6 09 18 pm" src="https://cloud.githubusercontent.com/assets/10505524/22622317/385ac13c-eb05-11e6-8b6b-657632728830.png">

Any ideas how to fix this? This still occurs even if I unlock my preferences and enter my account password before setting the app as a login item.

**Comment by markn86** [comment]
+1. Get the same issue.

**Comment by eczarny** [comment]
I've never seen this before... Have either of you tried completely removing Spectacle (including any preference plist in `~/Library/Preferences`) and trying to add it as a login item again?

**Comment by ymolchanov** [comment]
Yes, reinstall fixed this issue for me.
