### ISSUE TITLE
adding a 2/3 screen portion option

### ISSUE THREAD

**Issue by dimitrieh** [eczarny/spectacle#725]
@eczarny would it be simple to add an option to allow for:
- left aligned 2/3 screen
- right aligned 2/3 screen

When I have 1 of my windows taking up a third, i want to be able to perfectly fill up the other 2/3 with another application as well.

**Comment by eczarny** [comment]
Have you tried pressing the same shortcut to move to the left or right halves more than once? This should cycle the window between 1/2, 1/3, amd 2/3.

**Comment by dimitrieh** [comment]
@eczarny is this documented? I love this feature and hadn't discovered it myself!

**Comment by eczarny** [comment]
Just updated the README in a8932c0:

> Windows may also be resized between thirds using any of the shortcuts above. For example, to have a window resized between 1/3 and 2/3 of the left region of the screen simply activate the left half ⌥⌘← keyboard shortcut more than once. Each time the shortcut is activated Spectacle will move the window between 1/3, 2/3, and back to 1/2 of the left side of the screen. This feature also applies to the upper left, lower left, upper right, and lower right shortcuts.
