### ISSUE TITLE
Fullscreen is short on the bottom side

### ISSUE THREAD

**Issue by Maslor** [eczarny/spectacle#730]
<img width="1136" alt="screen shot 2017-02-15 at 12 12 34" src="https://cloud.githubusercontent.com/assets/9674408/22973987/1681ad52-f378-11e6-8b57-18ab39c8f473.png">
I formatted my mac and reinstalled spectacle but now its fullscreen doesn't cover the entire fullscreen, it's a little short on the bottom side, as you can see in the image.
Is this a known issue?

**Comment by igryski** [comment]
Possibly related issue fullscreen not covering left side (see screenshot).
![screen shot 2017-02-17 at 11 33 07](https://cloud.githubusercontent.com/assets/7983626/23062156/fbd2cbce-f504-11e6-9f7e-5a45cc37088c.png)

**Comment by eczarny** [comment]
@Maslor @igryski are you hiding your Docks? If so that space is used by macOS.

**Comment by eczarny** [comment]
Closing as I believe this is expected macOS behavior (to not include that space as part of the visible frame of the screen). Please reopen if the Dock is not being hidden.

**Comment by Maslor** [comment]
@eczarny Yes, I am hiding the Docks. The solution I found for the issue was to manually extend the window so that it covered my full screen. From then on, spectacles recognises my true full screen instead of leaving the bar at the bottom.

**Comment by OJFord** [comment]
@Maslor Does that still work for you? Mine resets to having a space as soon as I use a Spectacle shortcut.

@eczarny Is there nothing Spectacle can do to override this? As above, one can manually use that space. I've effectively disabled my Dock completely (extremely long hide delay) since I never use it, so this strip of unused space is nothing but annoying.

**Comment by Maslor** [comment]
Actually it doesn't work for me anymore @OJFord 
When I have a dark background, I don't notice it so it doesn't bother me that much. When I have a colourful background though, it's pretty noticeable, as you can see in this screenshot.

<img width="1270" alt="screen shot 2017-07-02 at 16 18 25" src="https://user-images.githubusercontent.com/9674408/27771211-1d41faf8-5f42-11e7-84c4-565acd33733c.png">
