### ISSUE TITLE
Json file for disabled application? 

### ISSUE THREAD

**Issue by Kerruba** [eczarny/spectacle#732]
Hello, where I can check if I've disabled spectacle for a certain application? 
If there's no file for such thing, it may be really helpful to define disabled applications in a json file - like we do on Shortcuts.json - for tracking and batch processing.

**Comment by eczarny** [comment]
You can find the list of disabled applications in Spectacle's preferences plist in `~/Library/Preferences`. No plans to move these settings elsewhere. macOS provides a helpful command line utility to modify these files, making automation easy.
