### ISSUE TITLE
The app doesn't work

### ISSUE THREAD

**Issue by PeterKuralt** [eczarny/spectacle#733]
I have installed the app on macOS Sierra.

I've allowed Spectacle to control my computer (System preferences > Security & Privacy >Accessibility>Privacy).

***Problem solved**: the issue is with mbp2016 which does not recover properly from lock/screen mode. When going back to arrange screens in preferences the app works like a charm. 

P.S. Best app for me on Mac.

**Comment by eczarny** [comment]
@PeterKuralt have you tried restarting your computer at all?

**Comment by PeterKuralt** [comment]
@eczarny 

I have found out that it was actually mb2016 problem. After switching to lock/sleep mode it doesn't recover and app doesn't work.  When I go to monitoring setting and arrange screens it starts to work again.
