### ISSUE TITLE
Download link down for 0.86

### ISSUE THREAD

**Issue by get-json** [eczarny/spectacle#734]
https://s3.amazonaws.com/spectacle/downloads/Spectacle+0.8.6.zip

**Comment by barbeque** [comment]
Amazon AWS, where the download is hosted, seems to be having problems at the moment: https://status.aws.amazon.com/

Please try it again in a bit when things have settled down.

**Comment by get-json** [comment]
My bad, I forgot S3 was down. Didn't realize it till my jobs started failing
