### ISSUE TITLE
Move window to the middle third of the screen, with half of the screen height

### ISSUE THREAD

**Issue by konstantinmiller** [eczarny/spectacle#741]
Hi,

not sure if I didn't find this feature or if it's actually not there.

I can resize a window to one third of the screen width and half of the screen height, which is nice! But I cannot afterwards put this window in the center of the screen. The shortcut that moves the window between left third, middle third, and right third of the screen immediately resizes the window to half the height of the screen.

Thanks!
Konstantin

**Comment by eczarny** [comment]
Unfortunately this isn't supported. Assuming I'm understanding the request.

Hopefully, if I get some time this summer, I'll try and get around to finishing #427.
