### ISSUE TITLE
Chrome sometimes stops responding normally.

### ISSUE THREAD

**Issue by mikestopcontinues** [eczarny/spectacle#746]
Running Mac 10.12.3 and Spectacle 1.2. Most recent version of Chrome. This bug has persisted for some time.

After restart, Chrome responds fine for a while. Then it's crazy town. Moving left, the window will slide to the middle of the screen, but it's width won't adjust to reach the edge. 

Maximizing or moving to top/bottom extends the width incrementally. It takes a dozen presses for the window to reach both edges.

It seems like a chrome bug, as the same issue occurs with Magnet. But I figured I'd post it here, as you might be able to file a more poignant bug report with Chrome.

Thanks!

**Comment by eczarny** [comment]
Chrome periodically runs into issues with apps like Spectacle. I don't really have the time to dig into these reports unfortunately.
