### ISSUE TITLE
Multi workspace support

### ISSUE THREAD

**Issue by nylqd** [eczarny/spectacle#747]
Is there any possible to add multi workspace support? 
it would be nice if spectacle can move window to different workspace just like move to different display

**Comment by pburkholder** [comment]
+1.  I use Cmd-Ctrl-Left and Cmd-Ctrl-Right with SizeUp all the time. This feature is what I need to make the switch. Thanks, P.

**Comment by eczarny** [comment]
Closing as a duplicate of #15.
