### ISSUE TITLE
Some apps stuck to left when moving next or previous third

### ISSUE THREAD

**Issue by sseyalioglu** [eczarny/spectacle#750]
Some apps like whatsapp or messages cannot get to middle or right most. The shake in first third and cannot move anywhere else.

**Comment by jorvi** [comment]
I have this same issue. It stems from the fact that some windows (example: Mail and Calendar also suffer from this, but Finder doesn't) can't be made more narrow. If you use Magnet.me, it actually throws up a nice warning pop-up, and moves the problematic window anyway. This seems, to me, like a very sensible approach.

<img width="1440" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6699838/26172689/90f8d006-3b49-11e7-8b91-110f81531690.png">
