### ISSUE TITLE
Mouse follows focus

### ISSUE THREAD

**Issue by eugenetaranov** [eczarny/spectacle#751]
Hello,

I am using Spectacle v1.2. Is it possible to enable mouse-follows-focus (i.e. when window in another workspace/display becomes active, mouse should jump there)? If not, would it be something that can be added to spectacle later?

Thank you

**Comment by joejoe79** [comment]
This reminds me, I hope this is ok, how about a linux fashion focus-follows-mouse (sloppy, no auto-raise) ? Clearly out of field, but I see kwm started that way, so maybe?: 

"Kwm started as a simple project to get true focus-follows-mouse support on OSX through event tapping."

**Comment by eczarny** [comment]
This isn't something that will be added to Spectacle.
