### ISSUE TITLE
Feature suggestion: Always on top

### ISSUE THREAD

**Issue by lottakash** [eczarny/spectacle#755]
Thanks for such an amazing app for my macbook. Found it very useful and easy to use. Especially for a regular consumer like me. 

It would be cool if you could implement an option that locks a window "always on top." There might be some apps out there that has it, but having it combined with Spectacle would be amazing.

**Comment by keenahn** [comment]
I second this. I would be interested in helping make this happen (but I'd have to learn more about macos first :))

This app does it https://github.com/JadenGeller/Helium

**Comment by eczarny** [comment]
Unfortunately this isn't functionality I intend to add to Spectacle.
