### ISSUE TITLE
Feature suggestion: resize windows to two thirds

### ISSUE THREAD

**Issue by tumpotumpta** [eczarny/spectacle#756]
Something I'm missing after switching to Spectacles from Magnet is the ability to resize a window to the two right or left thirds of the screen. This helps when you want to work with two windows simultaneously but one of them needs more room than the other one.

EDIT: I feel a bit stupid right now. I discovered by accident, that when you repeatedly press the 'Left Half' or 'Right Half' shortcut, the windows cycles through half, one third and two thirds on that side.

**Comment by sambigelow** [comment]
@tumpotumpta can I ask why you closed this?

**Comment by MightyPixel** [comment]
@tumpotumpta Thanks for updating the question! I needed that as well.
