### ISSUE TITLE
Weird Screen Order? 

### ISSUE THREAD

**Issue by Ashtonian** [eczarny/spectacle#760]
I have a MBP with two dells attached via usb C to Displayport. I have the MBP screen on the far left a dell in the middle and a dell on the right. Spectacle treats the MBP as if its in the center all the time so when I use move window to "next" display it moves it to the left. Rather then the right which is a bit weird ?

**Comment by Ashtonian** [comment]
I was able to achieve the desired behavior by switching the direction of the keyboard shortcuts so that ctrl + alt + cmd + -> moves the window to previous display and ctrl + alt + cmd + <- moves it to next display. 

Fixes it for me, but that seems like odd behavior ?

**Comment by eczarny** [comment]
Closing as a duplicate of #298.
