### ISSUE TITLE
Avoid gap due to hidden dock when resizing

### ISSUE THREAD

**Issue by cbrnr** [eczarny/spectacle#763]
I think it would be nice if Spectacle had an option to ignore the gap that the dock creates if it is hidden (see [here](https://apple.stackexchange.com/questions/141800/gap-at-the-bottom-of-maximized-windows) for more details on this behavior). This should be possible, because if the dock is hidden at the bottom, the bottom window border can't be dragged all the way to the bottom edge of the screen. However, you can move the window all the way to the bottom, and then resize the top border all the way up to the top edge of the screen.

**Comment by eczarny** [comment]
This has been mentioned quite a bit before. Unfortunately I don't have any plans to add this functionality.
