### ISSUE TITLE
Spectacle tagged as malware by Ikarus

### ISSUE THREAD

**Issue by gabhain** [eczarny/spectacle#766]
I'm sure its a false positive but it's flagged as: PUA.OSX.Adware

Can see in the virus total report:
https://www.virustotal.com/en/file/5ba38f59dd1eabb539ec1cfd04be82286382e896eae9f0f43be7ad7861b061a2/analysis/

**Comment by eczarny** [comment]
I'm not seeing anything in the report that flags Spectacle as malware?

**Comment by eczarny** [comment]
Closing for now. Not really sure how actionable this is.
