### ISSUE TITLE
move apps between desktop

### ISSUE THREAD

**Issue by jujes** [eczarny/spectacle#773]
Hi, someone know if this feature is available or planned for some future release?
thanks in advance,

**Comment by ManuDevelopia** [comment]
+1 to this feature, would be very nice to have!

**Comment by eczarny** [comment]
If you mean moving windows between monitors, Spectacle already supports that. If you're talking about moving windows between Spaces that's an entirely different story. Unfortunately this isn't something I intend to support. See #15.
