### ISSUE TITLE
Question / Issue: speed and smoothness of window animations

### ISSUE THREAD

**Issue by lewallen** [eczarny/spectacle#775]
Hello, thanks for the great app!
I've noticed that for most of the window transitions where the window is re-sized, there is a noticeable lag (as compared to the transitions where the window is moved but not re-sized, for example). I was mostly just wondering if this is an unavoidable consequence of the way windows are drawn in osx/macOS, or if it's actually a consequence of one of those macOS "animation" features which can be somehow disabled in terminal.
This probably doesn't count as an issue / feature request, unless of course there's some way to shorten the lag by tweaking the app.
Thanks a lot!

**Comment by eczarny** [comment]
Unfortunately Spectacle doesn't really have that much control over how it moves and resizes windows. It simply asks the OS to do what it wants via macOS' accessibility API. Not much to be done here I don't think.
