### ISSUE TITLE
Switch Spaces [enhancement]

### ISSUE THREAD

**Issue by drpiou** [eczarny/spectacle#778]
Hi, I use Spectacle with happiness since the beginning and many thanks for your work.
I still have a wish I would like to have that would be switching apps to prev/next Spaces (and still conserving the ability to switch screens).

**Comment by OJFord** [comment]
This is a duplicate of #15 (and numerous other duplicates) which was closed as 'won't implement'.

**Comment by drpiou** [comment]
Damn, so sorry to hear I must find an another app, not because of the lack but because of your behavior under the global requests that you want to ignore. Thanks anyway :)
