### ISSUE TITLE
Feature suggestion - 2/3 windows

### ISSUE THREAD

**Issue by mhurron** [eczarny/spectacle#782]
It would be nice if windows could be moved to the left or right 2/3's. Basically like the way the 'Next Third' option works but take up the first and second third of the screen for left third, and the right third would be the second and third thirds.

**Comment by danielzen** [comment]
Actually, you can already get this functionality from Spectacle.

Use the "Left Half" shortcut twice in a row to get the left 2/3rds, or 
use the "Right Half" shortcuts twice in a row for the right 2/3rds.

Hope that helps.
