### ISSUE TITLE
FEATURE REQUEST - 1/6th (top or bottom 1/3rds)

### ISSUE THREAD

**Issue by danielzen** [eczarny/spectacle#783]
I have a 4K screen and would love to be able to quickly use the top or bottom of the 1/3rds.
Maybe 4 more shortcuts:

- Next Top Third
- Previous Top Third
- Next Bottom Third
- Previous Bottom Third

I can see there are decent _WindowCalculationSpec_, before writing a _WindowPositionCalculator_, and finally tie it to the Shortcuts and then add it to the Preferences. Unfortunately I'm not an Obj-C or Swift developer. But I do have the interest (although maybe not the time... :)

**Comment by eczarny** [comment]
Closing in favor of #427.
