### ISSUE TITLE
Spectacle leaves margins around certain windows? (e.g. GNU Emacs)

### ISSUE THREAD

**Issue by jamiecollinson** [eczarny/spectacle#784]
Apologies if this is a case [as mentioned in common issues](https://github.com/eczarny/spectacle#spectacle-does-not-resize-a-particular-window-as-expected) (though it seems slightly different), but I couldn't see it mentioned anywhere despite several people using emacs.

I'm seeing a margin around [GNU Emacs](https://emacsformacosx.com/) with spectacle, but not with any other windows (including iterm2). Is this expected and is there anything I can do about it? I know emacs carries lots of weirdness - e.g. Magnet doesn't work with it at all - but I thought I'd check.

Here's a screenshot in case it helps:

<img width="1280" alt="screen shot 2017-07-13 at 18 47 16" src="https://user-images.githubusercontent.com/3263722/28180328-b3b4d9f2-67fc-11e7-9d11-800994e399d2.png">

**Comment by eczarny** [comment]
This scenario is actually described in the README below the common issue you linked:

https://github.com/eczarny/spectacle#spectacle-behaves-strangely-with-terminal-windows

**Comment by jamiecollinson** [comment]
Are you sure? This is the gui version of Emacs compiled with '--with-cocoa'.

I saw that comment in the docs before posting but as it specifically referenced terminal like windows which snap to columns - and Emacs seems to be freely resizable manually - I figured it was something different.

**Comment by eczarny** [comment]
My understanding of the macOS build of Emacs is that it tries to avoid partially obscuring a row or column of the editor. This is the exact same behavior as most Terminal emulators on macOS as well.

**Comment by jamiecollinson** [comment]
I guess you're right - I hadn't noticed before but I do see the terminal
style size (e.g. 80x36) in the title bar.

I'd love to know if it's something which can be configured with build flags
and will do some digging. Interestingly the `macports` version at
https://github.com/railwaycat/homebrew-emacsmacport does work correctly.

Keep up the good work with Spectacle - big fan and finding it works better
than Magnet which I was previously using. Magnet doesn't resize GNU Emacs
at all!
