### ISSUE TITLE
Chrome "resize event" ❓

### ISSUE THREAD

**Issue by breadadams** [eczarny/spectacle#799]
* Spectacle `Version 1.2 (672)`
* MacOS 10.12.6

After doing some work using the javascript `resize` event, it seems that it doesn't fire when resizing a Chrome window via Spectacle (may be the same with other browsers, I can test if necessary).

I'm not sure who this is on (Chrome, MacOS or Spectacle), as I'm unaware of which method you're using to resize the browser window, but surely there must be a way to make it _behave_ like a regular resize action?

Thanks

**Comment by chriswait** [comment]
@breadadams I failed to reproduce this in Chrome after doing the following:

1. Navigate to this page, open the developer tools console

2. Enter `window.addEventListener('resize', () => { console.log('resize') })` into the console

3. Resize the window to _Left Half_ using Spectacle

Outcome: The console outputs 'resize', and does so each time the window is resized.

Environment:

- Spectacle Version 1.2 (672)

- MacOS 10.12.6

- Chrome 61

![screen shot 2017-09-20 at 9 20 28 pm](https://user-images.githubusercontent.com/2563474/30641265-c5ba88e4-9e49-11e7-922d-c1c8037f4128.png)

**Comment by breadadams** [comment]
Yeah you're right @chriswait, I see the `resize` output in console too. I'm not sure what was causing the issue for me back then but since so I've seen it working fine with Spectacle. Thanks!
