### ISSUE TITLE
macOS High Sierra Compatibility

### ISSUE THREAD

**Issue by SuyashLakhotia** [eczarny/spectacle#805]
It seems like `Center` and `Fullscreen` don't take into account the space the Dock is taking in macOS High Sierra. Screenshots below (notice the bottom part of the screen, near the Dock):

**Center:** https://imgur.com/a/90r6M

**Fullscreen:** https://imgur.com/a/sRJbB

**Comment by SuyashLakhotia** [comment]
Hmm. Seems to have fixed itself.

**Comment by designgrill** [comment]
Another system restart (just after upgrading to High Sierra) fixed it for me.
