### ISSUE TITLE
full screen doesn't fit to top of screen and cuts under dock

### ISSUE THREAD

**Issue by jstoebel** [eczarny/spectacle#834]
Specticle 1.2,  OSX 10.13.2

See screen shot. When I activate full screen the window leaves space at the top and cuts under the dock. This is the first time I've experienced this issue.

Thanks for this amazing project!

![screen shot 2018-01-09 at 6 34 04 am 2](https://user-images.githubusercontent.com/12101566/34719087-4b485a90-f507-11e7-86d2-1367968e829d.png)

**Comment by beshur** [comment]
Try restart the OS
see #832

**Comment by ttben** [comment]
Possibly duplicate of #787 and #680

**Comment by jstoebel** [comment]
Thanks that solved it.
