### ISSUE TITLE
Rename "Make Larger" in "Make Bigger"

### ISSUE THREAD

**Issue by mattia** [eczarny/spectacle#837]
In the current version of the app the "Make Larger" action augment the width and height of the window. As a non-native English speaker when I first read that I thought that it would make the window wider.
Would you be interested in a PR that renames the label from "Make Larger" in "Make Bigger"?
I already have a branch in my fork that does that (migrating the older shortcuts to the new name)

Thanks for the hard work!

**Comment by tbmreza** [comment]
Because Large == Big?
I assume that you want distinction between making the window's size increases _just_ in width and _just_ in height.

I think what you might want to suggest is 'Make Wider' or 'Increase Width' and 'Increase Height'. 'Make Larger' is correctly making the window taller and wider.

**Comment by mipstian** [comment]
The Italian word "largo" is a "false friend", it means "wide" and not "large". This would only affect some Italian users (and some Spanish users; apparently there "largo" means "long"). I don't think the wording in the app should be changed because of this, but localizing the app would help :)
