### ISSUE TITLE
Garbled preference panel

### ISSUE THREAD

**Issue by ntsuji** [eczarny/spectacle#84]
Attached screenshot describes everything.
![spectacle](https://f.cloud.github.com/assets/3109213/28866/4ffd7a26-4cf0-11e2-9833-d51549bc3789.png)
This screenshot has taken with default settings, so, C, F, and Z have garbled.
I'm using Spectacle 0.7 on my MBP13 Retina with OS X 10.8.2.

**Comment by eczarny** [comment]
Bumping priority. See https://github.com/eczarny/spectacle/issues/329#issuecomment-78024589 for some potential details on a fix.

**Comment by eczarny** [comment]
I would love to figure this out but I'm not very familiar with the Carbon text input sources API to understand why this is happening.
