### ISSUE TITLE
Issue opening Spectacle on startup

### ISSUE THREAD

**Issue by madskatie** [eczarny/spectacle#846]
Hello,

I love your app. However, I can't seem to get Spectacle to start at login on my Mac. I've flicked the switch in the program, and I've gone into system preferences etc on the computer as well. I also had a programmer friend look at it and he also couldn't get it to work. I wondered if you have any advice?

Thanks!

**Comment by ilar** [comment]
Seconding this issue, I've always had to start it myself on restart.

**Comment by Clendenin** [comment]
Solution: Your download did not install correctly (I think the issue stems from not having the application in your actual applications directory if I remember correctly). To fix this just go ahead and re-download the project and this time double check Spectacle is placed in your applications dir. Then check that that switch in the application itself is toggled on. Further check that Spectacle is listed as a "login item" in System Preference -> Users & Groups -> Login Items. That should do the trick.

**Comment by ilar** [comment]
Fixed it for me, passing this along to our sysadmin.

**Comment by iwllyu** [comment]
@Clendenin's solution worked for me. My spectacle was in the download folder so I just dragged it into applications. I didn't see it under login items so I closed and then reopened spectacle, checked `Launched spectacle at login` under spectacle settings, and then saw it under Login Items

**Comment by madskatie** [comment]
It worked for me too! Thanks for your help.
