### ISSUE TITLE
Spectacle deletes public/index.html

### ISSUE THREAD

**Issue by nurikabe** [eczarny/spectacle#859]
If I supply a different filename, for example:

    spectacle swagger.yaml -f api.html

Spectacle will still delete `public/index.html`

**Comment by barbeque** [comment]
I think you might be looking for [`sourcey/spectacle`](https://github.com/sourcey/spectacle) instead of this one, which is a window-management tool for macOS.

Have a nice day!

**Comment by nurikabe** [comment]
Oops!
