### ISSUE TITLE
Shortcut to place a window into the corners of the screen

### ISSUE THREAD

**Issue by mrumpf** [eczarny/spectacle#872]
When working on 4K screens moving a window to a half of the screen is just wasting a lot of space.  
On 4K screens moving them into the corners (a quarter) is a better utilisation of the available screen size.
It would be great if you could add a feature to move windows into the corner of the screen.
Maybe a shortcut to circle a window around the corners.

The issue #716 was asking for the same feature but the requester was happy with the move the window to a third of the screen. I'm asking for a quarter and into the corner so that I can have 4 windows open at the same time.

**Comment by FreddyHurkmans** [comment]
It seems that the behaviour you want is already there: Upper Left, Lower Left, Upper Right and Lower Right. The default shortcuts are, if I remember correctly shift-control-command-left for Upper Left and control-command-left for Lower Left (same for right).

**Comment by mrumpf** [comment]
Thanks for the hint!
