### ISSUE TITLE
Terminal window does not take the total height of the screen [Mojave]

### ISSUE THREAD

**Issue by remyduthu** [eczarny/spectacle#874]
The terminal window does not take the full screen height when applying keyboard shortcuts.

<img width="841" alt="capture d ecran 2018-08-27 a 15 50 01" src="https://user-images.githubusercontent.com/36485585/44663449-e13efb80-aa10-11e8-8ead-09df631b1297.png">

**Comment by pronoiac** [comment]
That sounds like [the situation noted in the README,](https://github.com/eczarny/spectacle/blob/master/README.md#spectacle-behaves-strangely-with-terminal-windows) about how the terminal doesn't do half-lines. Does that sound like a match?

**Comment by jlhall** [comment]
If this is iTerm2, you can enable this:
Preferences - Advanced - Windows - Terminal Windows resize smoothly - Yes

**Comment by remydt** [comment]
Perfect!
Thanks :)

Rémy DUTHU

**Comment by mkarnicki** [comment]
This also fixed it for me. Since it was clearly a mac OS (Mojave) + iTerm2 issue, I would consider closing this one @remydt . Cheers!
