### ISSUE TITLE
Mojave - Accessibility Never Seems to "Stick"

### ISSUE THREAD

**Issue by sfhaney** [eczarny/spectacle#880]
I get a prompt on Mojave that Spectacle requires Accessibility access and so I go to System Preferences but for some reason in the +/- application list, it doesn't show Spectacle with the checkbox (like I would expect).  I tried to drag/drop Spectacle in the Accessibility window and also use the + and select the application but it doesn't seem to make a difference.

Not sure if this is an issue with Mojave in general or something compatibility related b/w Mojave and Spectacle.

**Comment by drmjp93** [comment]
Did u succeed to make it run on mojave then?

**Comment by sfhaney** [comment]
@drmjp93 - the app is "running" on Mojave but it doesn't seem to be functional as none of the commands have any effect on the windows.  I'm guessing thats related to the Accessibility access never being applied.

**Comment by sfhaney** [comment]
I tried deleting Spectacle.  Downloaded latest 1.2 zip from site.  On launch I get the expected Accessibility prompt.  I click Open System Preferences.

![image](https://user-images.githubusercontent.com/6844484/46261509-22b44200-c4ba-11e8-88a9-469343a8905e.png)

In past OS versions I would expect to see Spectacle listed in this app list.  But all I see is a blank list.

![image](https://user-images.githubusercontent.com/6844484/46261519-411a3d80-c4ba-11e8-9b06-3ef28e0ff9dc.png)

I've tried using the + to add Spectacle but it seems like its never recognized as being granted permissions.  I realize the lock is locked, I unlocked it and it still didn't seem to make a difference.

Any ideas?

**Comment by drmjp93** [comment]
I saw in mine I have spectacle there in the list.
On using + button, I am given a windows to add apps as you did.

For me I would like to share may be why its working with me? But its a long shot:

I had it installed on 10.13.5, updated to 10.14 without removing anything and it was working.
Was it same for you?

Other way is to contact apple support and ask them to help you out with deleting some config file or plist form library folder which they will guide you during support.

Previously I had problem adding/removing apps in accessibility menu but I didn't found the chat transcript :(

**Comment by sfhaney** [comment]
Closing the issue.  Seems to be possibly caused by Trend Micro AV software.  Although ironically now it seems Spectacle is added properly to my Accessibility apps so who knows what happened.  Thanks for the responses.

**Comment by hubertjakubiak** [comment]
I've just experienced the same issue on Mojave 10.14.2. I can't add Accessibility for Spectacle even manually.

**Comment by CalderMarshall** [comment]
@hubertjakubiak ditto, same osx version

**Comment by sfhaney** [comment]
@CalderMarshall , @hubertjakubiak 

I had chalked it up to having to TrendMicro AV on my machine (due to work requirements).  I did find when booting up in Safe mode that Spectacle loaded in Accessibility without issue.  

My work ITOps were not very receptive to disabling TrendMicro so I just resigned to the fact it would be a permanent restriction.

**Comment by christopherdietrich** [comment]
@sfhaney 
We found that adding `/Library/Application Support/com.apple.TCC/TCC.db` as a "Scan Exclusion" in Trend Micro resolved the issue.
That file is protected by SIP, so maybe you can persuade your IT dept to try that...

**Comment by CalderMarshall** [comment]
My machine has got ESET Endpoint Antivirus on it, but I cannot confirm that is what is blocking adding the application to Accessibility list
