### ISSUE TITLE
Fullscreen option window behind dock

### ISSUE THREAD

**Issue by jorenvh1** [eczarny/spectacle#892]
I updated to Mojave and now my fullscreen shortcut makes my windows go completely fullscreen (behind the dock at the bottom)

It used to scale untill right above the dock, is this a bug?

**Comment by kubilaykarpat** [comment]
Can confirm this problem with Mojave

**Comment by jorenvh1** [comment]
@kubilaykarpat For some reason I don't have this issue anymore... Maybe a reboot fixed it?
