### ISSUE TITLE
Feature request: Disable shortcuts

### ISSUE THREAD

**Issue by Luc45** [eczarny/spectacle#912]
Hi,

It would be awesome to be able to disable shortcuts that I don't intend to use in Spectacle.

Best,
Lucas

**Comment by yochem** [comment]
![](https://media.giphy.com/media/toYucopwGl17U8W0ro/giphy.gif)

**Comment by Luc45** [comment]
lol, I feel stupid.

Thanks, closing this 🤣

**Comment by yochem** [comment]
No problem, glad to help! 👍
