### ISSUE TITLE
Please don't go, take my money!

### ISSUE THREAD

**Issue by Spaceghost** [eczarny/spectacle#939]
I'd give you $100 once, or heck a reasonable subscription to keep going!

**Comment by stgarf** [comment]
@Spaceghost @rxhason has had a great [spectacle alternative, called Rectangle](https://github.com/rxhanson/rectangle) for quite a bit now. Highly recommended :)

**Comment by juliana0101** [comment]
Retângulo//PHYTON
Eu quero
