### ISSUE TITLE
Move to desktop shortcut

### ISSUE THREAD

**Issue by dantebarba** [eczarny/spectacle#946]
Hi

First, thanks a lot for this very useful application. I've been using it since I started using OSX. 

If it's not too much to ask, can you add a shortcut to move the currently selected window between desktops. I don't know any other way than dragging the window to the edge of the screen, which is quite annoying considering that there is a shortcut available in Ubuntu to do the same.

Regards

**Comment by luisfrocha** [comment]
Hi Dante. You can customize it so that it uses any shortcut you prefer. For example, I set mine to match what Spectacle uses, which is Cmd+Option+Control+Arrow key (either left or right).![image](https://user-images.githubusercontent.com/7130389/86175434-f2fbf900-bae8-11ea-968e-0f47edb67615.jpeg)

**Comment by dantebarba** [comment]
> Hi Dante. You can customize it so that it uses any shortcut you prefer.
> Sorry for my previous answer; I got them mixed up lol Since Spectacle is no longer being developed, I started using Rectangle, which was the screenshot I originally sent.
> 
> Below is the correct screenshot for my Spectacle settings.
> 
> ![image](https://user-images.githubusercontent.com/7130389/86175719-74ec2200-bae9-11ea-9825-4752c95b8967.jpeg)

Unfortunately "Next Display" only works when you have more than one display monitor connected, it doesn't move the window from one desktop to another. 

I realized that the project was discontinued after I had opened this ticket. I'll repost this in Rectangle repository.
